In [525]:
import pandas as pd
import plotly.express as px
from datetime import datetime
import os
import re 
from tqdm import tqdm

In [526]:
pd.set_option("display.max_colwidth", 100)  # after this you can print any column length
pd.set_option("display.max_rows", 7)  # after this you can print any column length
pd.set_option("display.max_columns", None)  # after this you can print any column length

## Load data

In [657]:
data_dir = 'raw'
motions_data_path = os.path.join(data_dir, 'motions_bp.csv')

if not os.path.exists(motions_data_path): 
    raise FileNotFoundError('Local data file not found. Please run the data collection notebook first.')

df = pd.read_csv(motions_data_path, index_col=0)
df

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2
0,Esta casa prohibiría el empotramiento en el periodismo,"Se denomina ""periodistas empotrados"" a aquellos que, en zonas altamente violentas, acompañan con...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ECCQ las comunidades indígenas deberían sabotear los proyectos de infraestructura en su territor...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Esta casa lamenta la fuerte personalización de los movimientos sociales y políticos (LePen en Fr...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"En países con una historia de conflicto, discriminación y/o tensión étnica (por ejemplo: Nigeria...","Un modelo de rotación étnica es aquel en el cual, se turna la presidencia entre grupos étnicos. ...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Esta casa prefiere un mundo donde toda la gente tenga habilidades y características medias (inte...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 7,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8646,THP a human existence void of love,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Open Grand Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8647,"THR the decline of religion's role in emotional healing, in replacement with professional psycho...",NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8648,THS trends of government-imposed regulations pushing full responsibility on producers for waste ...,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8649,"As a feminist, THR the propagation of sexual liberation as a symbol of progress for gender minor...",NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8650,THBT the outcome of a federal election should always reflect the popular vote,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [658]:
len(df['Tournament'].unique()), len(df['Motion'].unique())

(748, 8149)

## Data polishing

In [659]:
df['Motion'] = df['Motion'].astype("string")
df['Motion'] = df["Motion"].str.strip()

### Remove duplicates (motion used in same tournament across different rounds)
in future, better way of handling would be to accumulate/distinguish between these

In [660]:
# check for duplicates on motion and round 
# motions can be duplicated (if same is used in two different rounds)
duplicates = df[df.duplicated(subset=['Motion', 'Tournament'], keep=False)]

if len(duplicates) > 0:
    raise ValueError(f"Found {len(duplicates)} duplicates in the data. This likely means the same motion is used in two different rounds.")

ValueError: Found 703 duplicates in the data. This likely means the same motion is used in two different rounds.

In [661]:
duplicates[['Motion', 'round_1', 'round_2', 'Tournament']]

,Motion,round_1,round_2,Tournament
35,THW marry for utility rather than love and passion,Gold Final,NaN,DK Wien Mini Invitational 2023
36,THW marry for utility rather than love and passion,Silver Final,NaN,DK Wien Mini Invitational 2023
38,ECA que está no interesse de movimentos liberais de oposição em regimes democrático-autoritários...,Pré-Semifinal,NaN,Campeonato Mundial de Debate em Língua Portuguesa 2021
50,ECA que está no interesse de movimentos liberais de oposição em regimes democrático-autoritários...,Pré-Semifinal,NaN,Campeonato Mundial de Debate em Língua Portuguesa 2021
66,THP a world without the institution of marriage.,Quarterfinals,NaN,Netaji Subhas Memorial Parliamentary Debate 2023
...,...,...,...,...
8597,"In developing countries, This House Believes that the provision of public utilities (e.g. electr...",Semifinals,NaN,Asian Online Debating Championship BP 2023
8598,"In developing countries, This House Believes that the provision of public utilities (e.g. electr...",EFL Semifinals,NaN,Asian Online Debating Championship BP 2023
8599,"In developing countries, This House Believes that the provision of public utilities (e.g. electr...",Highschool Semifinals,NaN,Asian Online Debating Championship BP 2023
8644,THW allow police commanders to be criminally liable for instances of police brutality committed ...,Open Semifinals,NaN,World Debate Open 2022
8645,THW allow police commanders to be criminally liable for instances of police brutality committed ...,EFL Semifinals,NaN,World Debate Open 2022

In [662]:
df.drop_duplicates(subset=['Motion', 'Tournament'], keep=False, inplace=True) #FIXME: better to aggregate scores
df

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2
0,Esta casa prohibiría el empotramiento en el periodismo,"Se denomina ""periodistas empotrados"" a aquellos que, en zonas altamente violentas, acompañan con...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ECCQ las comunidades indígenas deberían sabotear los proyectos de infraestructura en su territor...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Esta casa lamenta la fuerte personalización de los movimientos sociales y políticos (LePen en Fr...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"En países con una historia de conflicto, discriminación y/o tensión étnica (por ejemplo: Nigeria...","Un modelo de rotación étnica es aquel en el cual, se turna la presidencia entre grupos étnicos. ...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Esta casa prefiere un mundo donde toda la gente tenga habilidades y características medias (inte...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 7,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8646,THP a human existence void of love,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Open Grand Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8647,"THR the decline of religion's role in emotional healing, in replacement with professional psycho...",NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8648,THS trends of government-imposed regulations pushing full responsibility on producers for waste ...,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8649,"As a feminist, THR the propagation of sexual liberation as a symbol of progress for gender minor...",NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8650,THBT the outcome of a federal election should always reflect the popular vote,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Duplicate motions used across different tournaments

In [663]:
recycled = df[df.duplicated(subset=['Motion'], keep=False)]

In [664]:
df[df['Motion'] == recycled.iloc[0]['Motion']]

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2
51,THBT minority artists should create street art and other art in public spaces rather than art in...,NaN,Netaji Subhas Memorial Parliamentary Debate 2023,NSMPD 2023,https://nsmpd23.calicotab.com/nsmpd23,Round 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000,THBT minority artists should create street art and other art in public spaces rather than art in...,NaN,The Queen Mary IV 2021,QMIV 2021,https://tabtastic.calicotab.com/qmiv2021,Round 1,P,8.0,16.0,40.0,22.0,19.0,15.0,4861.0,14.0,34.0,21.0,7.0,12.0,28.0,4.0,6.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN
3765,THBT minority artists should create street art and other art in public spaces rather than art in...,NaN,The IITB Grand Prix,The IITB Grand Prix,https://iitbgrandprix.calicotab.com/iitb2024,Round 2,P,10.0,16.0,38.0,32.0,7.0,19.0,6093.0,19.0,45.0,9.0,28.0,7.0,11.0,15.0,18.0,46.0,NaN,NaN,NaN,NaN,NaN,NaN

## Basics

### Tournament year

In [665]:
def get_year(tournament: str):
    pattern = re.compile(r'\d{4}')
    match = pattern.search(tournament)

    if tournament == 'eurosdc-25':
        return 2025

    if match:
        return int(match.group(0))
    else:
        return None

df['Year'] = df['Tournament'].apply(get_year)
df.value_counts('Year')

Year
2024.0    1823
2025.0    1683
2023.0    1388
2022.0     910
2021.0     704
          ...
2015.0      54
2019.0      53
2016.0      42
2018.0      26
2014.0      19
Name: count, Length: 11, dtype: int64

### Motion types

In [666]:
full_to_abbr = {
    'BT': "believes",
    'B': "believes",
    "S": "supports",
    "O": "opposes",
    "W": "would",
    "R": "regrets",
    "P": "prefers",
    "PAW": "prefers",
}

all_types = set(full_to_abbr.values()) # *most types (this is used to fix up actor motions)
all_types

{'believes', 'opposes', 'prefers', 'regrets', 'supports', 'would'}

In [667]:
def fix_motions(motion: str):
    australs_pattern = re.compile(r'(A|B|C)\W ') #australs bs that adds A, B, C motion types

    if match := re.match(australs_pattern, motion): 
        motion = motion[match.span()[1]:]
    
    # this fixes actor motions without commas
    # e.g. "This House as the environmental movement would support the use of extremist tactics"
    # https://regex101.com/r/jI2tDT/1
    actor_pattern = re.compile(r"(?:This (h|H)ouse?|TH),?(?P<actor> as( [a-zA-Z']+)+)" + f" ({'|'.join(all_types)})")

    if match := re.search(actor_pattern, motion):
        actor = match.group('actor')
        motion = motion.replace(actor, ',' + actor + ',')

    if motion.startswith('That'):
        motion = 'This House believes that' + motion[4:]
    
    return motion

df['Motion'] = df['Motion'].apply(fix_motions)

In [668]:
def extract_motion_header(motion: str): 
    # https://regex101.com/r/XB1k1w/1
    pattern = re.compile(r"(?:(T|t)his (h|H)ouse?|TH)[ ,]?(?:,.*?, )?(?P<type>\w+)\s?")

    match = re.search(pattern, motion)
    return match

In [669]:
def get_motion_type(motion: str): 
    match = extract_motion_header(motion)

    if match: 
        motion_type = match.group('type')
        all_caps = all(map(str.isupper, motion_type))

        if all_caps:
            return full_to_abbr.get(motion_type, None)
        else: 
            return f'{motion_type.lower()}'
    else:
        return None

df["Motion Type"] = df["Motion"].apply(get_motion_type)

df[df["Motion Type"].isna()] #could not determine motion type / parse motion for these

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2,Year,Motion Type
0,Esta casa prohibiría el empotramiento en el periodismo,"Se denomina ""periodistas empotrados"" a aquellos que, en zonas altamente violentas, acompañan con...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None
1,ECCQ las comunidades indígenas deberían sabotear los proyectos de infraestructura en su territor...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None
2,Esta casa lamenta la fuerte personalización de los movimientos sociales y políticos (LePen en Fr...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None
3,"En países con una historia de conflicto, discriminación y/o tensión étnica (por ejemplo: Nigeria...","Un modelo de rotación étnica es aquel en el cual, se turna la presidencia entre grupos étnicos. ...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None
4,Esta casa prefiere un mundo donde toda la gente tenga habilidades y características medias (inte...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 7,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8407,TH (the European Union) will decline Ukraine's request to become a member of the EU,"Amidst the Russia-Ukraine war, Ukraine applied to become a member of the EU. At present the appl...",The 7th CBS Parliamentary Debate,7th CBS PD,https://cbs.calicotab.com/cbspd23,Round 5,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
8413,TH (Kazakhstan) W pursue the multi-vector approach,Central Asian governments have refused to endorse either the invasion or Russia’s annexation of ...,The 7th CBS Parliamentary Debate,7th CBS PD,https://cbs.calicotab.com/cbspd23,Round 5,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
8444,"TH, would choose to destroy the evidence.","You are an avid progressive. Although you initially supported Bernie, you have rallied your supp...",Ram Manohar Lohiya Parliamentary Debate,RML PD 2023,https://rmlpd2023.calicotab.com/rmlpd2023,Round 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
8531,That we support memory laws,"A: Memory laws are laws governing the interpretation of historical events (e.g., the European Un...",Macquarie | UTS Easters 2023,Easters 2023,https://easters2023.calicotab.com/easters2023,Round 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,None
8589,Reducted,"<font color=""#000000"" face=""Arial""><span style=""font-size: 13.3333px;"">Reducted</span></font>",Heritage Parliamentary Debate 2024,HPD2024,https://hpd.calicotab.com/hpd2024,Semifinals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,None

In [671]:
df = df[df["Motion Type"].notna()]
df

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2,Year,Motion Type
14,THS people adopting an indifferent approach to news,"For the purpose of this debate, the “indifferent approach” means that people can choose to stop ...",Cambridge IV 2023,Cambridge IV 2023,https://cambridgeiv2023.calicotab.com/_,Round 1,P,11.0,21.0,55.0,19.0,23.0,29.0,6717.0,15.0,35.0,14.0,22.0,13.0,27.0,14.0,17.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,supports
15,THS the use of the Ludovico Treatment for violent prisoners,"For the purpose of this debate, the Ludovico Treatment forces people to develop a natural aversi...",Cambridge IV 2023,Cambridge IV 2023,https://cambridgeiv2023.calicotab.com/_,Round 2,P,11.0,24.0,64.0,25.0,27.0,28.0,6799.0,12.0,22.0,16.0,9.0,17.0,43.0,16.0,13.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,supports
16,This House opposes the use of nostalgia* in political campaigning \r\n\r\n(*nostalgia refers to ...,NaN,Cambridge IV 2023,Cambridge IV 2023,https://cambridgeiv2023.calicotab.com/_,Round 3,P,11.0,21.0,51.0,32.0,28.0,15.0,6758.0,18.0,36.0,31.0,9.0,19.0,49.0,6.0,8.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,opposes
17,This House would continue to keep his identity a secret,"You are a journalist who has recently uncovered secret, indisputable evidence that a long-though...",Cambridge IV 2023,Cambridge IV 2023,https://cambridgeiv2023.calicotab.com/_,Round 4,P,11.0,20.0,42.0,48.0,16.0,14.0,6690.0,27.0,71.0,20.0,23.0,10.0,24.0,0.0,9.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,would
18,"THW break up banks* considered ""Too Big to Fail""\r\n\r\n*Such as but NOT limited to Goldman Sach...",NaN,Cambridge IV 2023,Cambridge IV 2023,https://cambridgeiv2023.calicotab.com/_,Round 5,P,11.0,16.0,40.0,16.0,23.0,17.0,6743.0,19.0,49.0,25.0,24.0,16.0,32.0,16.0,15.0,33.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,would
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8646,THP a human existence void of love,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Open Grand Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.0,prefers
8647,"THR the decline of religion's role in emotional healing, in replacement with professional psycho...",NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.0,regrets
8648,THS trends of government-imposed regulations pushing full responsibility on producers for waste ...,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.0,supports
8649,"As a feminist, THR the propagation of sexual liberation as a symbol of progress for gender minor...",NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.0,regrets
8650,THBT the outcome of a federal election should always reflect the popular vote,NaN,World Debate Open 2022,WDO 2022,https://midp.calicotab.com/wdo2022,Round 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2022.0,believes

## Vectorization
NB! This step requires access to a Google Cloud project with billing enabled. If desired, you can sign up for a $300 free trial that will be plenty to cover the costs of vectorization.

Alternatively, all vector space information is already included in the exported file.

### Clean up motions not to clutter with motion types

In [576]:
def clean_motion(motion: str):
    match = extract_motion_header(motion)

    if match is None:
        print(f'[WARN] No header found for motion: {motion}')
        return motion

    header_end = match.span()[1]
    chopped = motion[header_end:].lower()

    filler_words = ['that', 'the', 'it', 'is']

    flag = True
    while flag: 
        flag = False

        for w in filler_words: 
            if chopped.startswith(w): 
                chopped = chopped.replace(w, '')
                flag=True
    
    punctuations = ['.', ',' ';']
    for p in punctuations: 
        chopped = chopped.replace(p, '')
    return chopped

In [578]:
df['Motion (cleaned)'] = df['Motion'].map(clean_motion)
df.head()

[WARN] No header found for motion: Esta casa prohibiría el empotramiento en el periodismo
[WARN] No header found for motion: ECCQ las comunidades indígenas deberían sabotear los proyectos de infraestructura en su territorio que dañan a sus comunidades (por ejemplo: bloqueos de carreteras, destrucción de la infraestructura, etc.)
[WARN] No header found for motion: Esta casa lamenta la fuerte personalización de los movimientos sociales y políticos (LePen en Francia, Justin Trudeau en Canada, Emma Watson en ""He for She"" o Greta Thunberg con el movimiento de juventud por el clima).
[WARN] No header found for motion: En países con una historia de conflicto, discriminación y/o tensión étnica (por ejemplo: Nigeria, India, Myanmar, Irak). Esta casa instauraría modelos de rotación étnica
[WARN] No header found for motion: Esta casa prefiere un mundo donde toda la gente tenga habilidades y características medias (inteligencia medio, belleza media...) a uno en el que exista disparidad
[WARN] No header found for motion: Esta casa cree que los estados deberían crear empresas farmacéuticas públicas
[WARN] No header found for motion: Esta casa lamenta la narrativa de que el trabajo es la mejor forma de  empoderar a grupos vulnerables (por ejemplo: personas en situación de pobreza, exconvictos, personas con adicciones, etc)
[WARN] No header found for motion: En contextos de recesión económica, con inflación baja o negativa y crisis de demanda, esta casa cree que es mejor que los bancos centrales inyecten liquidez directamente en los ciudadanos de a pie, en vez de realizar políticas de expansión cuantitativa.
[WARN] No header found for motion: Esta casa haría legalmente responsable a las instituciones religiosas por los perjuicios sufridos por sus fieles a causa de sus "creencias religiosas potencialmente perjudiciales"
[WARN] No header found for motion: Esta casa cree que los partidos de izquierda deberían centrar principalmente sus propuestas electorales en medidas económicas y de clase en vez de en aquellas enfocadas a identidades sociales (por ejemplo, reducción de impuestos a clases bajas en vez de mayor emancipación de la mujer o visibilidad LGBT)
[WARN] No header found for motion: Esta casa cree que la Asamblea General de la ONU debería reconocer como estados independientes a los campos de refugiados cuya existencia se alargue por encima de 25 años
[WARN] No header found for motion: Esta casa prefiere una sociedad que enfatiza el colectivismo por encima del individualismo
[WARN] No header found for motion: EC prefiere un mundo en el que todo el trabajo pudiera ser hecho efectivamente y a un costo asequible por robots
[WARN] No header found for motion: Esta casa destruiría el estudio
[WARN] No header found for motion: Ao se relacionar com a China, EC, como a Administração Biden, focaria na abordagem de direitos humanos em detrimento da abordagem econômica
[WARN] No header found for motion: EC prefere um mundo baseado na narrativa "lying flat" em oposição a um mundo baseado na narrativa de produtividade
[WARN] No header found for motion: ECL a dominância da narrativa do "Ocidente Mau" nos círculos acadêmicos
[WARN] No header found for motion: ECAQ a UE deveria ter optado por políticas de alívio de dívidas (ex. renegociação de prazo ou taxa de juros) dos Estados Membro em vez da emissão de "Coronabonds"
[WARN] No header found for motion: ECAQ movimentos LGBTQ+, em nações progressistas, deveriam focar suas campanhas em valores familiares em vez de liberalização sexual
[WARN] No header found for motion: Assumindo a possibilidade tecnológica de deepfake para tal, EC dá as boas vindas à recriação digital de grandes artistas falecidos*

*Por exemplo, James Dean que morreu 70 anos atrás sendo escalado para um novo filme ou o holograma de Tupac Shakur performando em shows de rap.
[WARN] No header found for motion: EC apoia a existência de instituições com o poder de banir ações e discursos políticos anti-democráticos
[WARN] No header found for motion: EC repudia a noção de que os filhos têm uma dívida para com os pais
[WARN] No header found for motion: EC optaria pelo sistema de saúde de Seguro Social em detrimento do Universalista em países desenvolvidos
[WARN] No header found for motion: ECAQ movimentos sociais deveriam enfatizar a capacidade do indivíduo de alterar a própria realidade diante da opressão em detrimento de enfatizar estruturas que restringem e determinam a vida de um indivíduo
[WARN] No header found for motion: Em bairros enclaves islâmicos, ECAQ a França deveria financiar escolas públicas com interpretações progressistas do islã em detrimento de escolas públicas laicas.
[WARN] No header found for motion: EC prefere um mundo em que a noção de felicidade está desatrelada da busca por um propósito de vida
[WARN] No header found for motion: TH, as the opposition in the parliament would push for occassions otherwise popular across other regions to be introduced as gazetted holidays.
[WARN] No header found for motion: TH, as Emmanuel Macron's government would shift to Policy A over Policy B.
[WARN] No header found for motion: TH, as the Indian government Will mandate mixed housing.
[WARN] No header found for motion: H as the feminist movement in India would reclaim various traditional practices under the umbrella of "choice feminism".
[WARN] No header found for motion: [Redacted]
[WARN] No header found for motion: TH, in a zombie apocalypse W choose to join the authoritarian society over the democracy.
[WARN] No header found for motion: EC estabeleceria um teto de gastos e salários no futebol profissional
[WARN] No header found for motion: EC se casaria por utilidade ao invés de por amor ou paixão
[WARN] No header found for motion: Em grandes centros urbanos, EC proibiria o mercado não-hoteleiro de hospedagens de curto prazo (ex: Airbnb, VRBO, HomeAway)
[WARN] No header found for motion: EC privatizaria a Empresa Brasil de Comunicação (EBC)
[WARN] No header found for motion: EC acredita que a Ucrânia deveria buscar o apoio de empresas militares privadas na guerra contra a Rússia
[WARN] No header found for motion: EC prefere viver num mundo em que o conceito de divindade não exista
[WARN] No header found for motion: EC prefere um mundo sem o desejo por vingança
[WARN] No header found for motion: Esta Casa apoia a entrada dos novos países* no BRICS
[WARN] No header found for motion: EC considera legítimo o uso de fatos da vida pessoal do adversário político no debate público
[WARN] No header found for motion: Thw support Human Challenge Trials being used to advance medical research.
[WARN] No header found for motion: Thr the decision of the NBA players to resume the season
[WARN] No header found for motion: TH, as an average Kurdish individual,
Opposes Öcalan's Statement.
[WARN] No header found for motion: TH, as the Government of a newly decolonised country would seek to appease rather than oppose their former colonial rulers.
[WARN] No header found for motion: EC investigaría desde el enfoque de las causas en lugar de las consecuencias.
[WARN] No header found for motion: EC dividiría Penguin Random House en sellos editoriales.
[WARN] No header found for motion: EC prefiere un mundo donde la concepción dominante sobre el derecho sea la principialista sobre la contextual.
[WARN] No header found for motion: EC implementaría la pedagogía post radical en el sistema educativo tradicional.
[WARN] No header found for motion: EC se opone a la Línea de Crédito Flexible del FMI
[WARN] No header found for motion: ECCQ los partidos políticos de izquierdas deberían priorizar las políticas universalistas por sobre las progresivas.
[WARN] No header found for motion: ECCQ República Dominicana debería acelerar sus políticas de transición energética.
[WARN] No header found for motion: EC prefiere la ética zoroastrista en lugar de la ética taoísta
[WARN] No header found for motion: EC, siendo el movimiento LGBTIAQ+ en los países del norte global, priorizaría un activismo basado en la "denuncia como resistencia" por encima del "placer como resistencia".
[WARN] No header found for motion: EC prefiere que la crítica artística se rija predominantemente por el CAMP en lugar del AURA
[WARN] No header found for motion: ECCQ el Gobierno Federal de Etiopía debería delegar la gestión de los conflictos con milicias étnicas a las policías regionales
[WARN] No header found for motion: EC, siendo un unicornio tecnológico en expansión, priorizaría financiarse con prestamistas directos en lugar de empresas de capital de inversión
[WARN] No header found for motion: EC, como una persona Otaku (オタク), reorientaría su vida hacia el concepto de Ikigai (生き甲斐)
[WARN] No header found for motion: TH, as an intelligent student from a low income family would pursue vocational training over a traditional college degree.
[WARN] No header found for motion: TH (as an emerging Democrat) Prefers Hamilton's outlook to Burr's
[WARN] No header found for motion: Th, as the President of the United States, would order CIA's Head of Station in Moscow to press the button
[WARN] No header found for motion: Thbt that states with aging populations should pursue policies which redistribute wealth aggressively to the young (i.e. taxes on assets, reducing subsidies for healthcare, increased retirement ages, and reduced pension allowances)
[WARN] No header found for motion: TBHT education systems should heavily prioritise the teaching of local literature over the global canon
[WARN] No header found for motion: TH, as Ayan would confess his love for Alizeh regardless of the outcome.
[WARN] No header found for motion: TH (as a low income parent in India) W raise their child to believe in determinism over free will
[WARN] No header found for motion: TH (as China) W invade Taiwan
[WARN] No header found for motion: TBHT all wealth beyond the necessary to meet one's basic needs is immoral
[WARN] No header found for motion: TH(As Bhim Army) W
gradually shift towards Dalit Panther’s approach for combatting caste-based discrimination
[WARN] No header found for motion: In countries where men are conscripted to serve in the military, TBHT the feminist movement should advocate for the conscription of women as well
[WARN] No header found for motion: Th(Shark Tank) W not call Ashneer Grover for S2
[WARN] No header found for motion: TH (Feminist Movement) W oppose the trope of 'femme fatale' being empowering
[WARN] No header found for motion: TH (Female Wrestlers) W not go to Saudi Arabia
[WARN] No header found for motion: TH(US Senate)W pass the Antitrust bill
[WARN] No header found for motion: TH(Western Liberal Democracies)W
implement the Protocol
[WARN] No header found for motion: Time set: 12th Feb 2022
TH(NATO)W concede to Russia's demands
[WARN] No header found for motion: Assuming the candidate has already been
decided, TH(INC) W release the name of the INC
candidate before the elections"
[WARN] No header found for motion: TH(Left) W oppose the release of "Why I killed Gandhi"
[WARN] No header found for motion: TH(Jayant Chowdhary)W accept BJPs post poll alliance offer
[WARN] No header found for motion: TH, as an average individual would opt into the artificial afterlife
[WARN] No header found for motion: EC prefiere un mundo donde se espere que todas las relaciones amistosas y románticas sean temporales
[WARN] No header found for motion: EC administraría conjuntamente los recursos naturales a través de las Naciones Unidas en lugar de que cada país administre los propios de manera autónoma. (Ejemplos: La ONU gestionando el Amazonas, el Lago Victoria,  los Glaciares del Himalaya, yacimientos petrolíferos transfronterizos, etc.)
[WARN] No header found for motion: EC lamenta que las empresas privadas financien a las instituciones públicas de educación superior.
[WARN] No header found for motion: ECCQ les xadres deben desalentar a sus hijes a que practiquen el "cambio de código"
[WARN] No header found for motion: ECCQ las empresas pequeñas y medianas deberían usar a Amazon para distribuir sus productos.
[WARN] No header found for motion: ECCQ La justicia ambiental debería convertirse en un objetivo central del movimiento feminista (por ejemplo: apoyando el ecofeminismo, difundiendo la narrativa de que las mujeres son parte de la naturaleza en su conjunto, luchando contra la contaminación del agua y el aire etc.)
[WARN] No header found for motion: EC incentivaría a los medios (series, películas, publicidad) a representar a las personas estereotípicamente felices como introvertidas, reservadas y solitarias.
[WARN] No header found for motion: EC, como artista, preferiría representar el mundo de la forma en que le gustaría que fuese, en lugar de representarlo como lo ve.
[WARN] No header found for motion: ECCQ la OMC debería permitir a los países en desarrollo proteger ciertas industrias y excluirlas del libre comercio.
[WARN] No header found for motion: Suponiendo que fuera factible, EC preferiría una coalición en torno a los valores democráticos que no tuvieran en cuenta divisiones ideológicas (por ejemplo una coalición de izquierda y derecha) para ir en contra del gobierno Bolsonaro.
[WARN] No header found for motion: EC lamenta la narrativa imperante en religiones monoteístas de que si te arrepientes de tus actos en tu lecho de muerte tendrás el perdón y la salvación
[WARN] No header found for motion: ECCQ, en países con problemas endémicos de corrupción, les fiscales respetuoses de la ley deben utilizar tácticas ilegales para lograr una condena (por ejemplo: falsificar pruebas, obtener pruebas de forma ilícita, sobornar a les juezes, etc.)
[WARN] No header found for motion: EC lamenta los esfuerzos para encontrar la inmortalidad
[WARN] No header found for motion: TH, as person X would choose to stay in our home country
[WARN] No header found for motion: EC prefere nutrir relações com indivíduos que possuam características similares em detrimento de alguém com características opostas
[WARN] No header found for motion: EC lamenta o niilismo político
[WARN] No header found for motion: ECL a influência de instituições internacionais (e.g.: FIFA, OCDE, OPEC, Multinacionais, FMI etc) na política interna dos países
[WARN] No header found for motion: EC, enquanto Rodrigo Pacheco, apoiaria o pedido de impeachment do Min. Alexandre de Moraes
[WARN] No header found for motion: ECAQ heranças* são ilegítimas
*Para fins desse debate, as heranças são materiais (dinheiro, bens, ações etc)
[WARN] No header found for motion: Em sociedades pós-conflito, EC ativamente suprimiria informações e interpretações que retratem qualquer ditador ou regime tirânico do passado de maneira simpática.
[WARN] No header found for motion: EC prevê que o século XXI será o século do declínio do Ocidente.
[WARN] No header found for motion: EC prefere uma sociedade em que prevalece a ideia espírita de reencarnação, em detrimento de uma noção de juízo final.
[WARN] No header found for motion: Em um contexto de ditadura e limitação de liberdade de expressão, ECAQ é legitimo o uso de notícias falsas por movimentos de oposição a esses regimes.
[WARN] No header found for motion: Assuming God is the creator of all life, TH (as God) will erase humanity and restart life again
[WARN] No header found for motion: Thbt the feminist movement should actively disavow body positivity in favour of body neutrality.
[WARN] No header found for motion: ΤΗΒΤ Latin America should pursue strong economic and trade ties with Asia, even at the expense of their relations with the West.
[WARN] No header found for motion: TBHT MULTIRACIAL DEMOCRACIES SHOULD REFORM ITS CURRENT PARLIAMENTARY DEMOCRACY TO A RANKED-CHOICE PRESIDENTIAL ELECTION
[WARN] No header found for motion: TH (as India) W aggressively pursue the
 development of the SEZ model.
[WARN] No header found for motion: EC apoya la inclusión significativa del nihilismo en contenidos infantiles (p.e. en libros, en series de televisión como Billy y Mandy, Igor en Winnie Pooh, Hakuna Matata y en material educativo).
[WARN] No header found for motion: EC aboliría la PAC
[WARN] No header found for motion: EC lamenta el voto de cenura (no-confidence vote) contra Michel Barnier.
[WARN] No header found for motion: ECCQ las ONGs deberían rechazar donaciones provenientes de organizaciones y empresarios con comportamientos poco éticos.
[WARN] No header found for motion: EC, recién finalizado el genocidio de Ruanda, repatriaría a los refugiados Hutus al territorio de Ruanda.
[WARN] No header found for motion: EC prohibiría el juego/apuestas.
[WARN] No header found for motion: ECCQ está en el interés del PCC (Partido Comunista Chino) la victoria de Trump.
[WARN] No header found for motion: En la resolución de conflictos entre pueblos originarios y empresas, EC preferiría optar por el arbitraje en lugar del proceso judicial
[WARN] No header found for motion: EC implementaría el modelo de reclutamiento legionario
[WARN] No header found for motion: ECCQ Chile debería adoptar fuertes medidas de desregulación financiera
[WARN] No header found for motion: TH, as a person in their early 20s entering a new relationship W use LoveOracle
[WARN] No header found for motion: TH, as lower middle class immigrant parents W,raise their child to believe free will does not exist
[WARN] No header found for motion: TH (as ICC) will acquit Eichmann
[WARN] No header found for motion: TH (as FIDE) will switch the WCC format to Chess 960.
[WARN] No header found for motion: TH (as Durant) W not join the Golden State Warriors (GSW).
[WARN] No header found for motion: TH (Alan Turing) W not crack the Enigma.
[WARN] No header found for motion: TH (as EU) will ask USA to abandon Ukraine.
[WARN] No header found for motion: presuming it were possible, That we would opt for a digital existence over a physical one
[WARN] No header found for motion: presuming feasibility, That we should allow individuals to selectively erase others' memories of them
[WARN] No header found for motion: in a world where it exists, That love with artificial intelligence is as valid as love with a human
[WARN] No header found for motion: in the face of an overwhelming failure of conventional responses by nation-states, That churches should encourage and materially support able members of their congregation to go and fight against ISIS
[WARN] No header found for motion: Where conflicts have disproportionately harmed women, That post-conflict states should exclusively appoint women to positions of leadership in the military
[WARN] No header found for motion: On July 13th 2024, Donald Trump was shot nonfatally by an assassin at a campaign rally.
[WARN] No header found for motion: --
[WARN] No header found for motion: EC apoya la flexibilización del Mercosur
[WARN] No header found for motion: ECCQ el gobierno de Colombia debería redistribuir masivamente la tierra a las comunidades indígenas
[WARN] No header found for motion: EC prefiere un mundo en el que la mayoría de las personas crean en la noción colectiva del arte
[WARN] No header found for motion: ECCQ está en el interés de la ACLU abandonar la defensa del discurso de odio
[WARN] No header found for motion: EC apoya la implementación de un salario mínimo universal en Italia
[WARN] No header found for motion: ECCQ los movimientos feministas deberían adoptar el modelo de nuevas masculinidades en lugar del modelo separatista
[WARN] No header found for motion: EC prefiere que las comisiones de verdad prioricen el modelo conciliador en lugar del modelo de justicia.
[WARN] No header found for motion: EC lamenta la financiarización del sector agrario
[WARN] No header found for motion: EC como la persona joven activista latinoamericana, elegiría el activismo por sobre la política
[WARN] No header found for motion: EC apoya las reformas de Keir Starmer al Partido Laborista
[WARN] No header found for motion: ECCQ la República Democrática del Congo debería permitir la propuesta de apoyo militar de la Unión Africana

,Motion,Info Slide,Tournament,short_name,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,cg_wins,co_wins,og_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned)
0,Esta casa prohibiría el empotramiento en el periodismo,"Se denomina ""periodistas empotrados"" a aquellos que, en zonas altamente violentas, acompañan con...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 2,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None,Esta casa prohibiría el empotramiento en el periodismo
1,ECCQ las comunidades indígenas deberían sabotear los proyectos de infraestructura en su territor...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 1,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None,ECCQ las comunidades indígenas deberían sabotear los proyectos de infraestructura en su territor...
2,Esta casa lamenta la fuerte personalización de los movimientos sociales y políticos (LePen en Fr...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 3,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None,Esta casa lamenta la fuerte personalización de los movimientos sociales y políticos (LePen en Fr...
3,"En países con una historia de conflicto, discriminación y/o tensión étnica (por ejemplo: Nigeria...","Un modelo de rotación étnica es aquel en el cual, se turna la presidencia entre grupos étnicos. ...",CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 4,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None,"En países con una historia de conflicto, discriminación y/o tensión étnica (por ejemplo: Nigeria..."
4,Esta casa prefiere un mundo donde toda la gente tenga habilidades y características medias (inte...,NaN,CMUDE 2019,cmude2019,https://cmude2019.calicotab.com/cmude2019,Ronda 7,P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019.0,None,Esta casa prefiere un mundo donde toda la gente tenga habilidades y características medias (inte...

In [579]:
import vertexai
import os

vertexai.init(project=os.environ['VERTEXAI_PROJECT_ID'])

from vertexai.language_models import TextEmbeddingModel
from typing import Optional

def embed(texts, output_dims: Optional[int] = None):
  model_id = 'text-embedding-005'
  model = TextEmbeddingModel.from_pretrained(model_id)
  embeddings = model.get_embeddings(texts, output_dimensionality=output_dims)

  return embeddings

In [272]:
# vertexai allows a max of 250 input elements at once
chunk_size = 100

for start in tqdm(range(0, len(df), chunk_size)):
    end = start + chunk_size
    motion_strings = df['Motion (cleaned)'].values[start:end]

    embeddings = embed(list(motion_strings))
    df.loc[start:end-1, 'Embedding'] = embeddings #NB! pandas uses an inclusive end index (hence the end-1)

#TODO: maybe better to store each value in its own column? or just use a diff file format specifically for floats
from vertexai.language_models import TextEmbedding
df['Embedding'] = df['Embedding'].map(lambda e: e.values if isinstance(e, TextEmbedding) else None) #get only the numbers

df.head()

100%|██████████| 11/11 [00:30<00:00,  2.81s/it]

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding
0,This House believes that the South Korean government should redirect resources currently used to...,"Koryo-in (고려인) are Korean diasporas residing in post-Soviet countries, mainly\nin Central Asia. ...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,the south korean government should redirect resources currently used to help koryo-in settle in...,"[0.04669427126646042, -0.041124969720840454, 0.0035075603518635035, 0.0260517168790102, 0.031686..."
1,This House believes that we oppose Australia's 501 policy.,"Australia's 501 policy refers to section 501 of the Migration Act 1958, which\ndeals with the ca...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose australia's 501 policy,"[-0.033344559371471405, -0.02679823897778988, 0.014931241050362587, -0.03771759942173958, 0.0110..."
2,This House believes that we oppose countries adopting ‘pull-back’ measures to respond to the inf...,Irregular migrants are those who enter another country without official\npermission. In response...,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants,"[0.00870150700211525, -0.06843803077936172, -0.003463117405772209, 0.025157984346151352, 0.01750..."
3,"This House believes that we regret self-denial in religion (e.g. celibacy, fasting, giving up ma...",NaN,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"we regret self-denial in religion (eg celibacy, fasting, giving up material or sensory pleasures)","[-0.03781802952289581, 0.033481165766716, 0.05631212145090103, -0.04665393754839897, 0.030571291..."
4,"This House believes that, in multireligious states, schools should teach integrated religious ed...","In ‘integrated religious education’, all students are taught material\nencompassing many major r...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,", in multireligious states, schools should teach integrated religious education instead of separ...","[-0.07520031929016113, -0.03346019983291626, 0.06300149857997894, -0.013544010929763317, 0.00563..."

### Checkpoint: Save data locally

In [273]:
data_dir = 'raw'

In [274]:
os.makedirs(data_dir, exist_ok=True)
df.to_csv(os.path.join(data_dir, 'motions_bp_with_embeddings.csv'), index=False)

In [275]:
import json 

df = pd.read_csv(os.path.join(data_dir, 'motions_bp_with_embeddings.csv'))
df['Embedding'] = df['Embedding'].apply(lambda x: json.loads(x))

## Motion counts

In [276]:
by_year = df.groupby('Year')
year_counts = by_year['Motion'].count()

In [277]:
px.line(year_counts)

## Motion types

### All-time motion types

In [278]:
year_counts = df.value_counts('Motion Type')
print(year_counts)

px.bar(
    year_counts, 
    y='count', 
    title='All-time Motion Types',
    labels={'Motion Type': 'Motion Type'},
    height=600,
    width=1000
).show()

Motion Type
believes    637
would       171
prefers      82
           ...
hopes         2
predicts      2
welcomes      1
Name: count, Length: 9, dtype: int64

### This year's motion types

In [279]:
current_year = datetime.now().year

df_this_year = df[df['Year'] == current_year]
df_this_year.tail()

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding
651,This House Opposes the increased shift to subscription based business models,Companies are increasingly adopting subscription models for selling their\nphysical and digital ...,Panama World Universities Debating Championships 2025,https://wudc2025.calicotab.com/open,ESL Semi Finals,E,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,2025.0,opposes,increased shift to subscription based business models,"[-0.004157711751759052, -0.04387740045785904, 0.014440606348216534, -0.008247307501733303, 0.040..."
652,This House Would militarily intervene in Sudan,NaN,Panama World Universities Debating Championships 2025,https://wudc2025.calicotab.com/open,Semi Finals,E,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,NaN,2025.0,would,militarily intervene in sudan,"[0.0015502679161727428, -0.047926560044288635, -0.04136025160551071, -0.00388136925175786, -0.00..."
653,This House Believes That Trumpism is in the long-term interest of the Republican Party,"Trumpism is a populist ideology and style of politics that combines elements\nof nationalism, an...",Panama World Universities Debating Championships 2025,https://wudc2025.calicotab.com/open,EFL Grand Final,E,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2025.0,believes,trumpism is in the long-term interest of the republican party,"[-0.07597186416387558, -0.026646390557289124, 0.02228401042521, 0.015662826597690582, 0.01518684..."
654,"This House, as the Holy See, would adopt the ""two-speed Church"" policy",The Holy See is the central governing body of the Catholic Church (including\nthe Pope). \n \n...,Panama World Universities Debating Championships 2025,https://wudc2025.calicotab.com/open,ESL Grand Final,E,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,2025.0,would,"adopt the ""two-speed church"" policy","[-0.051644157618284225, -0.0018404759466648102, 0.025723902508616447, 0.019065221771597862, 0.00..."
655,This House Supports the shift away from the traditional left-right spectrum in the politics of m...,NaN,Panama World Universities Debating Championships 2025,https://wudc2025.calicotab.com/open,Grand Final,E,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,2025.0,supports,shift away from traditional left-right spectrum in politics of major democracies,"[0.004278264474123716, -0.02921971306204796, 0.055171720683574677, 0.001925002783536911, 0.02778..."

In [280]:
year_counts = df_this_year.value_counts('Motion Type')

px.bar(
    year_counts, 
    y='count', 
    title=f'Motion Types for {current_year}',
    labels={'Motion Type': 'Motion Type'},
    height=600,
    width=1000
).show()

### Motion types for earliest year

In [281]:
earliest_year = df['Year'].min()
df_earliest_year = df[(df['Year'] == earliest_year)]

In [282]:
year_counts = df_earliest_year.value_counts('Motion Type')

px.bar(
    year_counts, 
    y='count', 
    title=f'Motion Types for {int(earliest_year)}',
    labels={'Motion Type': 'Motion Type'},
    height=600,
    width=1000
).show()

## Semantic analysis

In [283]:
%pip install -q scikit-learn

Note: you may need to restart the kernel to use updated packages.

In [284]:
df.head()

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding
0,This House believes that the South Korean government should redirect resources currently used to...,"Koryo-in (고려인) are Korean diasporas residing in post-Soviet countries, mainly\nin Central Asia. ...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,the south korean government should redirect resources currently used to help koryo-in settle in...,"[0.04669427126646042, -0.041124969720840454, 0.0035075603518635035, 0.0260517168790102, 0.031686..."
1,This House believes that we oppose Australia's 501 policy.,"Australia's 501 policy refers to section 501 of the Migration Act 1958, which\ndeals with the ca...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose australia's 501 policy,"[-0.033344559371471405, -0.02679823897778988, 0.014931241050362587, -0.03771759942173958, 0.0110..."
2,This House believes that we oppose countries adopting ‘pull-back’ measures to respond to the inf...,Irregular migrants are those who enter another country without official\npermission. In response...,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants,"[0.00870150700211525, -0.06843803077936172, -0.003463117405772209, 0.025157984346151352, 0.01750..."
3,"This House believes that we regret self-denial in religion (e.g. celibacy, fasting, giving up ma...",NaN,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"we regret self-denial in religion (eg celibacy, fasting, giving up material or sensory pleasures)","[-0.03781802952289581, 0.033481165766716, 0.05631212145090103, -0.04665393754839897, 0.030571291..."
4,"This House believes that, in multireligious states, schools should teach integrated religious ed...","In ‘integrated religious education’, all students are taught material\nencompassing many major r...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,", in multireligious states, schools should teach integrated religious education instead of separ...","[-0.07520031929016113, -0.03346019983291626, 0.06300149857997894, -0.013544010929763317, 0.00563..."

In [285]:
# spread embeddings across multiple columns

df_embeddings = pd.DataFrame(df['Embedding'].to_list())
df_embeddings.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,418,419,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,450,451,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,482,483,484,485,486,487,488,489,490,491,492,493,494,495,496,497,498,499,500,501,502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,546,547,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,578,579,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,610,611,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,642,643,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,674,675,676,677,678,679,680,681,682,683,684,685,686,687,688,689,690,691,692,693,694,695,696,697,698,699,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,720,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,739,740,741,742,743,744,745,746,747,748,749,750,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767
0,0.046694,-0.041125,0.003508,0.026052,0.031686,0.033562,-0.009249,-0.006062,-0.028621,0.008644,0.039939,-0.037726,-0.011121,-0.005692,-0.019954,-0.025353,0.057021,-0.035762,-0.018242,0.008832,0.039862,-0.004182,0.058362,0.026759,0.005156,-0.045800,-0.022359,0.029002,-0.023129,-0.011232,0.020176,-0.027394,0.018938,-0.099196,-0.027543,0.001622,-0.025254,-0.027498,0.056550,-0.000821,0.057827,0.013686,-0.039846,0.014219,0.035766,-0.019864,0.019870,0.043749,-0.036258,-0.054908,0.053059,-0.054393,0.027459,-0.024115,-0.022839,-0.001879,-0.006121,0.042798,-0.012427,0.023106,0.005949,-0.001739,0.064806,-0.016471,-0.007655,0.015588,0.045019,-0.000399,-0.025310,0.007292,0.015379,-0.058049,0.070324,-0.038533,0.003318,0.032971,0.066686,0.040921,0.001325,-0.032993,0.004795,-0.011691,-0.035173,-0.011562,0.013435,-0.034369,-0.083864,0.017199,-0.005637,-0.004097,0.006273,0.052737,0.002075,-0.018995,0.049240,0.080468,0.044541,0.032655,-0.068362,-0.017110,0.021411,-0.030333,-0.066768,-0.044045,-0.036726,-0.010313,-0.056484,-0.033504,0.064368,-0.050382,-0.007715,0.066425,-0.052202,-0.009157,-0.015374,-0.021112,0.003235,0.016387,-0.023364,-0.005314,-0.056632,0.044662,-0.014064,-0.062489,0.029347,0.056995,0.017486,0.007403,-0.019009,-0.046503,0.047296,-0.062078,0.036958,0.006758,-0.031782,-0.029038,-0.048103,0.016783,0.026648,0.038283,-0.017540,-0.045727,-0.026295,0.038602,-0.037500,0.036926,-0.040379,0.000223,0.061020,0.060574,-0.043993,0.029751,-0.071433,-0.011673,0.021759,0.059817,0.052474,-0.063756,-0.004066,0.031679,0.039045,-0.006231,-0.044885,-0.014168,-0.018218,0.082986,0.060410,-0.004844,-0.034129,-0.064261,-0.000926,-0.052817,-0.013447,0.081681,0.010607,-0.003976,-0.017710,-0.069236,0.037674,0.009416,-0.017992,-0.010752,-0.028473,-0.024392,-0.117222,0.023353,-0.012350,-0.027835,-0.062531,-0.030740,0.000070,-0.011026,-0.018128,0.054706,-0.024243,0.043478,-0.005703,-0.013167,-0.021185,-0.026592,-0.036375,0.080319,0.014663,0.019498,-0.005362,0.033936,-0.008416,0.031023,-0.024840,-0.013150,0.041294,-0.007407,-0.093640,-0.021208,-0.036689,-0.137486,-0.077121,0.062865,0.067476,-0.015470,0.029171,0.048785,-0.099562,0.004518,-0.029753,0.020808,0.020620,-0.028134,0.052436,-0.051035,0.007132,0.020709,-0.012590,0.048239,-0.020609,0.067516,-0.008189,0.026613,-0.037454,-0.048774,0.001918,0.026216,0.040795,-0.040132,0.014320,0.016934,-0.063503,0.066279,-0.114307,0.001196,-0.011892,-0.022963,0.029649,-0.006784,0.017946,-0.049154,0.011625,-0.055448,-0.017928,0.048775,0.026903,0.036566,0.017812,0.023622,0.030245,-0.021521,-0.051433,-0.017391,-0.018962,0.074908,0.019533,0.024270,-0.068150,-0.008181,-0.028028,0.033685,-0.038999,-0.005560,0.025806,-0.006629,-0.013572,-0.020809,0.068336,0.079617,0.019189,-0.005529,0.005606,0.007824,-0.036252,-0.013459,0.017931,0.002318,0.071204,-0.071825,-0.000290,0.035913,0.047562,0.032201,0.028495,-0.037578,-0.011670,0.003432,0.003796,0.044023,0.060011,-0.012564,-0.032578,-0.031466,-0.022527,0.018524,-0.024046,-0.052265,0.057793,-0.011009,-0.005211,-0.010446,-0.063795,0.006860,0.034448,-0.071827,-0.021011,-0.003290,0.067318,0.011101,-0.026272,0.020512,0.034974,-0.000637,-0.026036,0.001171,-0.039942,0.042499,-0.024781,0.011544,-0.024397,-0.044311,0.017785,0.007382,0.027163,0.034071,0.015681,0.017295,-0.042317,0.012099,-0.036522,-0.001700,-0.057401,-0.023999,0.002008,-0.000184,0.015311,0.020655,-0.005119,-0.067769,-0.008019,-0.001627,-0.016684,0.036950,-0.023560,0.024998,0.019119,-0.005206,-0.007407,0.004634,-0.040565,-0.024433,-0.016961,-0.049480,0.021360,0.007562,-0.024860,0.032755,0.008122,-0.019154,0.022287,-0.074992,-0.016430,0.021434,0.014996,-0.078769,-0.027610,-0.054474,-0.012812,0.014573,-0.010236,0.004079,0.020281,-0.026278,0.033321,-0.024146,-0.016650,0.073075,-0.020788,0.003658,0.007497,-0.024258,-0.029315,0.093561,-0.012270,0.004881,-0.002599,-0.043472,-0.027182,-0.029303,-0.027607,-0.039867,0.010298,0.046727,0.017288,0.021596,0.000791,-0.055344,0.020404,0.042734,-0.005779,-0.091788,0.007777,0.043528,0.062269,0.008096,-0.002244,-0.044141,0.041841,0.052992,-0.015172,-0.066145,0.003991,0.036197,0.040153,0.044307,-0.036383,0.002981,0.006429,-0.058253,0.001194,-0.032165,0.056208,-0.029859,-0.009331,0.053697,0.015078,0.026955,0.033518,-0.033820,-0.036723,-0.031784,0.029293,0.031246,-0.000076,0.007311,0.029985,0.016261,0.007178,-0.007178,-0.018113,-0.030060,0.035310,0.006210,0.021389,-0.063884,-0.038884,0.010486,0.024821,0.021358,0.057555,0.037110,-0.033042,0.002913,0.018830,-0.036459,-0.004018,-0.039536,-0.052564,0.025168,-0.034748,-0.008765,-0.002416,0.004760,0.012921,0.015840,0.007882,0.004203,0.044468,0.005588,-0.025755,0.004175,-0.057978,-0.053585,-0.021460,0.006592,-0.087206,0.010196,-0.008731,-0.007792,0.021137,0.012915,-0.009473,0.024258,-0.028488,-0.055289,-0.035694,-0.028396,-0.010312,-0.020800,-0.023344,-0.006232,-0.079427,-0.010966,0.035443,0.046714,-0.001626,-0.029927,-0.056732,-0.043006,-0.013850,0.019170,0.018658,-0.021193,-0.004185,-0.035742,0.035132,-0.046407,0.051535,0.004970,-0.028582,-0.038911,-0.024026,0.004699,-0.018745,0.008422,0.004239,-0.030381,0.006503,-0.014310,0.000574,-0.015870,-0.017068,0.000334,-0.052605,-0.020144,0.023100,0.042331,-0.023895,-0.025229,0.048292,-0.023066,0.018889,-0.027742,-0.034416,0.063482,0.006580,0.052921,0.028171,-0.050641,-0.027579,0.004098,-0.018672,-0.042785,0.015353,-0.018140,0.053579,-0.000482,0.044271,-0.050712,-0.011806,-0.027451,-0.026145,0.032096,-0.015709,-0.007885,0.034200,0.012725,0.038124,0.039065,0.014960,-0.024284,-0.039561,0.021775,0.026513,-0.025592,0.045266,0.022804,-0.000788,0.024311,-0.023793,0.007272,-0.027083,-0.041043,-0.013244,-0.042104,-0.016261,0.003689,0.000282,0.002641,-0.003086,-0.024734,-0.052099,0.034092,0.047405,-0.052461,-0.011210,0.063576,-0.037139,-0.001781,-0.006798,0.068874,0.007667,-0.035940,0.021748,-0.019739,0.037706,0.023893,-0.032730,-0.007650,-0.016137,0.016335,0.030056,0.005667,-0.064564,0.069398,0.027684,-0.071945,-0.074400,-0.049672,0.016944,-0.004974,-0.026547,-0.014948,-0.014131,-0.008270,-0.011214,0.064688,-0.068227,-0.014231,-0.002670,0.031962,-0.010236,-0.030766,0.004140,0.016309,-0.031805,-0.067825,0.013020,-0.025705,0.011776,-0.015520,0.042961,-0.006938,0.026731,0.008605,0.046489,-0.024861,-0.057447,0.064413,0.009942,0.092917,0.028329,0.091608,0.030838,-0.003660,0.009293,-0.002669,0.028623,0.011448,0.040834,-0.054508,-0.061037,-0.002885,-0.061626,-0.033644,-0.062194,-0.010517,0.007160,-0.000053,-0.034417,0.029316,0.009568,-0.024602,-0.000273,0.036784,0.027267,-0.021426,-0.019991,-0.014056,-0.077893,-0.017172,0.013012,0.010844,0.025257,0.015014,0.000568,0.028813,-0.005220,-0.108206,0.032899,-0.060140,0.003853,0.001460,0.020918,0.024462,0.002359,-0.022985,0.019798,-0.025704,0.030700,0.003244,-0.038478,0.022926,-0.012498,0.040576,0.013801,-0.007352,-0.025063,-0.068665,-0.039326,-0.023371,0.003791,0.010293,0.026233,-0.031032,0.045196,-0.044498,0.034791,0.026237,-0.033056,-0.009046,-0.042995,-0.002837,-0.016120,0.035771,-0.032063,-0.011672,0.011503,0.010959,0.026612,-0.013402,-0.107988,0.032907,-0.008254,-0.013403,-0.001728,0.005844,0.091777,0.009481,-0.020195,-0.009984,-0.009098,0.050177,-0.053569,0.045557,-0.028756,-0.039760,-0.004011,-0.047827,0.026295,0.032509,0.003785,-0.006810,0.098015,0.010627,0.045197,-0.040085,-0.013018,-0.016939,-0.014443,-0.034869,-0.008606,-0.019030
1,-0.033345,-0.026798,0.014931,-0.037718,0.011014,0.034806,0.034370,0.041291,0.012680,0.046795,-0.011790,-0.011674,-0.046755,-0.056398,-0.008980,-0.007464,0.018599,0.002114,-0.030624,0.023749,0.079805,-0.016002,0.012355,-0.042289,0.023835,-0.063922,-0.030597,-0.028564,-0.008308,0.012124,0.019428,-0.079764,0.015342,0.008454,-0.022203,-0.014037,-0.034376,0.006339,0.091241,0.007660,-0.053530,0.020053,-0.051086,-0.067903,-0.019508,0.041265,0.062604,-0.011510,0.011861,-0.061801,0.014238,-0.016785,-0.007968,-0.035007,0.008905,0.007792,0.011933,0.058978,-0.000735,-0.039224,0.010214,0.052438,-0.038344,-0.042290,-0.040819,-0.016978,0.041443,0.012511,-0.016557,-0.077818,0.002612,-0.006817,0.046479,-0.043181,0.020285,0.030044,0.050898,0.037222,-0.020776,-0.002446,-0.095874,-0.000942,-0.053047,-0.068519,0.014756,-0.038271,-0.027075,-0.022714,-0.033380,0.030450,0.034323,0.037691,-0.037719,-0.072252,0.023464,0.079493,0.060642,-0.021672,-0.076330,-0.030930,-0.023560,-0.009440,-0.002828,0.023106,-0.010808,0.017865,-0.043846,-0.050197,0.015576,-0.031593,-0.074200,0.048396,-0.014024,0.004513,-0.005054,-0.042997,0.020960,-0.012511,-0.062937,-0.053306,-0.054599,0.059595,0.042425,-0.005306,0.021464,0.048090,0.020697,-0.000286,0.041252,-0.021785,0.023299,-0.027129,0.016654,0.023753,-0.029322,0.029460,0.002542,-0.070285,0.028828,-0.030136,-0.031095,-0.047433,-0.064339,0.015117,-0.066725,0.013742,0.018094,-0.059097,-0.011162,0.075173,0.007326,-0.010775,-0.072945,0.045479,0.001639,0.051212,-0.006813,-0.015467,0.008008,0.036419,0.022468,0.052824,-0.004643,0.072080,-0.005055,0.023065,0.118550,-0.080767,-0.001299,0.020157,0.022898,-0.008418,-0.018164,0.025960,0.045765,0.007909,-0.045846,-0.017410,0.018426,-0.018240,0.004044,-0.030968,-0.034642,-0.040314,-0.072908,0.031095,-0.004549,-0.029194,-0.080927,-0.030386,0.028099,-0.047643,0.032690,0.020923,0.012638,0.002487,0.003104,-0.034778,-0.003082,0.037108,-0.045230,0.060928,0.007276,0.079759,0.008106,0.006368,0.071728,-0.003447,0.031785,0.003518,0.080207,-0.021380,-0.098004,-0.042242,-0.057366,-0.041714,-0.011371,-0.025178,0.073225,-0.038680,0.053645,0.034977,-0.086434,-0.022808,0.057058,0.022370,0.024093,-0.043443,0.021971,-0.032826,0.014897,-0.007673,-0.001995,0.047452,-0.070532,0.029897,0.036254,0.006220,-0.097887,-0.013751,-0.053799,0.016993,-0.026669,-0.058055,-0.048948,0.023140,-0.042863,-0.021896,-0.057167,-0.069382,-0.029112,-0.025080,-0.044928,0.014187,0.054520,-0.104421,-0.016637,-0.020996,0.021029,0.016126,0.009074,0.030792,0.012365,-0.038236,0.038041,-0.027178,0.002884,0.007498,0.017607,0.067187,0.005342,-0.015258,0.008142,-0.025233,-0.062203,0.013899,0.038688,0.010992,-0.016024,0.049050,0.025737,-0.004005,0.047907,0.083993,0.010957,0.045252,0.011948,-0.054427,0.015074,0.010321,-0.028197,0.033999,0.039103,-0.004441,0.002698,-0.027127,0.051714,-0.016997,0.000666,-0.035058,-0.013090,-0.012993,0.013014,0.000568,0.053771,-0.010112,-0.055565,-0.008509,-0.042805,0.013463,-0.053225,-0.064597,0.024838,-0.002156,-0.017789,0.016505,-0.032789,-0.038342,0.002721,-0.017069,-0.013081,0.015985,0.059187,0.061006,0.023500,-0.022422,-0.037267,0.039189,0.019090,-0.006668,0.022552,0.024770,0.018742,0.025605,-0.018388,-0.004606,-0.012484,0.029436,-0.008511,-0.000002,-0.011942,0.015989,-0.019420,-0.025433,-0.068756,-0.027896,-0.034255,0.006879,-0.065357,0.031737,0.025685,0.043104,0.058515,-0.031013,-0.031315,-0.022165,-0.030652,0.063324,-0.011475,0.022836,-0.039630,-0.012030,-0.001474,-0.008311,0.021408,-0.064988,0.000927,-0.011974,0.013568,-0.003177,0.016599,-0.027511,0.005000,-0.008442,0.022693,-0.035342,0.027942,0.005316,-0.014666,-0.006821,-0.018257,-0.038946,0.042109,0.001747,0.002058,0.050653,-0.012445,0.027499,0.004632,-0.020067,0.004882,0.041196,0.020356,0.026694,0.035932,-0.023652,0.027316,0.028777,-0.019374,0.024178,-0.010134,-0.006386,-0.023417,-0.038751,0.015027,-0.032897,-0.045990,0.024197,-0.021665,-0.006128,0.028829,-0.000283,0.042798,0.039339,-0.018147,-0.054493,0.035718,0.020665,-0.000056,0.044204,0.002522,0.022301,0.004483,0.063685,-0.015288,-0.073414,0.008086,0.039741,0.007338,0.015677,-0.081301,0.010169,-0.006951,-0.045593,0.027309,-0.016942,0.012966,-0.028918,0.003217,0.016328,-0.005592,-0.033094,0.043922,-0.010841,-0.023050,-0.014630,0.007227,0.015286,-0.026626,0.021013,0.028224,-0.007094,0.021636,-0.041178,-0.008145,-0.018483,0.061108,0.026296,0.030675,0.027121,0.012196,-0.022315,-0.013568,0.006773,0.048340,-0.062740,-0.043710,0.017804,-0.036714,0.027178,-0.022300,-0.041766,-0.026342,-0.037951,0.030346,0.019333,-0.003333,-0.029427,-0.013475,-0.008365,-0.033643,0.071276,0.042394,-0.034449,0.009128,0.076724,-0.070531,-0.045963,0.032373,-0.020922,-0.038662,-0.011356,-0.060807,-0.053504,-0.038356,-0.013018,-0.008713,-0.027717,-0.016559,0.008124,-0.032511,-0.020637,-0.009132,0.009723,-0.014279,0.024001,-0.073365,-0.038813,0.025415,-0.004325,-0.025064,0.002092,-0.007557,-0.012836,0.016828,0.003809,0.020471,-0.021627,-0.008533,-0.047153,0.031599,-0.025622,-0.011069,0.008860,-0.006591,-0.065023,0.010742,0.020114,-0.001927,0.039383,-0.025879,0.012981,-0.026199,0.026288,0.004607,0.053017,0.016019,-0.018972,-0.063700,0.022820,0.042525,-0.035073,-0.042258,-0.048696,0.042749,-0.048742,-0.041033,-0.025600,0.034347,0.011159,-0.001451,0.058043,-0.002333,-0.045112,0.002310,0.031216,-0.008097,-0.008541,-0.032014,-0.040017,-0.024564,-0.048607,0.027169,-0.058186,0.049637,-0.020150,0.002178,0.028058,-0.035129,0.014214,-0.003340,0.022079,-0.054155,0.079708,-0.002151,-0.004165,-0.053024,0.015533,-0.049253,0.009167,-0.011752,0.046802,0.083491,-0.037426,-0.000325,0.037739,0.005170,-0.035579,0.026404,-0.016850,-0.016258,0.012002,-0.040572,-0.003701,0.006201,-0.015033,0.018604,0.032953,0.024299,-0.105473,0.030945,0.016342,-0.011119,0.007588,-0.015708,0.005905,0.019156,-0.055592,0.001559,-0.024615,0.052633,-0.010019,0.030198,0.036011,-0.002681,0.005295,0.031864,-0.025660,-0.028259,0.087253,-0.024695,-0.077474,-0.023948,-0.029078,0.027812,-0.019140,-0.018286,-0.004098,0.024891,-0.028234,-0.030456,0.044328,-0.087960,-0.057876,0.010872,0.019979,-0.040485,-0.040548,0.018451,0.022452,-0.093948,-0.046182,-0.044186,-0.028628,0.014595,0.005312,-0.015258,0.024350,0.019586,0.015123,0.036033,-0.012948,-0.059353,-0.018977,0.067143,0.010076,0.012638,0.053138,0.042028,-0.025022,0.009273,0.012038,-0.021726,-0.009295,0.029497,-0.022325,-0.034428,-0.024494,-0.020580,-0.020242,-0.002751,0.010765,-0.001306,-0.006743,0.007391,0.017814,-0.004571,-0.061027,-0.017485,0.006557,0.024250,-0.022540,0.015654,-0.011709,-0.025294,-0.020580,0.092452,-0.022987,-0.023693,0.062824,0.027181,0.013234,0.042885,-0.134010,0.004763,-0.027894,-0.036826,-0.013923,-0.028311,0.036013,0.008116,-0.021480,0.012690,0.006296,0.027552,-0.015189,0.031425,0.031054,0.008067,-0.023899,0.032227,-0.002346,0.000662,-0.025110,0.019709,-0.039171,-0.015470,0.014889,0.012448,-0.061682,-0.015974,-0.047330,-0.001922,0.000264,0.019768,0.068928,-0.058535,-0.007469,-0.054324,0.013507,-0.032547,-0.002241,0.003297,-0.012541,0.060076,-0.072327,-0.066432,0.011279,-0.015800,-0.028757,-0.058557,0.026677,0.029044,0.010887,-0.067077,-0.031447,0.023242,0.134151,-0.057057,0.020223,-0.016008,-0.009184,0.013219,-0.013843,0.024278,0.033628,0.000902,-0.019496,0.064058,0.012655,-0.019085,0.004780,0.017143,0.007215,-0.006431,-0.028151,-0.041546,-0.038140

### Standardize features

In [286]:
def check_distr(df: pd.DataFrame):
    mse_mean = ((df.mean() - 0) ** 2).mean()
    mse_std = ((df.std() - 1) ** 2).mean()

    print(f"Mean: {df.values.mean()}, mse: {mse_mean}")
    print(f"St.d.: {df.values.std()}, mse: {mse_std}")

check_distr(df_embeddings)

Mean: -0.001966081240334597, mse: 0.0005108162029048404
St.d.: 0.036030746614779854, mse: 0.9447633214832128

In [287]:
from sklearn.preprocessing import StandardScaler

scaled = StandardScaler().fit_transform(df_embeddings)
df_embeddings = pd.DataFrame(scaled)

check_distr(df_embeddings)

Mean: -1.5469828400485812e-18, mse: 1.8774466435463133e-33
St.d.: 1.0, mse: 2.154304308032633e-07

### KMeans

In [288]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

silhouettes = []

k_range = (2, min(len(df_embeddings), 100))

def find_best_n_clusters(start: int = k_range[0], end: int = k_range[1]):
    best_n = dict(
        n=0.0,
        score=-1.0
    )

    for n_clusters in range(start, end):
        kmeans = KMeans(n_clusters=n_clusters, random_state=42)
        kmeans.fit(df_embeddings)

        df_kmeans = pd.DataFrame(kmeans.labels_, columns=['centroid'])

        silhouette_avg = float(silhouette_score(df_embeddings, df_kmeans.values.ravel()))
        silhouettes.append(silhouette_avg)

        if silhouette_avg > best_n['score']:
            best_n['score'] = silhouette_avg
            best_n['n'] = n_clusters
    
    return best_n

best_n_clusters = find_best_n_clusters()

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul


In [289]:
print(f"Best n clusters = {best_n_clusters['n']} with a silhouette score of {best_n_clusters['score']}")
fig = px.line(x=range(*k_range), y=silhouettes)

avg = sum(silhouettes) / len(silhouettes)
fig.add_hline(y=avg, line_dash='dash')

Best n clusters = 23 with a silhouette score of 0.03028554941587913

NOTE! This generally shows a pretty weak argument for single-label clustering (the silhouette score is as low as 0.03 when 1.00 is the ideal). 

But for simplicity for the time being, we can just select the first n of categories that is above the average of all silhouette scores.

In [313]:
n_clusters = None
max_k = 0

# select the first value above avg
for i,k in enumerate(silhouettes): 
    if i > 30:
        break
    if k > max_k:
        max_k = k
        n_clusters = i + 2 # + 2 because k >= 2

n_clusters

23

In [314]:
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(df_embeddings)

labels = kmeans.labels_
centroids = kmeans.cluster_centers_

df_kmeans = pd.DataFrame(labels, columns=['centroid'])
df_kmeans.head()

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:237: RuntimeWarning:

invalid value encountered in matmul

   centroid
0        15
1        19
2         3
3         4
4         4

In [315]:
# import matplotlib.pyplot as plt
# import matplotlib.cm as cm
# import numpy as np
# from sklearn.metrics import silhouette_samples

# sample_silhouette_values = silhouette_samples(df_embeddings, df_kmeans.values.ravel())

# ax1 = plt.subplot()

# y_lower = 10
# for i in range(n_clusters):
#     # Aggregate the silhouette scores for samples belonging to
#     # cluster i, and sort them
#     ith_cluster_silhouette_values = sample_silhouette_values[df_kmeans.values.ravel() == i]

#     ith_cluster_silhouette_values.sort()

#     size_cluster_i = ith_cluster_silhouette_values.shape[0]
#     y_upper = y_lower + size_cluster_i

#     color = cm.nipy_spectral(float(i) / n_clusters)
#     ax1.fill_betweenx(
#         np.arange(y_lower, y_upper),
#         0,
#         ith_cluster_silhouette_values,
#         facecolor=color,
#         edgecolor=color,
#         alpha=0.7,
#     )

#     # Label the silhouette plots with their cluster numbers at the middle
#     ax1.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))

#     # Compute the new y_lower for next plot
#     y_lower = y_upper + 10  # 10 for the 0 samples

# ax1.set_title("The silhouette plot for the various clusters.")
# ax1.set_xlabel("The silhouette coefficient values")
# ax1.set_ylabel("Cluster label")

# # The vertical line for average silhouette score of all the values
# ax1.axvline(x=silhouette_avg, color="red", linestyle="--")

# ax1.set_yticks([])  # Clear the yaxis labels / ticks
# # ax1.set_xticks([-0.1, 0, 0.2, 0.4, 0.6, 0.8, 1])

### PCA

In [316]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_embeddings = pca.fit_transform(df_embeddings)
df_pca = pd.DataFrame(pca_embeddings, columns=['pca_1', 'pca_2'])

df_pca.head(), pca_embeddings.shape, pca.explained_variance_ratio_

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:340: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:340: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:340: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:533: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:533: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:533: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:547: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:547: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:547: RuntimeWarning:

invalid value encountered in matmul

(       pca_1     pca_2
 0   4.835657 -4.971304
 1   1.844232  4.491210
 2   7.487733  0.981564
 3 -10.493422 -3.085940
 4  -2.238666 -4.310638,
 (1078, 2),
 array([0.03738192, 0.02798341]))

In [317]:
# centroids through PCA
pca_centroids = pca.transform(centroids)
pca_centroids.shape

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/decomposition/_base.py:148: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/decomposition/_base.py:148: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/decomposition/_base.py:148: RuntimeWarning:

invalid value encountered in matmul

(23, 2)

In [318]:
df_with_emb = pd.concat([df, df_pca, df_kmeans], axis=1)
df_with_emb.head()

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding,pca_1,pca_2,centroid
0,This House believes that the South Korean government should redirect resources currently used to...,"Koryo-in (고려인) are Korean diasporas residing in post-Soviet countries, mainly\nin Central Asia. ...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,the south korean government should redirect resources currently used to help koryo-in settle in...,"[0.04669427126646042, -0.041124969720840454, 0.0035075603518635035, 0.0260517168790102, 0.031686...",4.835657,-4.971304,15
1,This House believes that we oppose Australia's 501 policy.,"Australia's 501 policy refers to section 501 of the Migration Act 1958, which\ndeals with the ca...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose australia's 501 policy,"[-0.033344559371471405, -0.02679823897778988, 0.014931241050362587, -0.03771759942173958, 0.0110...",1.844232,4.491210,19
2,This House believes that we oppose countries adopting ‘pull-back’ measures to respond to the inf...,Irregular migrants are those who enter another country without official\npermission. In response...,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants,"[0.00870150700211525, -0.06843803077936172, -0.003463117405772209, 0.025157984346151352, 0.01750...",7.487733,0.981564,3
3,"This House believes that we regret self-denial in religion (e.g. celibacy, fasting, giving up ma...",NaN,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"we regret self-denial in religion (eg celibacy, fasting, giving up material or sensory pleasures)","[-0.03781802952289581, 0.033481165766716, 0.05631212145090103, -0.04665393754839897, 0.030571291...",-10.493422,-3.085940,4
4,"This House believes that, in multireligious states, schools should teach integrated religious ed...","In ‘integrated religious education’, all students are taught material\nencompassing many major r...",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,", in multireligious states, schools should teach integrated religious education instead of separ...","[-0.07520031929016113, -0.03346019983291626, 0.06300149857997894, -0.013544010929763317, 0.00563...",-2.238666,-4.310638,4

In [319]:
import plotly.graph_objects as go

fig = go.Figure()

marker = go.scatter.Marker(
    color=df_with_emb['centroid'],
    colorscale='rainbow',
    size=10,
    opacity=0.7
)

centroid_marker = go.scatter.Marker(
    symbol='x',
    size=20,
    opacity=0.5,
    color='gray'
)

fig.add_trace(go.Scatter(x=df_with_emb['pca_1'], y=df_with_emb['pca_2'], mode='markers', hovertext=df_with_emb['Motion'], marker=marker))
# fig.add_trace(go.Scatter(x=pca_centroids[:, 0], y=pca_centroids[:, 1], mode='markers', marker=centroid_marker))

fig.show()

In [320]:
df_with_emb.sort_values('centroid')[['Motion (cleaned)', 'centroid']]

,Motion (cleaned),centroid
1050,implement a national job guarantee,0
771,labor activists should predominantly pursue permeationism over the rank-and-file union-building ...,0
673,"aggressively relax regulations on the construction of new infrastructure (eg, environmental revi...",0
...,...,...
493,medicalization of gender dysphoria among queer community,22
446,the queer community should oppose the glorification of white gender-fluid icons (eg harry style...,22
395,portrayals of bl genre in asian media,22

### t-SNE

In [321]:
from sklearn.manifold import TSNE

tsne = TSNE(n_components=3, random_state=42)
X_tsne = tsne.fit_transform(df_embeddings)

df_tsne = pd.DataFrame(X_tsne, columns=['tsne_1', 'tsne_2', 'tsne_3'])
tsne.kl_divergence_

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:335: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:336: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:340: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:340: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:340: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:533: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:533: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:533: RuntimeWarning:

invalid value encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:547: RuntimeWarning:

divide by zero encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:547: RuntimeWarning:

overflow encountered in matmul

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/sklearn/utils/extmath.py:547: RuntimeWarning:

invalid value encountered in matmul

1.5682158470153809

In [322]:
df_with_emb2 = pd.concat([df_with_emb, df_tsne], axis=1)

In [323]:
px.scatter_3d(df_with_emb2, x='tsne_1', y='tsne_2', z='tsne_3', hover_data='Motion', color='centroid',color_continuous_scale=px.colors.sequential.Jet)

## Auto-label categories with LLMs

In [324]:
from google import genai

from dotenv import load_dotenv
load_dotenv()

client = genai.Client(vertexai=True, project=os.getenv("VERTEXAI_PROJECT_ID"), location="us-central1")

In [325]:
by_category = df_with_emb2.groupby("centroid")

In [326]:
past_themes = [

]

for centroid, group in by_category:
    motions_list = group['Motion'].to_list()
    all_motions = '\n'.join(motions_list)

    user_prompt = f"""
    You are given a list of motions that are related to a single topic or theme. Your task is to label these motions with a single category that best describes them on average, yet is as specific as possible.

    Return your answer as just an appropriate emoji and the category name (1-3 words), no other text.

    For example, 💰 National Economics.
    
    Do not repeat past themes, nor use the same emoji: {past_themes}

    Motions:
    {all_motions}
    """
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=user_prompt
    )

    theme = response.text.strip()
    past_themes.append(theme)

    df_with_emb2.loc[df_with_emb2['centroid'] == centroid, 'category'] = theme

    print(centroid, theme)
    print(motions_list[:3])

0 ⚖️ Government Policy
['This House believes that renters of public housing should be allowed to purchase that housing at a discounted rate.', 'This House believes that, in states with a low fertility rate, we prefer policies with a familising effect rather than a de-familising effect.', 'TH, as the Chinese Communist Party, would prioritize direct stimulus to the private market (e.g. consumption vouchers, tax cuts to companies) over investing into the public sector (e.g. reducing debt burdens of local governments, investments in State-Owned Enterprises)']
1 🌍 Environmental Advocacy
['THBT environmental movements should heaviliy prioritize climate litigation as an advocacy strategy', 'THS disruptive climate protests by environmental movements (e.g., blocking traffic)', 'This House believes that the environmentalist movement should include a just transition away from the animal agriculture industry in its messaging']
2 🎭 Societal Narratives
['This House believes that we oppose the portrayal of vengeance in media as morally justified (e.g. John Wick, Kill Bill, Taken).', 'This House believes that, as an artist, we would prioritise making our art comprehensible to audiences, at the expense of authentic self-expression.', 'THO the premium placed on humility']
3 🏛️ International Relations
['This House believes that we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants.', 'This House believes that we oppose Ukraine expanding military operations into Sudan and Syria.', 'This House believes that the EU should give all legislative power to a single body.']
4 🙏 Religious Doctrine
['This House believes that we regret self-denial in religion (e.g. celibacy, fasting, giving up material or sensory pleasures).', 'This House believes that, in multireligious states, schools should teach integrated religious education instead of separated religious education.', 'This House believes that we regret the influence of the Filipino Catholic Church in the People Power Revolution.']
5 📱 Modern Trends
['THR the decline of home cooking', "TH regrets the rise of a 'hookup culture' (one which accepts and encourages casual sexual encounters focused on physical pleasure, without necessarily including emotional bonding)", 'THBT the ubiquity of dating apps has done more harm than good.']
6 🧑‍⚖️ Criminal Justice
['This House believes that we would not grant legal protections to the wishes of the dead.', 'This House believes that we support funding orders in class action litigation.', 'This House believes that Māori should pursue redress for colonisation through novel legal claims rather than through the Waitangi Tribunal.']
7 🤔 Hypothetical Worlds
['This House believes that we support Microsoft’s investment into OpenAI.', 'This House believes that we support Microsoft’s investment into OpenAI.', 'THBT Marx would have approved of AI']
8 🧑‍🏫 Educational Institutions
['This House believes that artists should always refuse requests to do unpaid work.', 'This House believes that governments should set up a department dedicated to producing and submitting ‘Sokal papers’ to academic journals, removing academics that admit Sokal papers and shutting down faculties that systemically admit ‘Sokal papers’.', 'This House believes that all scientific journals should move to a registered reports model of publication']
9 🏦 Global Finance
["This House believes that we support Indonesia's revision of their green investment rulebook.", 'This House believes that China should require shadow banks to obtain formal bank licenses in order to continue operating.', 'THP the main banking system to dominantly shareholder based investments']
10 ✊ Political Movements
['This House believes that, as the Houthi rebels, we would reject any negotiations with the Presidential Leadership Council', 'This House believes that Western states should support local rebel groups (e.g. by funding them and giving them intel) as opposed to direct military intervention in other states', 'THBT developing countries should ban members of political dynasties from standing for elected office']
11 ♀️ Feminist Debates
['This House believes that the feminist movement should support the portrayal of women as the source of fear in films (ex. Miranda Priestly in the Devil Wears Prada, Carrie in Carrie, Dolores Umbridge in Harry Potter)', 'This House believes that we prefer a world where co-parenting is primarily non-romantic (ie. conducted by consenting partners who have no romantic or sexual relationship, eg. friends).', 'THBT women should reject practices that alter the appearance of their genitalia, such as waxing and labiaplasty']
12 🛑 Economic Regulation
['This House believes that we would discontinue the Jakarta capital city relocation project.', 'This House believes that governments should enter into offtake agreements with emerging manufacturers of green energy technology.', 'This House believes that we should break up the three big chocolate traders.']
13 🗳️ Electoral Systems
['This House believes that military leaders should be directly elected by citizens.', 'This House believes that the Philippines should disallow split-ticket voting.', 'THO the practice of vote buying']
14 ⚽ Professional Sports
["This House believes that sports clubs should adopt a blanket 'no fault stand-down' policy.", 'This House believes that we oppose the use of video refereeing to make on-field decisions.', 'This House believes that, as a reigning F2 champion with no promised F1 seat, we would choose to race in a different series over taking a F1 reserve seat.']
15 ⚔️ Military Affairs
['This House believes that the South Korean government should redirect resources currently used to help Koryo-in settle in their respective countries of residence, to efforts to resettle them in South Korea.', "This House believes that we oppose the attempts of civil organisations in South Korea to inform North Korean citizens about their regime's wrongdoings (e.g. disseminating leaflets and ad balloons, smuggling USBs, transmitting cross-border radio waves).", 'This House believes that we regret the rise of open-audition programs in the K-Pop industry.']
16 🍎 Curriculum Design
['In post-colonial states, THP education where strong emphasis is placed on multi-culturalism over similarities between different groups', 'THBT the United States of America should fund moderate Madrassas (schools of Islamic study) throughout the Islamic world', 'This House believes that we should vocationalise teaching']
17 📢 Media Influence
["THP 'direct cinema' to 'cinema verite' as a dominant approach to production of video journalism and documentary films", 'THBT social movements should prioritise blaming the structure over particular public figures', 'This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms.']
18 🫂 Cultural Identity
['This House believes that we regret the cooption of indigenous and minority languages, art and culture for fantasy and sci-fi worldbuilding.', "THBT affirmative action policies should include 'model minorities', even in instances where that minority has sufficient representation", 'THR the popularization of culturally significant locations as tourist destinations (e.g. Bali and Central Java in Indonesia, Siem Reap in Cambodia etc)']
19 ⚕️ Medical Ethics
["This House believes that we oppose Australia's 501 policy.", 'This House believes that we prefer all human genome editing experiments to be approved by the WHO rather than domestic regulatory bodies.', 'This House believes that we prefer all human genome editing experiments to be approved by the WHO rather than domestic regulatory bodies.']
20 🧭 Political Ideologies
['Assuming a peaceful and democratic transition, this house supports the United States of America being separated into several, more politically-homogeneous, sovereign states.', 'This House believes that developed countries should pursue a policy of degrowth', 'This House believes that developed countries should pursue a policy of degrowth']
21 🇨🇳 China's Foreign Policy
['This House believes that the National Semiconductor Strategy is in the interests of Malaysia.', "This House believes that it is in China's interests to abandon the CPEC project.", 'This house, as Nepal, prefers strengthening our long-term relationship with China rather than India.']
22 🏳️‍🌈 LGBTQ+ Activism
['This House believes that in the aftermath of the repeal of Section 377A, the LGBTQ+ movement in Singapore should actively prioritise fighting for reforms that impact the Trans community, at the exclusion of fighting for gay marriage.', 'This House believes that the LGBTQ+ movement should abandon the advocacy for traditional societal norms (marriage equality, religious acceptance) in favour of non-traditional norms (irreligiosity, hyper-sexualization, polyamoury/open relationships etc).', 'This House opposes the prominence of the "Out & Proud" movement in LGBTQ+ advocacy']

In [327]:
category_counts = df_with_emb2.value_counts('category')
px.bar(category_counts)

In [328]:
for category, label in category_counts.items():
    print(category)

🛑 Economic Regulation
🤔 Hypothetical Worlds
🗳️ Electoral Systems
🧑‍⚖️ Criminal Justice
⚖️ Government Policy
🇨🇳 China's Foreign Policy
⚕️ Medical Ethics
🏛️ International Relations
🙏 Religious Doctrine
✊ Political Movements
📱 Modern Trends
🏦 Global Finance
⚽ Professional Sports
🎭 Societal Narratives
♀️ Feminist Debates
📢 Media Influence
🧑‍🏫 Educational Institutions
🫂 Cultural Identity
⚔️ Military Affairs
🍎 Curriculum Design
🧭 Political Ideologies
🌍 Environmental Advocacy
🏳️‍🌈 LGBTQ+ Activism

In [329]:
most_common_category = category_counts.idxmax()
df_with_emb2[df_with_emb2['category'] == most_common_category]['Motion'].head()

7              This House believes that we would discontinue the Jakarta capital city relocation project.
20    This House believes that governments should enter into offtake agreements with emerging manufact...
24                           This House believes that we should break up the three big chocolate traders.
25                              This House believes that regulators should be granted divestiture powers.
26                                           This House believes that we should ban personalised pricing.
Name: Motion, dtype: object

## Context/prerequisites analysis (deprecated: not reliable!)

TODO: can we measure difficulty by speaker score averages? 

-> easier motions should have higher average speaker scores across everyone in the tournament
this only works when comparing with a single tournaments (unless you trust speaker scores)

In [330]:
import pandas as pd
import plotly.express as px
from datetime import datetime
import os
import asyncio
import time
from functools import wraps
import random

# Exponential backoff retry decorator for handling timeouts
def exponential_backoff_retry(
    max_retries=5, 
    base_delay=3.0, 
    max_delay=60.0, 
    exponential_base=2.0,
    jitter=True,
    timeout_exceptions=(asyncio.TimeoutError, TimeoutError, Exception)
):
    """
    Decorator that implements exponential backoff with retries for timeout handling.
    
    Args:
        max_retries: Maximum number of retry attempts
        base_delay: Initial delay in seconds
        max_delay: Maximum delay cap in seconds
        exponential_base: Base for exponential calculation
        jitter: Whether to add random jitter to delays
        timeout_exceptions: Tuple of exception types to retry on
    """
    def decorator(func):
        @wraps(func)
        async def async_wrapper(*args, **kwargs):
            last_exception = None
            
            for attempt in range(max_retries + 1):
                try:
                    return await func(*args, **kwargs)
                except timeout_exceptions as e:
                    last_exception = e
                    
                    if attempt == max_retries:
                        print(f"Max retries ({max_retries}) reached. Final error: {e}")
                        raise e
                    
                    # Calculate delay with exponential backoff
                    delay = min(base_delay * (exponential_base ** attempt), max_delay)
                    
                    # Add jitter to prevent thundering herd
                    if jitter:
                        delay = delay * (0.5 + random.random() * 0.5)
                    
                    print(f"Timeout on attempt {attempt + 1}/{max_retries + 1}. "
                          f"Retrying in {delay:.2f} seconds... Error: {e}")
                    
                    await asyncio.sleep(delay)
                    
                except Exception as e:
                    # For non-timeout exceptions, don't retry
                    print(f"Non-timeout error on attempt {attempt + 1}: {e}")
                    raise e
            
            # This should never be reached, but just in case
            raise last_exception
        
        @wraps(func)
        def sync_wrapper(*args, **kwargs):
            last_exception = None
            
            for attempt in range(max_retries + 1):
                try:
                    return func(*args, **kwargs)
                except timeout_exceptions as e:
                    last_exception = e
                    
                    if attempt == max_retries:
                        print(f"Max retries ({max_retries}) reached. Final error: {e}")
                        raise e
                    
                    # Calculate delay with exponential backoff
                    delay = min(base_delay * (exponential_base ** attempt), max_delay)
                    
                    # Add jitter to prevent thundering herd
                    if jitter:
                        delay = delay * (0.5 + random.random() * 0.5)
                    
                    print(f"Timeout on attempt {attempt + 1}/{max_retries + 1}. "
                          f"Retrying in {delay:.2f} seconds... Error: {e}")
                    
                    time.sleep(delay)
                    
                except Exception as e:
                    # For non-timeout exceptions, don't retry
                    print(f"Non-timeout error on attempt {attempt + 1}: {e}")
                    raise e
            
            # This should never be reached, but just in case
            raise last_exception
        
        # Return the appropriate wrapper based on whether the function is async
        if asyncio.iscoroutinefunction(func):
            return async_wrapper
        else:
            return sync_wrapper
    
    return decorator

# ... existing code ...

In [331]:
@exponential_backoff_retry()
async def rank_motion_difficulty(motion: str, info_slide: str): 
    user_prompt = f"""
    You are given a motion (and optionally its info slide) from a debate tournament. Your task is to rank how much background knowledge is required properly understand and debate this motion.
    If it is something an average intelligent voter would already know and understand, assign a score of 1.

    Return your answer as a single an integer between 1 and 5, no other text.

    Examples:

    This house prefers a world where genius only develops after adulthood (so that there are no child prodigies). [1]
    This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms. [2]
    This House prefers a diverse number of highly competitive banks to a small number of banks. [3]
    THBT Panama should replace the US dollar with its own independent currency. [4]

    (Info slide):
    {info_slide}
    Motion:
    {motion}
    """

    response = await client.aio.models.generate_content(
        model="gemini-2.0-flash",
        contents=user_prompt
    )

    return int(response.text)

In [332]:
motion = df_with_emb2.iloc[0]
test = await rank_motion_difficulty(motion['Motion'], motion['Info Slide'])
motion['Motion'], test

('This House believes that the South Korean government should redirect resources currently used to help Koryo-in settle in their respective countries of residence, to efforts to resettle them in South Korea.',
 5)

In [333]:
import asyncio

BATCH_SIZE = 50  # Adjust as needed

async def get_difficulty_for_row(row, i):
    try: 
        print(f"Getting difficulty for row {i}")
        difficulty = await rank_motion_difficulty(row['Motion'], row['Info Slide'])
        return difficulty
    except Exception as e:
        print(f"Error getting difficulty for row {i}: {e}")
        return None

all_difficulties = []

for start in range(0, len(df_with_emb2), BATCH_SIZE):
    batch = df_with_emb2.iloc[start:start+BATCH_SIZE]

    difficulties = await asyncio.gather(*[get_difficulty_for_row(row, i) for i, row in batch.iterrows()])
    all_difficulties.extend(difficulties)

df_with_emb2['Difficulty'] = all_difficulties
df_with_emb2.head()

Getting difficulty for row 0
Getting difficulty for row 1
Getting difficulty for row 2
Getting difficulty for row 3
Getting difficulty for row 4
Getting difficulty for row 5
Getting difficulty for row 6
Getting difficulty for row 7
Getting difficulty for row 8
Getting difficulty for row 9
Getting difficulty for row 10
Getting difficulty for row 11
Getting difficulty for row 12
Getting difficulty for row 13
Getting difficulty for row 14
Getting difficulty for row 15
Getting difficulty for row 16
Getting difficulty for row 17
Getting difficulty for row 18
Getting difficulty for row 19
Getting difficulty for row 20
Getting difficulty for row 21
Getting difficulty for row 22
Getting difficulty for row 23
Getting difficulty for row 24
Getting difficulty for row 25
Getting difficulty for row 26
Getting difficulty for row 27
Getting difficulty for row 28
Getting difficulty for row 29
Getting difficulty for row 30
Getting difficulty for row 31
Getting difficulty for row 32
Getting difficulty for row 33
Getting difficulty for row 34
Getting difficulty for row 35
Getting difficulty for row 36
Getting difficulty for row 37
Getting difficulty for row 38
Getting difficulty for row 39
Getting difficulty for row 40
Getting difficulty for row 41
Getting difficulty for row 42
Getting difficulty for row 43
Getting difficulty for row 44
Getting difficulty for row 45
Getting difficulty for row 46
Getting difficulty for row 47
Getting difficulty for row 48
Getting difficulty for row 49
Getting difficulty for row 50
Getting difficulty for row 51
Getting difficulty for row 52
Getting difficulty for row 53
Getting difficulty for row 54
Getting difficulty for row 55
Getting difficulty for row 56
Getting difficulty for row 57
Getting difficulty for row 58
Getting difficulty for row 59
Getting difficulty for row 60
Getting difficulty for row 61
Getting difficulty for row 62
Getting difficulty for row 63
Getting difficulty for row 64
Getting difficulty for row 65
Getting difficulty for row 66
Getting difficulty for row 67
Getting difficulty for row 68
Getting difficulty for row 69
Getting difficulty for row 70
Getting difficulty for row 71
Getting difficulty for row 72
Getting difficulty for row 73
Getting difficulty for row 74
Getting difficulty for row 75
Getting difficulty for row 76
Getting difficulty for row 77
Getting difficulty for row 78
Getting difficulty for row 79
Getting difficulty for row 80
Getting difficulty for row 81
Getting difficulty for row 82
Getting difficulty for row 83
Getting difficulty for row 84
Getting difficulty for row 85
Getting difficulty for row 86
Getting difficulty for row 87
Getting difficulty for row 88
Getting difficulty for row 89
Getting difficulty for row 90
Getting difficulty for row 91
Getting difficulty for row 92
Getting difficulty for row 93
Getting difficulty for row 94
Getting difficulty for row 95
Getting difficulty for row 96
Getting difficulty for row 97
Getting difficulty for row 98
Getting difficulty for row 99
Getting difficulty for row 100
Getting difficulty for row 101
Getting difficulty for row 102
Getting difficulty for row 103
Getting difficulty for row 104
Getting difficulty for row 105
Getting difficulty for row 106
Getting difficulty for row 107
Getting difficulty for row 108
Getting difficulty for row 109
Getting difficulty for row 110
Getting difficulty for row 111
Getting difficulty for row 112
Getting difficulty for row 113
Getting difficulty for row 114
Getting difficulty for row 115
Getting difficulty for row 116
Getting difficulty for row 117
Getting difficulty for row 118
Getting difficulty for row 119
Getting difficulty for row 120
Getting difficulty for row 121
Getting difficulty for row 122
Getting difficulty for row 123
Getting difficulty for row 124
Getting difficulty for row 125
Getting difficulty for row 126
Getting difficulty for row 127
Getting difficulty for row 128
Getting difficulty for row 129
Getting difficulty for row 130
Getting difficulty for row 131
Getting difficulty for row 132
Getting difficulty for row 133
Getting difficulty for row 134
Getting difficulty for row 135
Getting difficulty for row 136
Getting difficulty for row 137
Getting difficulty for row 138
Getting difficulty for row 139
Getting difficulty for row 140
Getting difficulty for row 141
Getting difficulty for row 142
Getting difficulty for row 143
Getting difficulty for row 144
Getting difficulty for row 145
Getting difficulty for row 146
Getting difficulty for row 147
Getting difficulty for row 148
Getting difficulty for row 149
Getting difficulty for row 150
Getting difficulty for row 151
Getting difficulty for row 152
Getting difficulty for row 153
Getting difficulty for row 154
Getting difficulty for row 155
Getting difficulty for row 156
Getting difficulty for row 157
Getting difficulty for row 158
Getting difficulty for row 159
Getting difficulty for row 160
Getting difficulty for row 161
Getting difficulty for row 162
Getting difficulty for row 163
Getting difficulty for row 164
Getting difficulty for row 165
Getting difficulty for row 166
Getting difficulty for row 167
Getting difficulty for row 168
Getting difficulty for row 169
Getting difficulty for row 170
Getting difficulty for row 171
Getting difficulty for row 172
Getting difficulty for row 173
Getting difficulty for row 174
Getting difficulty for row 175
Getting difficulty for row 176
Getting difficulty for row 177
Getting difficulty for row 178
Getting difficulty for row 179
Getting difficulty for row 180
Getting difficulty for row 181
Getting difficulty for row 182
Getting difficulty for row 183
Getting difficulty for row 184
Getting difficulty for row 185
Getting difficulty for row 186
Getting difficulty for row 187
Getting difficulty for row 188
Getting difficulty for row 189
Getting difficulty for row 190
Getting difficulty for row 191
Getting difficulty for row 192
Getting difficulty for row 193
Getting difficulty for row 194
Getting difficulty for row 195
Getting difficulty for row 196
Getting difficulty for row 197
Getting difficulty for row 198
Getting difficulty for row 199
Getting difficulty for row 200
Getting difficulty for row 201
Getting difficulty for row 202
Getting difficulty for row 203
Getting difficulty for row 204
Getting difficulty for row 205
Getting difficulty for row 206
Getting difficulty for row 207
Getting difficulty for row 208
Getting difficulty for row 209
Getting difficulty for row 210
Getting difficulty for row 211
Getting difficulty for row 212
Getting difficulty for row 213
Getting difficulty for row 214
Getting difficulty for row 215
Getting difficulty for row 216
Getting difficulty for row 217
Getting difficulty for row 218
Getting difficulty for row 219
Getting difficulty for row 220
Getting difficulty for row 221
Getting difficulty for row 222
Getting difficulty for row 223
Getting difficulty for row 224
Getting difficulty for row 225
Getting difficulty for row 226
Getting difficulty for row 227
Getting difficulty for row 228
Getting difficulty for row 229
Getting difficulty for row 230
Getting difficulty for row 231
Getting difficulty for row 232
Getting difficulty for row 233
Getting difficulty for row 234
Getting difficulty for row 235
Getting difficulty for row 236
Getting difficulty for row 237
Getting difficulty for row 238
Getting difficulty for row 239
Getting difficulty for row 240
Getting difficulty for row 241
Getting difficulty for row 242
Getting difficulty for row 243
Getting difficulty for row 244
Getting difficulty for row 245
Getting difficulty for row 246
Getting difficulty for row 247
Getting difficulty for row 248
Getting difficulty for row 249
Getting difficulty for row 250
Getting difficulty for row 251
Getting difficulty for row 252
Getting difficulty for row 253
Getting difficulty for row 254
Getting difficulty for row 255
Getting difficulty for row 256
Getting difficulty for row 257
Getting difficulty for row 258
Getting difficulty for row 259
Getting difficulty for row 260
Getting difficulty for row 261
Getting difficulty for row 262
Getting difficulty for row 263
Getting difficulty for row 264
Getting difficulty for row 265
Getting difficulty for row 266
Getting difficulty for row 267
Getting difficulty for row 268
Getting difficulty for row 269
Getting difficulty for row 270
Getting difficulty for row 271
Getting difficulty for row 272
Getting difficulty for row 273
Getting difficulty for row 274
Getting difficulty for row 275
Getting difficulty for row 276
Getting difficulty for row 277
Getting difficulty for row 278
Getting difficulty for row 279
Getting difficulty for row 280
Getting difficulty for row 281
Getting difficulty for row 282
Getting difficulty for row 283
Getting difficulty for row 284
Getting difficulty for row 285
Getting difficulty for row 286
Getting difficulty for row 287
Getting difficulty for row 288
Getting difficulty for row 289
Getting difficulty for row 290
Getting difficulty for row 291
Getting difficulty for row 292
Getting difficulty for row 293
Getting difficulty for row 294
Getting difficulty for row 295
Getting difficulty for row 296
Getting difficulty for row 297
Getting difficulty for row 298
Getting difficulty for row 299
Getting difficulty for row 300
Getting difficulty for row 301
Getting difficulty for row 302
Getting difficulty for row 303
Getting difficulty for row 304
Getting difficulty for row 305
Getting difficulty for row 306
Getting difficulty for row 307
Getting difficulty for row 308
Getting difficulty for row 309
Getting difficulty for row 310
Getting difficulty for row 311
Getting difficulty for row 312
Getting difficulty for row 313
Getting difficulty for row 314
Getting difficulty for row 315
Getting difficulty for row 316
Getting difficulty for row 317
Getting difficulty for row 318
Getting difficulty for row 319
Getting difficulty for row 320
Getting difficulty for row 321
Getting difficulty for row 322
Getting difficulty for row 323
Getting difficulty for row 324
Getting difficulty for row 325
Getting difficulty for row 326
Getting difficulty for row 327
Getting difficulty for row 328
Getting difficulty for row 329
Getting difficulty for row 330
Getting difficulty for row 331
Getting difficulty for row 332
Getting difficulty for row 333
Getting difficulty for row 334
Getting difficulty for row 335
Getting difficulty for row 336
Getting difficulty for row 337
Getting difficulty for row 338
Getting difficulty for row 339
Getting difficulty for row 340
Getting difficulty for row 341
Getting difficulty for row 342
Getting difficulty for row 343
Getting difficulty for row 344
Getting difficulty for row 345
Getting difficulty for row 346
Getting difficulty for row 347
Getting difficulty for row 348
Getting difficulty for row 349
Timeout on attempt 1/6. Retrying in 1.60 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.95 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.39 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 1.85 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 1.53 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.53 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.52 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.44 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.01 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.55 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.68 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.00 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 1.58 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.06 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 3.00 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.04 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.26 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.48 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 1.97 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.37 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.19 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 1.70 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 1.89 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.80 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.46 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}
Timeout on attempt 1/6. Retrying in 2.11 seconds... Error: 429 RESOURCE_EXHAUSTED. {'error': {'code': 429, 'message': 'Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/error-code-429 for more details.', 'status': 'RESOURCE_EXHAUSTED'}}

CancelledError:

In [ ]:
df_with_emb2[df_with_emb2['Difficulty'].isna()]

,Motion,Info Slide,Tournament,sum_og,sum_oo,sum_cg,sum_co,sum_og_og,sum_oo_oo,sum_cg_cg,sum_co_co,sum_og_oo,sum_og_cg,sum_og_co,sum_oo_cg,sum_oo_co,sum_cg_co,og_wins,oo_wins,cg_wins,co_wins,n,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,Difficulty
560,THR the use of the narrative of successful colonial resistance by political parties for politica...,NaN,bduadc2020:uadc2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,EFL Semifinals,E,NaN,NaN,2020.0,regrets,use of narrative of successful colonial resistance by political parties for political gain,-1.170807,-10.224353,12,7.883465,-38.652180,-0.549297,🏛️ Political Movements,NaN
561,THBT opposition parties in authoritarian democracies should actively prioritise their militant w...,An authoritarian democracy is one in which democratic institutions exist but may be manipulated ...,bduadc2020:uadc2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,EFL Semifinals,E,NaN,NaN,2020.0,believes,opposition parties in authoritarian democracies should actively prioritise their militant wings ...,3.160402,-6.975716,12,1.788872,-28.328962,-21.387804,🏛️ Political Movements,NaN
567,This House regrets the pervasiveness of colonial determinism in discourse surrounding African de...,Colonial determinism refers to the view that postcolonial states are irredeemably influenced by ...,bduadc2020:uadc2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,EFL Grand Final,E,NaN,NaN,2020.0,regrets,pervasiveness of colonial determinism in discourse surrounding african development and politics,-0.485554,-13.006703,1,5.264709,-39.589684,9.306721,🌍 Global Development,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
574,THP a cashless world,NaN,paudc2022:PAUDC2022,17.0,31.0,20.0,28.0,35.0,81.0,46.0,62.0,27.0,11.0,29.0,32.0,46.0,31.0,0.0,0.0,0.0,0.0,16,Round 4,P,NaN,NaN,2022.0,prefers,a cashless world,-0.269564,0.792058,11,15.322305,3.736644,44.701248,🤔 Philosophical Concepts,NaN
579,THBT globalization has failed,NaN,paudc2022:PAUDC2022,22.0,20.0,28.0,26.0,52.0,42.0,68.0,62.0,26.0,30.0,24.0,26.0,26.0,44.0,0.0,0.0,0.0,0.0,16,Round 9,P,NaN,NaN,2022.0,believes,globalization has failed,3.164158,-5.170668,1,-41.730572,10.258051,22.205425,🌍 Global Development,NaN
899,This House believes that western countries should refuse to negotiate with the United States to ...,NaN,easters2025:easters2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Round 6,P,NaN,NaN,2025.0,believes,western countries should refuse to negotiate with the united states to avoid the imposition of ...,8.961440,-0.530816,8,-47.435307,-18.624079,12.128250,🇨🇳 Sino Affairs,NaN

In [ ]:
df_with_emb2[df_with_emb2['Difficulty'] == 3].sample(10)

,Motion,Info Slide,Tournament,sum_og,sum_oo,sum_cg,sum_co,sum_og_og,sum_oo_oo,sum_cg_cg,sum_co_co,sum_og_oo,sum_og_cg,sum_og_co,sum_oo_cg,sum_oo_co,sum_cg_co,og_wins,oo_wins,cg_wins,co_wins,n,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,Difficulty
300,THP religious organisations to actively propagate the idea that faith in a higher power cannot b...,NaN,eudc2021:eudc2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Semifinals,E,NaN,NaN,2021.0,prefers,religious organisations to actively propagate the idea that faith in a higher power cannot be ex...,-6.976997,-1.762353,6,30.366627,-27.716940,15.884662,🙏 Religious Ideology,3.0
429,THR the US' declining relative influence over global governance,NaN,abp2020:abp2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,EFL Finals,E,NaN,NaN,2020.0,regrets,us' declining relative influence over global governance,4.651137,-8.975512,8,-43.885498,3.036664,23.589317,🇨🇳 Sino Affairs,3.0
214,This house would allow effort optimization strategies in American professional sports leagues,"In many American professional sports leagues, teams have considered using\n""effort optimization ...",usudc2025:_,31.0,39.0,24.0,26.0,79.0,91.0,58.0,52.0,53.0,16.0,38.0,47.0,43.0,23.0,0.0,0.0,0.0,0.0,20,Round 1,P,NaN,NaN,2025.0,would,allow effort optimization strategies in american professional sports leagues,-0.033050,5.626283,13,-7.006047,51.156990,-3.156822,⚽ Sports & Culture,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,This House believes that we would ban private prosecutions.,Most criminal prosecutions are brought by the state. A private prosecution is\na criminal case w...,easters2025:easters2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Round 3,P,NaN,NaN,2025.0,believes,we would ban private prosecutions,2.414823,12.758208,0,-2.299911,6.536935,14.677292,⚖️ Policy & Governance,3.0
741,This House believes that health care providers should be allowed to offer terminally ill patient...,NaN,easters2022:easters2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Round 5,P,NaN,NaN,2022.0,believes,health care providers should be allowed to offer terminally ill patients the option of a cash g...,-0.766261,7.654617,2,10.618214,27.085083,18.144449,🧑‍⚖️ Social Justice,3.0
886,This House believes that we prefer the 'Help to Buy' scheme to the 'Super for Housing' scheme.,Both major Australian political parties have proposed competing measures to\nassist first-home b...,easters2025:easters2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Round 2,P,NaN,NaN,2025.0,believes,we prefer the 'help to buy' scheme to the 'super for housing' scheme,2.133281,5.932016,7,-22.465141,-1.227273,-23.578163,📈 Economic Intervention,3.0

In [595]:
difficulty_freq = df_with_emb2['Difficulty'].value_counts().sort_index()
px.bar(difficulty_freq, y='count', title='Difficulty Frequency',
width=1000, height=600).show()

### Difficulty by category

In [601]:
pd.set_option('display.max_columns', None)
by_category_with_difficulty = df_with_emb2.groupby('category')

avg_difficulty_by_category = by_category_with_difficulty['Difficulty'].mean().sort_values(ascending=True)
px.bar(avg_difficulty_by_category, width=1000, height=600, title="Difficulty x Theme").show()

### Difficulty by motion type

In [ ]:
by_category_with_difficulty = df_with_emb2.groupby('Motion Type')

avg_difficulty_by_category = by_category_with_difficulty['Difficulty'].mean().sort_values(ascending=True)
px.bar(avg_difficulty_by_category, width=1000, height=600).show()

## Difficulty by speaker scores

In [439]:
df_with_emb2['avg_speaks'] = df_with_emb2['speaks'] / df_with_emb2['n'] / (4 * 2)
df_with_emb2.head()

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding,pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,avg_speaks,tournament_avg_speaks,difficulty,z,imbalance
0,"This House believes that the South Korean government should redirect resources currently used to help Koryo-in settle in their respective countries of residence, to efforts to resettle them in South Korea.","Koryo-in (고려인) are Korean diasporas residing in post-Soviet countries, mainly\nin Central Asia. Koryo-ins moved to the Far East and Primorsky regions during\nthe 1910s to organise resistance against Japanese colonisation, until the\nSoviet Union forcefully relocated them to other territories in 1937. There are\naround 500,000 Koryo-ins, most of whom still identify as Korean descendants.\n\nThe South Korean government helps Koryo-ins abroad to settle in their\nrespective countries of residence by providing foreign aid in education, job\ntraining, etc.",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"the south korean government should redirect resources currently used to help koryo-in settle in their respective countries of residence, to efforts to resettle them in south korea","[0.04669427126646042, -0.041124969720840454, 0.0035075603518635035, 0.0260517168790102, 0.03168632462620735, 0.03356233984231949, -0.009249215014278889, -0.006061697844415903, -0.02862136997282505, 0.00864429771900177, 0.039939191192388535, -0.037726085633039474, -0.011120708659291267, -0.005691937170922756, -0.0199541375041008, -0.02535325102508068, 0.05702070891857147, -0.03576156869530678, -0.018242238089442253, 0.00883160624653101, 0.039861615747213364, -0.004181785508990288, 0.058362044394016266, 0.026758529245853424, 0.005156387109309435, -0.04580002278089523, -0.022358663380146027, 0.029002021998167038, -0.023128962144255638, -0.011231628246605396, 0.02017585188150406, -0.027394147589802742, 0.01893795281648636, -0.09919628500938416, -0.027543263509869576, 0.0016221209662035108, -0.025253776460886, -0.0274977944791317, 0.05655022710561752, -0.0008209593943320215, 0.057827334851026535, 0.013685733079910278, -0.0398455411195755, 0.014219488948583603, 0.03576551005244255, -0.019864141941070557, 0.01987016573548317, 0.04374896362423897, -0.036258265376091, -0.05490824207663536, 0.05305888131260872, -0.05439281463623047, 0.02745940163731575, -0.0241154246032238, -0.022838830947875977, -0.0018793627386912704, -0.006121313199400902, 0.04279809445142746, -0.012427078559994698, 0.023106200620532036, 0.005948835518211126, -0.0017394074238836765, 0.0648064985871315, -0.01647108420729637, -0.007654597982764244, 0.015587597154080868, 0.04501911625266075, -0.0003992000420112163, -0.02531033754348755, 0.007292148191481829, 0.015378573909401894, -0.05804913491010666, 0.07032416015863419, -0.03853347897529602, 0.003318109782412648, 0.03297140821814537, 0.0666864886879921, 0.040921054780483246, 0.0013249622425064445, -0.032992884516716, 0.0047950237058103085, -0.011690525338053703, -0.03517264872789383, -0.011561808176338673, 0.013435029424726963, -0.034368522465229034, -0.08386398106813431, 0.01719943806529045, -0.005637293215841055, -0.004097035154700279, 0.006272714119404554, 0.05273690074682236, 0.002075214870274067, -0.018995273858308792, 0.049240000545978546, 0.08046840876340866, 0.044540584087371826, 0.032655466347932816, -0.06836190819740295, -0.017110392451286316, ...]",4.835657,-4.971304,15,2.943763,-38.048893,27.929848,⚔️ Military Affairs,NaN,NaN,NaN,NaN,NaN
1,This House believes that we oppose Australia's 501 policy.,"Australia's 501 policy refers to section 501 of the Migration Act 1958, which\ndeals with the cancellation of visas on character grounds. Under the policy,\nthe Australian government has the authority to cancel the visas of and deport\nnon-citizens who fail the character test, regardless of how long they have\nlived in Australia. The policy is typically applied to individuals who have\nbeen sentenced to at least one year imprisonment.",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose australia's 501 policy,"[-0.033344559371471405, -0.02679823897778988, 0.014931241050362587, -0.03771759942173958, 0.011014328338205814, 0.03480580821633339, 0.03436955437064171, 0.04129122570157051, 0.012680070474743843, 0.046794693917036057, -0.011789522133767605, -0.011674067936837673, -0.04675508290529251, -0.056398194283246994, -0.008980480954051018, -0.007463964633643627, 0.01859915629029274, 0.0021135136485099792, -0.030623668804764748, 0.02374877780675888, 0.07980476319789886, -0.016002120450139046, 0.012355057522654533, -0.04228943958878517, 0.023834997788071632, -0.06392233818769455, -0.030597040429711342, -0.028563939034938812, -0.008308157324790955, 0.012124162167310715, 0.019427834078669548, -0.07976411283016205, 0.01534205861389637, 0.008453872986137867, -0.022203102707862854, -0.01403671782463789, -0.034375909715890884, 0.0063390349969267845, 0.0912412777543068, 0.007660025730729103, -0.05352997034788132, 0.020052649080753326, -0.05108562856912613, -0.06790313869714737, -0.019507864490151405, 0.041264504194259644, 0.06260392814874649, -0.011509700678288937, 0.011861427687108517, -0.06180088222026825, 0.014238405972719193, -0.016785146668553352, -0.007967708632349968, -0.03500732406973839, 0.008905332535505295, 0.007792004384100437, 0.011932531371712685, 0.05897797271609306, -0.0007354290573857725, -0.039223793894052505, 0.010213920846581459, 0.05243812873959541, -0.038344044238328934, -0.04228958860039711, -0.040818583220243454, -0.016978494822978973, 0.041443098336458206, 0.012510833330452442, -0.016557421535253525, -0.07781840115785599, 0.0026124310679733753, -0.00681748753413558, 0.04647905379533768, -0.043181162327528, 0.020285215228796005, 0.030044106766581535, 0.05089806392788887, 0.03722216188907623, -0.02077566832304001, -0.0024461436551064253, -0.09587405622005463, -0.0009424828458577394, -0.053047168999910355, -0.06851851940155029, 0.014756164513528347, -0.03827102854847908, -0.02707539312541485, -0.022714093327522278, -0.03338012099266052, 0.03044978529214859, 0.034322768449783325, 0.03769102320075035, -0.03771866858005524, -0.07225163280963898, 0.023464133962988853, 0.07949250191450119, 0.06064247339963913, -0.02167150378227234, -0.07632996886968613, -0.03093048557639122, ...]",1.844232,4.491210,19,-3.417307,-27.026424,-39.689732,⚕️ Medical Ethics,NaN,NaN,NaN,NaN,NaN
2,This House believes that we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants.,"Irregular migrants are those who enter another country without official\npermission. In response to border crossings by irregular migrants, several\ncountries adopt ‘pull-back’ measures, cooperating with migrants’ countries of\norigin to stop them from exiting (e.g. providing support for border controls).",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants,"[0.00870150700211525, -0.06843803077936172, -0.003463117405772209, 0.025157984346151352, 0.017507191747426987, -0.0303875170648098, -0.02059384435415268, 0.05743293836712837, 0.001368101336993277, 0.04095758870244026, 0.012575137428939342, -0.06718512624502182, -0.0037729800678789616, 0.0013310132781043649, 0.014933854341506958, 0.02128373645246029, 0.03513993322849274, -0.029221875593066216, -0.026073575019836426, -0.03702264651656151, 0.03800711780786514, -0.039052922278642654, 0.022951491177082062, -0.041488636285066605, 0.008226659148931503, -0.03117653913795948, -0.030418075621128082, 0.03691736236214638, -0.06780695915222168, 0.01721208728849888, -0.021600807085633278, 0.00027380892424844205, 0.02528715878725052, -0.04632057622075081, 0.005294193048030138, 0.06070960685610771, -0.015746744349598885, -0.051718179136514664, 0.05833754315972328, -0.013057909905910492, -0.030223308131098747, 0.028464946895837784, -0.023631641641259193, -0.028492162004113197, 0.0023581762798130512, 0.01808883808553219, -0.002124636899679899, 0.05886312201619148, -0.009186247363686562, 0.013616736978292465, -0.007131893653422594, 0.03140971437096596, 0.013715488836169243, -0.03529708459973335, -0.04912465065717697, -0.0009523194748908281, -0.018910903483629227, 0.06387355923652649, -0.030045751482248306, -0.014989549294114113, 0.004238853696733713, 0.016776930540800095, 0.012400010600686073, -0.03233559429645538, -0.011438199318945408, -0.01447566132992506, -0.01585332676768303, 0.02054649218916893, 0.026149284094572067, -0.0886291116476059, -0.0044746920466423035, -0.07485630363225937, 0.07267636805772781, -0.03504190966486931, 0.021445050835609436, 0.006780571769922972, 0.03294910117983818, 0.0629894882440567, -0.06639498472213745, -0.0009971009567379951, -0.00885708536952734, 0.015707779675722122, -0.028746945783495903, -0.010558170266449451, -0.036554064601659775, -0.0003507430083118379, -0.010836039669811726, -0.026925723999738693, -0.035643320530653, -0.006883218418806791, -0.028850719332695007, 0.04299624636769295, 0.033092204481363297, -0.04194900020956993, -0.01587717793881893, 0.1139565259218216, 0.007108272984623909, 0.024178646504878998, -0.035638563334941864, -0.04477965831756592, ...]",7.487733,0.981564,3,4.948655,-29.265728,-2.006341,🏛️ International Relations,NaN,NaN,NaN,NaN,NaN
3,"This House believes that we regret self-denial in religion (e.g. celibacy, fasting, giving up material or sensory pleasures).",NaN,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"we regret self-denial in religion (eg celibacy, fasting, giving up material or sensory pleasures)","[-0.03781802952289581, 0.033481165766716, 0.05631212145090103, -0.04665393754839897, 0.030571291223168373, 0.03060401789844036, -0.03684534505009651, 0.03794411942362785, -0.05032408982515335, -0.03707517310976982, -0.007899381220340729, -0.04870051518082619, 0.01471886970102787, -0.023229259997606277, -0.025252673774957657, 0.01097631175071001, 0.07246993482112885, -0.022962549701333046, 0.02120521478354931, -3.6210498365107924e-05, 0.03623451665043831, -0.05870863050222397, -0.014353977516293526, -0.03905477374792099, -0.016974221915006638, -0.03164180368185043, -0.07602657377719879, 0.00576959690079093, -0.03735310956835747, 0.052262138575315475, -0.0021347496658563614, -0.032232705503702164, 0.03518468141555786, 0.010982917621731758, 0.01443720143288374, 0.014075432904064655, 0.07856179773807526, 0.009881856851279736, -0.0310727097094059, 0.03203405812382698, -0.004914592020213604, 0.036556679755449295, -0.033561546355485916, -0.04233436658978462, 0.02899523451924324, 0.05726257711648941, 0.027067964896559715, 0.03896244987845421, 0.02377924695611, -0.012006774544715881, 0.007756521925330162, -0.012484170496463776, -0.005428309552371502, -0.006512461230158806, -0.023833636194467545, 0.07395032048225403, -0.039217352867126465, 0.009990389458835125, -0.05294599384069443, 0.011777274310588837, -0.029969284310936928, -0.013530579395592213, -0.019468260928988457, -0.07512820512056351, -0.03675688058137894, 0.10732477903366089, 0.049394700676202774, 0.026176564395427704, -0.030542870983481407, -0.07802857458591461, 0.030975764617323875, -0.03700203076004982, 0.008385596796870232, -0.044088635593652725, 0.031368378549814224, 0.018230661749839783, 0.007297438569366932, 0.08184492588043213, 0.03150804713368416, -0.05648035556077957, -0.06362149864435196, 0.03375725448131561, -0.02628646045923233, -0.0362667590379715, -0.031946346163749695, -0.0007111296290531754, -0.06358709186315536, -0.024333328008651733, -0.04770407825708389, -0.04663310572504997, -0.04786740615963936, 0.011825649999082088, 0.01031561754643917, -0.013282595202326775, -0.019841963425278664, -0.010743995197117329, 0.035443808883428574, 0.07772501558065414, -0.05338028818368912, 0.017505932599306107, ...]",-10.493422,-3.085940,4,-19.872459,8.277333,29.218498,🙏 Religious Doctrine,NaN,NaN,NaN,NaN,NaN
4,"This House believes that, in multireligious states, schools should teach integrated religious education instead of separated religious education.","In ‘integrated religious education’, all students are taught material\nencompassing many major religions.\n\nIn ‘separated religious education’, students study different religions in\ndistinct classrooms (i.e. Catholic students attend Catholic class, Buddhist\nstudents attend Buddhist class, etc.).",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,", in multireligious states, schools should teach integrated religious education instead of separated religious education","[-0.07520031929016113, -0.03346019983291626, 0.06300149857997894, -0.013544010929763317, 0.005637470632791519, 0.04309633746743202, -0.06426656246185303, 0.05444727838039398, -0.025169309228658676, -0.02944754809141159, -0.015468250028789043, -0.032316047698259354, -0.01501105260103941, -0.006567661184817553, -0.062408387660980225, 0.010683541186153889, 0.0011690518585965037, -0.015708565711975098, -0.034836482256650925, -0.04100259765982628, 0.023420879617333412, -0.05665368214249611, -0.0037485540378838778, -0.005746413953602314, 0.08521213382482529, -0.05758580192923546, -0.04743649438023567, -0.03723529353737831, 0.019359180703759193, 0.007024390157312155, -0.03344457969069481, 0.02769320458173752, -0.014369726181030273, -0.040499478578567505, 0.02861480973660946, 0.019999805837869644, 0.015948209911584854, 0.0006641345680691302, 0.022074086591601372, -0.05318406969308853, -0.005211321637034416, 0.026106735691428185, -0.052494216710329056, -0.01786131039261818, 0.024853788316249847, 0.05995015799999237, 0.01337475422769785, 0.029842080548405647, -0.025944240391254425, -0.01554922852665186, 0.012158305384218693, -0.010886283591389656, -0.016360778361558914, -0.002266588155180216, 0.02398047037422657, 0.03760286048054695, -0.008035949431359768, -0.055095117539167404, 0.017622990533709526, 0.01159000489860773, 0.008484185673296452, 0.011263301596045494, 0.004175093956291676, -0.06071307137608528, 0.029846874997019768, 0.008960277773439884, 0.05101820081472397, -0.009726595133543015, -0.03735775500535965, 0.00921248272061348, -0.006142635829746723, 0.007486921269446611, -0.06690531224012375, -0.03949689865112305, 0.039431631565093994, 0.021605489775538445, 0.009596262127161026, 0.017230993136763573, -0.04003938287496567, 0.025672679767012596, -0.039553720504045486, 0.03464031219482422, -0.019456906244158745, -0.04437463358044624, -0.010899335145950317, -0.025988634675741196, -0.04247540980577469, 0.004260201007127762, -0.005645073018968105, 0.020099977031350136, -0.007241388782858849, 0.006596441380679607, -0.04178798198699951, -0.01944931410253048, 0.09613628685474396, 0.03908085078001022, 0.10429921001195908, 0.046262241899967194, -0.02572765201330185, -0.06777990609407425, ...]",-2.238666,-4.310638,4,-6.437295,-7.297156,38.905334,🙏 Religious Doctrine,NaN,NaN,NaN,NaN,NaN

### Sidequest: average speaks across all motions by tournament

This is necessary for us to make inferences based on speaker scores, i.e. we need to know if speaks are really absolutely averaged around 75 in tournaments. 

If so, we can say that a motion with a 73 speaks avg. is more difficult. However, if that tournament's whole average is 73, then it's just normal in difficulty.

In [440]:
non_null_speaks = df_with_emb2[df_with_emb2['speaks'] > 0]

In [441]:
avg_speaks_by_tournament = non_null_speaks.groupby('Tournament')['avg_speaks'].mean()
px.histogram(x=avg_speaks_by_tournament)

In [442]:
sorted_avg_speaks_by_tournament = avg_speaks_by_tournament.sort_values(ascending=False)
sorted_avg_speaks_by_tournament

Tournament
HWS Round Robin 2025                                                 80.462500
HWS Round Robin 2023                                                 80.412500
Krabi ABP 2024                                                       77.414583
                                                                       ...
Southern Africa National Universities Debating Championships 2021    75.146944
Chennai WUDC 2014                                                    74.979085
Pan African Universities Debating Championship 2022                  74.669502
Name: avg_speaks, Length: 26, dtype: float64

In [443]:
sorted_avg_speaks_by_tournament.index[0]

'HWS Round Robin 2025'

In [444]:
non_null_speaks[non_null_speaks['Tournament'] == sorted_avg_speaks_by_tournament.index[0]]

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding,pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,avg_speaks,tournament_avg_speaks,difficulty,z,imbalance
69,"This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms.",NaN,HWS Round Robin 2025,https://hwsrr2025.calicotab.com/_,Round 1-A,P,4.0,12.0,36.0,9.0,12.0,15.0,2579.0,3.0,5.0,0.0,4.0,4.0,8.0,4.0,5.0,7.0,NaN,NaN,NaN,NaN,Round 1-B,P,2025.0,prefers,"progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms","[-0.04474251717329025, -0.004065655637532473, 0.05996498838067055, 0.008644568733870983, -0.007011274341493845, 0.011290451511740685, -0.004182219505310059, 0.05629994347691536, 0.0020272191613912582, 0.039398301392793655, -0.0759798064827919, -0.0485001802444458, 0.00040542014176025987, 0.004090204369276762, -0.021051878109574318, 0.016836615279316902, 0.00407697819173336, -0.022169506177306175, 0.029943808913230896, -0.029862109571695328, 0.015477783977985382, -0.09306123107671738, -0.035450324416160583, 0.048231251537799835, -0.022921523079276085, -0.028681974858045578, -0.05045555531978607, 0.011173592880368233, -0.034840308129787445, 0.031014733016490936, -0.00752257788553834, 0.003588458988815546, -0.005648801103234291, -0.017575422301888466, 0.014086262322962284, 0.056543610990047455, 0.030263198539614677, -0.07874459773302078, -0.040042366832494736, 0.05209708958864212, -0.07042471319437027, 0.026105031371116638, -0.056576162576675415, -0.08247511833906174, 0.011218518018722534, 0.05781446397304535, -0.0042349109426140785, 0.04116575047373772, 0.011330388486385345, -0.019846968352794647, 0.028829822316765785, 0.0942394807934761, -0.06338746100664139, 0.0001717444829409942, -0.0033651988487690687, -0.005127858370542526, -0.01699282042682171, 0.025756575167179108, -0.002504686824977398, -0.006218257825821638, -0.01847682148218155, -0.0016476305900141597, -0.014110362157225609, -0.05239642783999443, -0.03773193061351776, -0.0163528174161911, 0.005960375536233187, 0.007299361284822226, -0.031734444200992584, -0.06116301566362381, -0.02043948881328106, 0.055433761328458786, 0.02356766350567341, 0.02528057061135769, 0.03004973754286766, 0.02280295081436634, 0.026354683563113213, 0.07517064362764359, 0.009083493612706661, 0.010859033092856407, -0.009917096234858036, 0.004231906961649656, 0.04809319227933884, -0.0141496816650033, 0.01827203296124935, -0.036305636167526245, -0.06076575070619583, -0.0025474142748862505, -0.00021798338275402784, 0.047366492450237274, 0.010274565778672695, 0.06182378903031349, -0.01569688692688942, -0.09787403792142868, 0.055771756917238235, 0.04966484382748604, 0.03248277306556702, 0.029739797115325928, 0.028404174372553825, -0.005929764825850725, ...]",-4.055677,-2.032293,17,-11.966599,1.190116,-9.606944,📢 Media Influence,80.59375,80.4625,NaN,NaN,NaN
70,This house regrets the Indian Premier League.,"The Indian Premier League (IPL) is a domestic cricket league in India. Since\nits inception in 2007, it has grown to become the largest cricket league in\nthe world, attracting sponsorship that exceeds that of most national teams.\n\nTraditionally, cricket competition has been dominated by international events\nand national teams touring other countries, and has involved games lasting\neither five days or one day. The IPL popularized large-scale domestic cricket\nleagues, and is played in a shorter, three-hour format of cricket called\nTwenty20 (T20). Teams are allowed up to 4 international (non-Indian) players\nin their teams. Additionally, the IPL usually lasts 3-4 months, taking up a\nsignificant portion of the annual cricket calendar.",HWS Round Robin 2025,https://hwsrr2025.calicotab.com/_,Round 2-A,P,4.0,2.0,2.0,5.0,0.0,5.0,2574.0,9.0,23.0,5.0,21.0,3.0,5.0,8.0,10.0,26.0,NaN,NaN,NaN,NaN,Round 2-B,P,2025.0,regrets,indian premier league,"[0.007603739388287067, 0.012494048103690147, -0.01023069303482771, 0.0025290455669164658, 0.019428802654147148, 0.0654008686542511, -0.01198536716401577, -0.034474145621061325, -0.03173413500189781, -0.021228905767202377, -0.02551998384296894, -0.03130896016955376, -0.00629404978826642, -0.03958302363753319, -0.03510182723402977, 0.0440652072429657, -0.013201489113271236, -0.041421908885240555, -0.07305104285478592, -0.04813327640295029, 0.009853774681687355, -0.00698023522272706, 0.019479412585496902, -0.014230377040803432, 0.026606813073158264, 0.0279611274600029, -0.013555650599300861, -0.021952880546450615, -0.07174386084079742, 0.016710655763745308, 0.07991145551204681, 0.04257602244615555, 0.05295657366514206, 0.06786946207284927, 0.008312906138598919, 0.0076124039478600025, 0.002630719682201743, -0.0005426148418337107, 0.07221966981887817, -0.009853018447756767, -0.002957922639325261, 0.016824044287204742, -0.02138856053352356, -0.040358249098062515, -0.015368746593594551, 0.044513627886772156, 0.015380137600004673, -0.029689846560359, 0.027500618249177933, -0.06463290005922318, 0.031097760424017906, -0.0017963266000151634, -0.07583197951316833, -0.07006162405014038, -0.01004223432391882, -0.02530958130955696, 0.009695084765553474, -0.08159033209085464, -0.027197228744626045, 0.0020736143924295902, 0.009458010084927082, -0.018207650631666183, -0.034135106950998306, -0.0364392064511776, -0.02728419378399849, 0.0053238472901284695, 0.010932587087154388, 0.03028418868780136, -0.010403850115835667, -0.014833135530352592, -0.007629848085343838, -0.007154810708016157, -0.023479031398892403, -0.00520566338673234, -0.005489639937877655, -0.013740509748458862, 0.043159279972314835, 0.02753988467156887, -0.07021155953407288, -0.053231388330459595, -0.04877312853932381, 0.01934678852558136, 0.019132407382130623, -0.025174051523208618, -0.021022288128733635, -0.015499167144298553, 0.007197429891675711, -0.04988168925046921, -0.025406835600733757, -0.0509263314306736, -0.03131711110472679, -0.03424123674631119, -0.04701122269034386, -0.025185605511069298, -0.046129245311021805, 0.08628810197114944, 0.00975022092461586, 0.059048958122730255, -0.03746967762708664, -0.07082244008779526, ...]",0.761255,-2.565107,14,7.291514,-8.524531,-48.417461,⚽ Professional Sports,80.43750,80.4625,NaN,NaN,NaN
71,This house believes that breaking up large meat companies is in the interests of animal welfare.,NaN,HWS Round Robin 2025,https://hwsrr2025.calicotab.com/_,Round 3-A,P,4.0,6.0,10.0,9.0,8.0,9.0,2544.0,7.0,15.0,9.0,9.0,5.0,13.0,0.0,6.0,18.0,NaN,NaN,NaN,NaN,Round 3-B,P,2025.0,believes,breaking up large meat companies is in the interests of animal welfare,"[-0.03787577897310257, -0.024296151474118233, 0.03693372756242752, -0.06150189787149429, 0.018666867166757584, 0.023816321045160294, -0.025736363604664803, 0.04322826862335205, -0.04959379509091377, 0.013446486555039883, 0.005591185297816992, -0.023509783670306206, -0.05292728915810585, 0.0054224818013608456, -0.03898325935006142, -0.03629282861948013, 0.014415762387216091, 0.03134606033563614, -0.0031208780128508806, -0.022928770631551743, 0.016422191634774208, -0.055385611951351166, -0.047542326152324677, -0.005707086995244026, 0.02861592546105385, -0.05026968941092491, -0.07940403372049332, -0.01104910857975483, -0.020783189684152603, -0.008083987981081009, -0.03754151239991188, 0.019321030005812645, 0.010710030794143677, -0.023096315562725067, -0.0068938578478991985, 0.037471503019332886, 0.027501825243234634, -0.025208141654729843, 0.003386592259630561, -0.029153622686862946, -0.06577273458242416, 0.01773320697247982, -0.014013463631272316, -0.0017828859854489565, 0.01894533820450306, 0.01145167089998722, 0.03251952677965164, 0.015317603945732117, 0.027401311323046684, -0.04730495810508728, 0.025025350973010063, 0.01116696186363697, -0.053571198135614395, -0.017007796093821526, -0.004168452229350805, -0.03230803832411766, -0.010430165566504002, -0.008911182172596455, 0.009612014517188072, 0.011482571251690388, -0.05252177640795708, 0.005490034818649292, -0.005486806854605675, 0.00858973152935505, 0.012234344147145748, 0.02669510990381241, 0.07298266887664795, 0.021005040034651756, 0.014323755167424679, -0.09330561757087708, -0.016966721042990685, -0.016878945752978325, 0.028069347143173218, 0.007084593176841736, 0.02963702194392681, -0.0503687746822834, -0.01687055639922619, 0.055291369557380676, 0.0358479842543602, 0.018302256241440773, 0.029707856476306915, -0.01749126799404621, 0.02320178411900997, -0.0060324701480567455, 0.0221937894821167, -0.010222875513136387, -0.05511441454291344, -0.05187895894050598, -0.08384039998054504, 0.03641925007104874, -0.06842593848705292, 0.02187555842101574, 0.05430670455098152, -0.04164277762174606, 0.06619313359260559, 0.03661377727985382, -0.018143098801374435, 0.048140786588191986, -0.02717248722910881, -0.048507701605558395, ...]",5.165279,5.125653,12,17.426075,-6.435878,-25.432373,🛑 Economic Regulation,79.50000,80.4625,NaN,NaN,NaN
72,This house prefers a world where genius only develops after adulthood (so that there are no child prodigies).,NaN,HWS Round Robin 2025,https://hwsrr2025.calicotab.com/_,Round 4-A,P,4.0,8.0,22.0,12.0,6.0,8.0,2592.0,7.0,17.0,6.0,7.0,5.0,13.0,5.0,4.0,4.0,NaN,NaN,NaN,NaN,Round 4-B,P,2025.0,prefers,a world where genius only develops after adulthood (so that there are no child prodigies),"[-0.043584320694208145, 0.02300327457487583, 0.025124406442046165, 0.03347980976104736, -0.01141364499926567, 0.04087560996413231, 0.023581907153129578, -0.001647909521125257, -0.01746019348502159, -0.0034884396009147167, -0.021678710356354713, -0.03342121094465256, 0.0461844801902771, -0.008998271077871323, -0.008176255039870739, 0.03794894367456436, 0.08113565295934677, -0.042413994669914246, -0.028829151764512062, -0.007117045111954212, 0.10275322943925858, -0.08050312846899033, -0.06617997586727142, 0.019664259627461433, -0.023950712755322456, -0.05868687480688095, -0.022704914212226868, -0.010604129172861576, -0.0011734480503946543, -0.01443486101925373, 0.041406918317079544, 0.054262615740299225, -0.05266198888421059, 0.03838663175702095, 0.006013611331582069, -0.006636945530772209, 0.016144949942827225, -0.010266940109431744, 0.0061936452984809875, 0.033168014138936996, -0.003707613330334425, 0.007339756470173597, -0.007856919430196285, 0.0023791140411049128, 0.07061006128787994, 0.028376806527376175, -0.0066050197929143906, 0.045777786523103714, 0.01967734843492508, -0.06488308310508728, 0.011972447857260704, -0.03435654565691948, -0.038359664380550385, 0.0716610699892044, -0.042194947600364685, 0.008998673409223557, -0.023971209302544594, 0.029162628576159477, 0.00040096743032336235, 0.03758009150624275, -0.05539184436202049, -0.03859061375260353, 0.02224542573094368, 0.022982407361268997, 0.024135028943419456, 0.02671070210635662, 0.04725152626633644, 0.07158944755792618, -0.030458854511380196, -0.09702412784099579, 0.049739547073841095, -0.0034193815663456917, 0.0519857294857502, 0.0030813650228083134, 0.035461440682411194, 0.013305787928402424, -0.03941856697201729, 0.05149431526660919, 0.05852842703461647, -0.01695978082716465, -0.038760535418987274, -0.02060081623494625, -0.03854904696345329, -0.011251451447606087, -0.028023913502693176, 0.05941321700811386, -0.009906400926411152, 0.016594048589468002, -0.016886327415704727, -0.0409565307199955, 0.03604493290185928, -0.026220789179205894, -0.015657082200050354, 0.006834269501268864, -0.021245716139674187, 0.007668579462915659, -0.04817379638552666, 0.09747963398694992, -0.06487792730331421, 0.03749639540910721, ...]",-8.537681,0.247332,7,-3.696568,34.162636,32.755871,🤔 Hypothetical Worlds,81.00000,80.4625,NaN,NaN,NaN
73,"This house believes that East African national governments should prioritize investments in agriculture (e.g., irrigation, R&D, and inputs like fertilizer) over accelerating industrialization (e.g., building infrastructure, export promotion).",NaN,HWS Round Robin 2025,https://hwsrr2025.calicotab.com/_,Round 5-A,P,4.0,12.0,36.0,9.0,9.0,18.0,2585.0,3.0,3.0,2.0,4.0,3.0,5.0,2.0,6.0,12.0,NaN,NaN,NaN,NaN,Round 5-B,P,2025.0,believes,"east african national governments should prioritize investments in agriculture (eg, irrigation, r&d, and inputs like fertilizer) over accelerating industrialization (eg, building infrastructure, export promotion)","[-0.006614001467823982, 0.005583884194493294, 0.03191974759101868, -0.015895619988441467, 0.04280254244804382, 0.057063449174165726, -0.013448561541736126, 0.07842831313610077, -0.02507953532040119, 0.016652584075927734, -0.04235588014125824, -0.02705957554280758, 0.04485463723540306, 0.00551289739087224, 0.0351669117808342, -0.004975953605026007, 0.07104223966598511, -0.012694371864199638, -0.058313824236392975, -0.06585116684436798, 0.028798017650842667, -0.0688476487994194, -0.05663911998271942, 0.03865749016404152, 0.016423674300312996, -0.058727361261844635, -0.020886484533548355, -0.01704181171953678, -0.01306677795946598, 0.027338841930031776, 0.015194450505077839, 0.00911910180002451, 0.03903580456972122, 0.0061274925246834755, -0.016897158697247505, 0.060502100735902786, 0.0629434585571289, -0.023823270574212074, -0.005842528771609068, -0.03222215548157692, -0.01111352164298296, 0.03213648870587349, -0.026218231767416, 0.04528651386499405, -0.002551525365561247, 0.01719251275062561, 0.021645912900567055, 0.0165172778069973, 0.02822604961693287, -0.0012361417757347226, 0.030733291059732437, -0.09668456017971039, -0.024608777835965157, -0.00834582932293415, -0.021817730739712715, 0.01979430578649044, 0.015674401074647903, -0.01017587911337614, -0.036096926778554916, -0.01773996278643608, -0.03035283461213112, -0.05141853541135788, 0.007801152765750885, -0.01295736338943243, 0.04456888884305954, 0.02182397060096264, 0.007556259632110596, 0.03310448303818703, -0.04564940929412842, -0.054443903267383575, -0.07258909940719604, 0.016207091510295868, 0.022349072620272636, -0.015964491292834282, -0.0212390199303627, 0.0017152123618870974, 0.011602788232266903, 0.030776239931583405, -0.01703428104519844, -0.0013258183607831597, -0.003618152579292655, 0.0018332323525100946, -0.013558655977249146, -0.013392634689807892, -0.06274019926786423, 0.010981712490320206, -0.05456264317035675, 0.004187176935374737, -0.06699958443641663, 0.0037698429077863693, -0.0286050233989954, 0.018532492220401764, 0.05025104060769081, -0.011701631359755993, 0.0042116655968129635, 0.09479273855686188, 0.004054184537380934, 0.011105786077678204, 0.022347699850797653, -0.0625004768371582, ...]",8.295903,-6.142619,0,39.881508,-1.878370,-0.133250,⚖️ Government Policy,80.78125,80.4625,NaN,NaN,NaN

In [445]:
df_with_emb2['tournament_avg_speaks'] = df_with_emb2['Tournament'].map(avg_speaks_by_tournament)
df_with_emb2[['Tournament', 'tournament_avg_speaks']]

,Tournament,tournament_avg_speaks
0,Jakarta Australasian Intervarsity Debate Championships 2024,NaN
1,Jakarta Australasian Intervarsity Debate Championships 2024,NaN
2,Jakarta Australasian Intervarsity Debate Championships 2024,NaN
...,...,...
1075,Vietnam World Universities Debating Championships 2024,76.741615
1076,Vietnam World Universities Debating Championships 2024,76.741615
1077,Vietnam World Universities Debating Championships 2024,76.741615

### Average speaks

In [446]:
df_with_emb2['speaks'].value_counts()

speaks
12379.0    2
2575.0     2
2585.0     2
          ..
54982.0    1
54557.0    1
44306.0    1
Name: count, Length: 189, dtype: int64

In [448]:
reliable_with_difficulty = df_with_emb2[(df_with_emb2['avg_speaks'] > 0) & (df_with_emb2['n'] > 4)]

In [449]:
px.histogram(x=reliable_with_difficulty['avg_speaks'], nbins=20)

In [452]:
reliable_with_difficulty.sort_values(by='avg_speaks', ascending=False)[['avg_speaks', 'Motion']]

,avg_speaks,Motion
336,77.651316,THBT cleantech and climate tech investors should prioritize investing in green startups in developing nations over those in developed nations
888,77.600000,"In countries with competitive national elections, THS the use of city council dismissals"
887,77.562500,THBT the international community's attempts to ostracise Israel have done more harm than good
...,...,...
137,74.194118,"THW make the receipt of welfare payments to raise children conditional on the use of long-term, but reversible, contraception"
1019,74.062500,THP afterlife A over Afterlife B
1022,74.039062,THBT globalization has failed

In [453]:
reliable_with_difficulty.loc[:, 'diff_avg_speaks'] = reliable_with_difficulty['avg_speaks'] - reliable_with_difficulty['tournament_avg_speaks']
reliable_with_difficulty[['Tournament', 'avg_speaks', 'tournament_avg_speaks', 'diff_avg_speaks']]

/var/folders/4t/nd2tlhnx0jlf0zb72mtxv19w0000gn/T/ipykernel_39771/613685175.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Tournament,avg_speaks,tournament_avg_speaks,diff_avg_speaks
45,Kumamoto North East Asia Debating Championship 2024,75.894231,76.060897,-0.166667
46,Kumamoto North East Asia Debating Championship 2024,76.384615,76.060897,0.323718
47,Kumamoto North East Asia Debating Championship 2024,75.788462,76.060897,-0.272436
...,...,...,...,...
1065,Vietnam World Universities Debating Championships 2024,77.207192,76.741615,0.465577
1066,Vietnam World Universities Debating Championships 2024,76.672945,76.741615,-0.068670
1067,Vietnam World Universities Debating Championships 2024,76.920139,76.741615,0.178524

In [454]:
px.histogram(x=reliable_with_difficulty['diff_avg_speaks'])

In [458]:
reliable_with_difficulty.sort_values(by='diff_avg_speaks', ascending=False)[['Motion', 'avg_speaks', 'tournament_avg_speaks', 'diff_avg_speaks']]

,Motion,avg_speaks,tournament_avg_speaks,diff_avg_speaks
1018,THS the decision by the Government of Kenya to lift the ban on GMOs.,75.593750,74.669502,0.924248
239,THB the US and Canada should ban Mandatory Binding Arbitration.,77.368750,76.558333,0.810417
659,This House Predicts that the Judicial Reform will lead to Netanyahu's Exit from Office,77.049342,76.275970,0.773372
...,...,...,...,...
357,This house opposes the norm of African elites outsourcing their ambitions to outsiders,75.587500,76.566250,-0.978750
723,This House Would break up the ABCDs,74.304054,75.345948,-1.041894
777,THR the rise of Investor-State dispute clauses in multilateral trade treaties,75.055556,76.110654,-1.055099

In [460]:
import numpy as np

def sigmoid_difficulty(x: float) -> float:
    k = 5
    a = 0
    b = -2 #FIXME: very arbitrary
    return k / (1 + np.exp(a + x * b))

reliable_with_difficulty.loc[:, 'difficulty'] = sigmoid_difficulty(-reliable_with_difficulty['diff_avg_speaks'])

px.histogram(reliable_with_difficulty['difficulty'])

In [461]:
reliable_with_difficulty[['Motion', 'tournament_avg_speaks', 'avg_speaks', 'diff_avg_speaks', 'difficulty']].sort_values(by='difficulty', ascending=False)

,Motion,tournament_avg_speaks,avg_speaks,diff_avg_speaks,difficulty
777,THR the rise of Investor-State dispute clauses in multilateral trade treaties,76.110654,75.055556,-1.055099,4.459452
723,This House Would break up the ABCDs,75.345948,74.304054,-1.041894,4.446587
357,This house opposes the norm of African elites outsourcing their ambitions to outsiders,76.566250,75.587500,-0.978750,4.381311
...,...,...,...,...,...
659,This House Predicts that the Judicial Reform will lead to Netanyahu's Exit from Office,76.275970,77.049342,0.773372,0.877785
239,THB the US and Canada should ban Mandatory Binding Arbitration.,76.558333,77.368750,0.810417,0.825450
1018,THS the decision by the Government of Kenya to lift the ban on GMOs.,74.669502,75.593750,0.924248,0.680248

### Difficulty by theme

In [514]:
pd.set_option('display.max_columns', None)
by_category_with_difficulty = reliable_with_difficulty.groupby('category')

avg_difficulty_by_category = by_category_with_difficulty['difficulty']
px.scatter(x=reliable_with_difficulty['difficulty'], y=reliable_with_difficulty['category'],labels={'x': 'Median difficulty', 'y': 'Theme'}, width=1000, height=600, title="Difficulty x Theme").show()

### Difficulty x motion type

In [469]:
by_category_with_difficulty = reliable_with_difficulty.groupby('Motion Type')

avg_difficulty_by_category = by_category_with_difficulty['difficulty'].median().sort_values(ascending=True)
px.bar(avg_difficulty_by_category, width=1000, height=600).show()

### Difficulty x Year

In [524]:
by_year_with_difficulty = reliable_with_difficulty.groupby('Year')

avg_difficulty_by_year = by_year_with_difficulty['difficulty'].median().sort_values(ascending=True)
px.scatter(avg_difficulty_by_year, width=1000, height=600).show()

### Bring results in

In [470]:
df_with_emb2.loc[reliable_with_difficulty.index, 'difficulty'] = reliable_with_difficulty['difficulty']

## Motion balance

In [471]:
with_results = df_with_emb2[(df_with_emb2['n'] >= 10) & (df_with_emb2['sum_og'] > 0)] # only in prelim rounds (technically should check if any of sum_side > 0)

In [472]:
motion = with_results.iloc[0]
motion

Motion                            THR the decline of home cooking
Info Slide                                                    NaN
Tournament    Kumamoto North East Asia Debating Championship 2024
                                     ...
difficulty                                               2.912851
z                                                       43.656297
imbalance                               extremely strong evidence
Name: 45, Length: 44, dtype: object

In [473]:
assert motion[['sum_og', 'sum_oo', 'sum_cg', 'sum_co']].sum() == motion['n'] * 6, "Does not compute."

In [474]:
import numpy as np 
N = motion['n']
mu = np.array([1.5, 1.5, 1.5])

In [475]:
x_bar = motion[['sum_og', 'sum_oo', 'sum_cg']].to_numpy() / N

In [476]:
var_og = motion['sum_og_og'] / N - (motion['sum_og'] / N) ** 2
var_oo = motion['sum_oo_oo'] / N - (motion['sum_oo'] / N) ** 2
var_cg = motion['sum_cg_cg'] / N - (motion['sum_cg'] / N) ** 2
var_co = motion['sum_co_co'] / N - (motion['sum_co'] / N) ** 2

var_og, var_oo, var_cg, var_co

(np.float64(0.24852071005917198),
 np.float64(0.4023668639053257),
 np.float64(1.3609467455621307),
 np.float64(1.3609467455621305))

In [477]:
cov_og_oo = motion['sum_og_oo'] / N - (motion['sum_og'] / N) * (motion['sum_oo'] / N)
cov_og_cg = motion['sum_og_cg'] / N - (motion['sum_og'] / N) * (motion['sum_cg'] / N)
cov_og_co = motion['sum_og_co'] / N - (motion['sum_og'] / N) * (motion['sum_co'] / N)

cov_oo_cg = motion['sum_oo_cg'] / N - (motion['sum_oo'] / N) * (motion['sum_cg'] / N)
cov_oo_co = motion['sum_oo_co'] / N - (motion['sum_oo'] / N) * (motion['sum_co'] / N)

cov_cg_co = motion['sum_cg_co'] / N - (motion['sum_cg'] / N) * (motion['sum_co'] / N)

print("OG - OO: ", cov_og_oo)
print("OG | CG: ", cov_og_cg)
print("OG \ CO: ", cov_og_co)

print("OO / CG: ", cov_oo_cg)
print("OO | CO: ", cov_oo_co)

print("CG - CO: ", cov_cg_co)

OG - OO:  0.0591715976331364
OG | CG:  0.005917159763313862
OG \ CO:  -0.3136094674556211
OO / CG:  -0.390532544378698
OO | CO:  -0.07100591715976279
CG - CO:  -0.9763313609467454

In [478]:
# og-og, og-oo, og-cg 
# oo-og, oo-oo, oo-cg
# cg-og, cg-oo, cg-cg

V = np.array([
    [var_og, cov_og_oo, cov_og_cg],
    [cov_og_oo, var_oo, cov_oo_cg],
    [cov_og_cg, cov_oo_cg, var_cg],
])
V

array([[ 0.24852071,  0.0591716 ,  0.00591716],
       [ 0.0591716 ,  0.40236686, -0.39053254],
       [ 0.00591716, -0.39053254,  1.36094675]])

In [479]:
V_inv = np.linalg.inv(V)
V_inv

array([[ 4.24210526, -0.88947368, -0.27368421],
       [-0.88947368,  3.63120301,  1.04586466],
       [-0.27368421,  1.04586466,  1.03609023]])

In [480]:
xdiff = x_bar - mu
xdiff, xdiff.shape

(array([np.float64(-0.03846153846153855), np.float64(1.0384615384615383),
        np.float64(-0.34615384615384626)], dtype=object),
 (3,))

In [481]:
xdiff.T, xdiff.T.shape

(array([np.float64(-0.03846153846153855), np.float64(1.0384615384615383),
        np.float64(-0.34615384615384626)], dtype=object),
 (3,))

In [482]:
z = N * xdiff.T @ V_inv @ xdiff
z

np.float64(43.65629699248114)

In [483]:
# sanity check
motion[['sum_og', 'sum_oo', 'sum_cg', 'sum_co']] / int(motion['n']), motion['n']

(sum_og    1.461538
 sum_oo    2.538462
 sum_cg    1.153846
 sum_co    0.846154
 Name: 45, dtype: object,
 np.float64(13.0))

In [484]:
data = [
    [motion['sum_og'] / motion['n'], motion['sum_oo'] / motion['n']],
    [motion['sum_cg'] / motion['n'], motion['sum_co'] / motion['n']]
]

px.imshow(data, text_auto=True)

### Now put it into a function

In [485]:
def compute_z(motion): 
    import numpy as np 
    N = motion['n']
    mu = np.array([1.5, 1.5, 1.5])

    x_bar = motion[['sum_og', 'sum_oo', 'sum_cg']].to_numpy() / N

    var_og = motion['sum_og_og'] / N - (motion['sum_og'] / N) ** 2
    var_oo = motion['sum_oo_oo'] / N - (motion['sum_oo'] / N) ** 2
    var_cg = motion['sum_cg_cg'] / N - (motion['sum_cg'] / N) ** 2

    cov_og_oo = motion['sum_og_oo'] / N - (motion['sum_og'] / N) * (motion['sum_oo'] / N)
    cov_og_cg = motion['sum_og_cg'] / N - (motion['sum_og'] / N) * (motion['sum_cg'] / N)

    cov_oo_cg = motion['sum_oo_cg'] / N - (motion['sum_oo'] / N) * (motion['sum_cg'] / N)

    V = np.array([
        [var_og, cov_og_oo, cov_og_cg],
        [cov_og_oo, var_oo, cov_oo_cg],
        [cov_og_cg, cov_oo_cg, var_cg],
    ])

    V_inv = np.linalg.inv(V)

    z = N * (x_bar - mu).T @ V_inv @ (x_bar - mu) # need to brush up on this

    return z

In [486]:
z_numpy = compute_z(motion)
z_numpy

np.float64(43.65629699248114)

### No numpy / raw python

In [487]:
# def compute_z_no_numpy(motion):
N = motion['n']
mu = [1.5, 1.5, 1.5]

x_bar = motion[['sum_og', 'sum_oo', 'sum_cg']] / N
x_bar = x_bar.values

var_og = motion['sum_og_og'] / N - (motion['sum_og'] / N) ** 2
var_oo = motion['sum_oo_oo'] / N - (motion['sum_oo'] / N) ** 2
var_cg = motion['sum_cg_cg'] / N - (motion['sum_cg'] / N) ** 2

cov_og_oo = motion['sum_og_oo'] / N - (motion['sum_og'] / N) * (motion['sum_oo'] / N)
cov_og_cg = motion['sum_og_cg'] / N - (motion['sum_og'] / N) * (motion['sum_cg'] / N)

cov_oo_cg = motion['sum_oo_cg'] / N - (motion['sum_oo'] / N) * (motion['sum_cg'] / N)

V = [
    [var_og, cov_og_oo, cov_og_cg],
    [cov_og_oo, var_oo, cov_oo_cg],
    [cov_og_cg, cov_oo_cg, var_cg],
]

In [488]:
def determinant_3x3(matrix):
    """Calculate determinant of 3x3 matrix"""
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    
    return a*(e*i - f*h) - b*(d*i - f*g) + c*(d*h - e*g)

def invert_matrix_manual(matrix):
    """Manually invert a 3x3 matrix using adjugate method"""
    # Calculate determinant
    det = determinant_3x3(matrix)
    
    if abs(det) < 1e-10:
        raise ValueError("Matrix is singular and cannot be inverted")
    
    # Extract elements
    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]
    
    # Calculate cofactor matrix
    cofactor = [
        [+(e*i - f*h), -(d*i - f*g), +(d*h - e*g)],
        [-(b*i - c*h), +(a*i - c*g), -(a*h - b*g)],
        [+(b*f - c*e), -(a*f - c*d), +(a*e - b*d)]
    ]
    
    # Transpose cofactor matrix to get adjugate
    adjugate = [[cofactor[j][i] for j in range(3)] for i in range(3)]
    
    # Multiply by 1/det
    inverse = [[adjugate[i][j] / det for j in range(3)] for i in range(3)]
    
    return inverse



def dot_product(A, B):
    result = 0
    for i in range(len(A)):
        result += A[i] * B[i]
    return result

def matvecmul(A, B):
    result = [0 for _ in range(len(B))]

    for i in range(len(B)):
        result[i] = dot_product(A[i], B)

    return result

In [489]:
V_inv = invert_matrix_manual(V)
V_inv

[[np.float64(4.242105263157891),
  np.float64(-0.8894736842105294),
  np.float64(-0.2736842105263172)],
 [np.float64(-0.8894736842105294),
  np.float64(3.6312030075187933),
  np.float64(1.0458646616541334)],
 [np.float64(-0.2736842105263172),
  np.float64(1.0458646616541334),
  np.float64(1.0360902255639088)]]

In [490]:
xdiff = x_bar - mu
x_bar, xdiff

(array([np.float64(1.4615384615384615), np.float64(2.5384615384615383),
        np.float64(1.1538461538461537)], dtype=object),
 array([np.float64(-0.03846153846153855), np.float64(1.0384615384615383),
        np.float64(-0.34615384615384626)], dtype=object))

In [491]:
z_temp = matvecmul(V_inv, xdiff)
z_temp

[np.float64(-0.9921052631578975),
 np.float64(3.443045112781951),
 np.float64(0.7379699248120282)]

In [492]:
z_manual = dot_product(xdiff, z_temp) * N 
z_manual

np.float64(43.65629699248116)

In [493]:
assert (z_numpy - z_manual) < 1e-10, "The two methods of computing z give different results"

### Apply calculation

In [494]:
def try_compute_z(motion): 
    try: 
        return compute_z(motion)
    except Exception as e: 
        print(e)
        print(motion[['sum_og', 'sum_oo', 'sum_cg', 'sum_co', 'n']])
        return None

In [495]:
df_with_emb2.loc[with_results.index, 'z'] = with_results.apply(try_compute_z, axis=1)

In [496]:
df_with_results = df_with_emb2.loc[with_results.index]
fig = px.histogram(df_with_results[df_with_results['z'] < 100], x='z', nbins=100)
fig.show()

In [497]:
# sourced from: https://www.danielsoper.com/statcalc/calculator.aspx?id=12
CRITICAL_VALUES = [
    # (maximum value, level of significance as percentage string, evidence strength)
    (16.26623620, '0.1%', "extremely strong evidence"),
    (11.34486673,    '1%', "strong evidence"),
    (9.83740931,    '2%', "moderate evidence"),
    (7.81472790,    '5%', "weak evidence"),
    (6.25138863,   '10%', "very weak evidence"),
    (2.36597388,   '50%', "extremely weak evidence"),
    (0, '100%', "no evidence")
]

In [498]:
for x_val, significance, evidence_strenth in CRITICAL_VALUES:
    fig.add_vline(
        x=x_val, 
        line_dash="dot", 
        line_color="gray",
        line_width=1,
        annotation_text=evidence_strenth,
        annotation_position="bottom",
        annotation_font_size=12
    )

fig.show()

In [499]:
def get_evidence(motion):
    for critical, level_str, evidence_strength in CRITICAL_VALUES:
        if motion['z'] > critical:
            return evidence_strength
    else: 
        return "no evidence"

In [500]:
df_with_emb2.loc[df_with_results.index, 'imbalance'] = df_with_results.apply(get_evidence, axis=1)
df_with_emb2.head()

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding,pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,avg_speaks,tournament_avg_speaks,difficulty,z,imbalance
0,"This House believes that the South Korean government should redirect resources currently used to help Koryo-in settle in their respective countries of residence, to efforts to resettle them in South Korea.","Koryo-in (고려인) are Korean diasporas residing in post-Soviet countries, mainly\nin Central Asia. Koryo-ins moved to the Far East and Primorsky regions during\nthe 1910s to organise resistance against Japanese colonisation, until the\nSoviet Union forcefully relocated them to other territories in 1937. There are\naround 500,000 Koryo-ins, most of whom still identify as Korean descendants.\n\nThe South Korean government helps Koryo-ins abroad to settle in their\nrespective countries of residence by providing foreign aid in education, job\ntraining, etc.",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"the south korean government should redirect resources currently used to help koryo-in settle in their respective countries of residence, to efforts to resettle them in south korea","[0.04669427126646042, -0.041124969720840454, 0.0035075603518635035, 0.0260517168790102, 0.03168632462620735, 0.03356233984231949, -0.009249215014278889, -0.006061697844415903, -0.02862136997282505, 0.00864429771900177, 0.039939191192388535, -0.037726085633039474, -0.011120708659291267, -0.005691937170922756, -0.0199541375041008, -0.02535325102508068, 0.05702070891857147, -0.03576156869530678, -0.018242238089442253, 0.00883160624653101, 0.039861615747213364, -0.004181785508990288, 0.058362044394016266, 0.026758529245853424, 0.005156387109309435, -0.04580002278089523, -0.022358663380146027, 0.029002021998167038, -0.023128962144255638, -0.011231628246605396, 0.02017585188150406, -0.027394147589802742, 0.01893795281648636, -0.09919628500938416, -0.027543263509869576, 0.0016221209662035108, -0.025253776460886, -0.0274977944791317, 0.05655022710561752, -0.0008209593943320215, 0.057827334851026535, 0.013685733079910278, -0.0398455411195755, 0.014219488948583603, 0.03576551005244255, -0.019864141941070557, 0.01987016573548317, 0.04374896362423897, -0.036258265376091, -0.05490824207663536, 0.05305888131260872, -0.05439281463623047, 0.02745940163731575, -0.0241154246032238, -0.022838830947875977, -0.0018793627386912704, -0.006121313199400902, 0.04279809445142746, -0.012427078559994698, 0.023106200620532036, 0.005948835518211126, -0.0017394074238836765, 0.0648064985871315, -0.01647108420729637, -0.007654597982764244, 0.015587597154080868, 0.04501911625266075, -0.0003992000420112163, -0.02531033754348755, 0.007292148191481829, 0.015378573909401894, -0.05804913491010666, 0.07032416015863419, -0.03853347897529602, 0.003318109782412648, 0.03297140821814537, 0.0666864886879921, 0.040921054780483246, 0.0013249622425064445, -0.032992884516716, 0.0047950237058103085, -0.011690525338053703, -0.03517264872789383, -0.011561808176338673, 0.013435029424726963, -0.034368522465229034, -0.08386398106813431, 0.01719943806529045, -0.005637293215841055, -0.004097035154700279, 0.006272714119404554, 0.05273690074682236, 0.002075214870274067, -0.018995273858308792, 0.049240000545978546, 0.08046840876340866, 0.044540584087371826, 0.032655466347932816, -0.06836190819740295, -0.017110392451286316, ...]",4.835657,-4.971304,15,2.943763,-38.048893,27.929848,⚔️ Military Affairs,NaN,NaN,NaN,NaN,NaN
1,This House believes that we oppose Australia's 501 policy.,"Australia's 501 policy refers to section 501 of the Migration Act 1958, which\ndeals with the cancellation of visas on character grounds. Under the policy,\nthe Australian government has the authority to cancel the visas of and deport\nnon-citizens who fail the character test, regardless of how long they have\nlived in Australia. The policy is typically applied to individuals who have\nbeen sentenced to at least one year imprisonment.",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose australia's 501 policy,"[-0.033344559371471405, -0.02679823897778988, 0.014931241050362587, -0.03771759942173958, 0.011014328338205814, 0.03480580821633339, 0.03436955437064171, 0.04129122570157051, 0.012680070474743843, 0.046794693917036057, -0.011789522133767605, -0.011674067936837673, -0.04675508290529251, -0.056398194283246994, -0.008980480954051018, -0.007463964633643627, 0.01859915629029274, 0.0021135136485099792, -0.030623668804764748, 0.02374877780675888, 0.07980476319789886, -0.016002120450139046, 0.012355057522654533, -0.04228943958878517, 0.023834997788071632, -0.06392233818769455, -0.030597040429711342, -0.028563939034938812, -0.008308157324790955, 0.012124162167310715, 0.019427834078669548, -0.07976411283016205, 0.01534205861389637, 0.008453872986137867, -0.022203102707862854, -0.01403671782463789, -0.034375909715890884, 0.0063390349969267845, 0.0912412777543068, 0.007660025730729103, -0.05352997034788132, 0.020052649080753326, -0.05108562856912613, -0.06790313869714737, -0.019507864490151405, 0.041264504194259644, 0.06260392814874649, -0.011509700678288937, 0.011861427687108517, -0.06180088222026825, 0.014238405972719193, -0.016785146668553352, -0.007967708632349968, -0.03500732406973839, 0.008905332535505295, 0.007792004384100437, 0.011932531371712685, 0.05897797271609306, -0.0007354290573857725, -0.039223793894052505, 0.010213920846581459, 0.05243812873959541, -0.038344044238328934, -0.04228958860039711, -0.040818583220243454, -0.016978494822978973, 0.041443098336458206, 0.012510833330452442, -0.016557421535253525, -0.07781840115785599, 0.0026124310679733753, -0.00681748753413558, 0.04647905379533768, -0.043181162327528, 0.020285215228796005, 0.030044106766581535, 0.05089806392788887, 0.03722216188907623, -0.02077566832304001, -0.0024461436551064253, -0.09587405622005463, -0.0009424828458577394, -0.053047168999910355, -0.06851851940155029, 0.014756164513528347, -0.03827102854847908, -0.02707539312541485, -0.022714093327522278, -0.03338012099266052, 0.03044978529214859, 0.034322768449783325, 0.03769102320075035, -0.03771866858005524, -0.07225163280963898, 0.023464133962988853, 0.07949250191450119, 0.06064247339963913, -0.02167150378227234, -0.07632996886968613, -0.03093048557639122, ...]",1.844232,4.491210,19,-3.417307,-27.026424,-39.689732,⚕️ Medical Ethics,NaN,NaN,NaN,NaN,NaN
2,This House believes that we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants.,"Irregular migrants are those who enter another country without official\npermission. In response to border crossings by irregular migrants, several\ncountries adopt ‘pull-back’ measures, cooperating with migrants’ countries of\norigin to stop them from exiting (e.g. providing support for border controls).",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,Grand Final,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,we oppose countries adopting ‘pull-back’ measures to respond to the influx of irregular migrants,"[0.00870150700211525, -0.06843803077936172, -0.003463117405772209, 0.025157984346151352, 0.017507191747426987, -0.0303875170648098, -0.02059384435415268, 0.05743293836712837, 0.001368101336993277, 0.04095758870244026, 0.012575137428939342, -0.06718512624502182, -0.0037729800678789616, 0.0013310132781043649, 0.014933854341506958, 0.02128373645246029, 0.03513993322849274, -0.029221875593066216, -0.026073575019836426, -0.03702264651656151, 0.03800711780786514, -0.039052922278642654, 0.022951491177082062, -0.041488636285066605, 0.008226659148931503, -0.03117653913795948, -0.030418075621128082, 0.03691736236214638, -0.06780695915222168, 0.01721208728849888, -0.021600807085633278, 0.00027380892424844205, 0.02528715878725052, -0.04632057622075081, 0.005294193048030138, 0.06070960685610771, -0.015746744349598885, -0.051718179136514664, 0.05833754315972328, -0.013057909905910492, -0.030223308131098747, 0.028464946895837784, -0.023631641641259193, -0.028492162004113197, 0.0023581762798130512, 0.01808883808553219, -0.002124636899679899, 0.05886312201619148, -0.009186247363686562, 0.013616736978292465, -0.007131893653422594, 0.03140971437096596, 0.013715488836169243, -0.03529708459973335, -0.04912465065717697, -0.0009523194748908281, -0.018910903483629227, 0.06387355923652649, -0.030045751482248306, -0.014989549294114113, 0.004238853696733713, 0.016776930540800095, 0.012400010600686073, -0.03233559429645538, -0.011438199318945408, -0.01447566132992506, -0.01585332676768303, 0.02054649218916893, 0.026149284094572067, -0.0886291116476059, -0.0044746920466423035, -0.07485630363225937, 0.07267636805772781, -0.03504190966486931, 0.021445050835609436, 0.006780571769922972, 0.03294910117983818, 0.0629894882440567, -0.06639498472213745, -0.0009971009567379951, -0.00885708536952734, 0.015707779675722122, -0.028746945783495903, -0.010558170266449451, -0.036554064601659775, -0.0003507430083118379, -0.010836039669811726, -0.026925723999738693, -0.035643320530653, -0.006883218418806791, -0.028850719332695007, 0.04299624636769295, 0.033092204481363297, -0.04194900020956993, -0.01587717793881893, 0.1139565259218216, 0.007108272984623909, 0.024178646504878998, -0.035638563334941864, -0.04477965831756592, ...]",7.487733,0.981564,3,4.948655,-29.265728,-2.006341,🏛️ International Relations,NaN,NaN,NaN,NaN,NaN
3,"This House believes that we regret self-denial in religion (e.g. celibacy, fasting, giving up material or sensory pleasures).",NaN,Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,"we regret self-denial in religion (eg celibacy, fasting, giving up material or sensory pleasures)","[-0.03781802952289581, 0.033481165766716, 0.05631212145090103, -0.04665393754839897, 0.030571291223168373, 0.03060401789844036, -0.03684534505009651, 0.03794411942362785, -0.05032408982515335, -0.03707517310976982, -0.007899381220340729, -0.04870051518082619, 0.01471886970102787, -0.023229259997606277, -0.025252673774957657, 0.01097631175071001, 0.07246993482112885, -0.022962549701333046, 0.02120521478354931, -3.6210498365107924e-05, 0.03623451665043831, -0.05870863050222397, -0.014353977516293526, -0.03905477374792099, -0.016974221915006638, -0.03164180368185043, -0.07602657377719879, 0.00576959690079093, -0.03735310956835747, 0.052262138575315475, -0.0021347496658563614, -0.032232705503702164, 0.03518468141555786, 0.010982917621731758, 0.01443720143288374, 0.014075432904064655, 0.07856179773807526, 0.009881856851279736, -0.0310727097094059, 0.03203405812382698, -0.004914592020213604, 0.036556679755449295, -0.033561546355485916, -0.04233436658978462, 0.02899523451924324, 0.05726257711648941, 0.027067964896559715, 0.03896244987845421, 0.02377924695611, -0.012006774544715881, 0.007756521925330162, -0.012484170496463776, -0.005428309552371502, -0.006512461230158806, -0.023833636194467545, 0.07395032048225403, -0.039217352867126465, 0.009990389458835125, -0.05294599384069443, 0.011777274310588837, -0.029969284310936928, -0.013530579395592213, -0.019468260928988457, -0.07512820512056351, -0.03675688058137894, 0.10732477903366089, 0.049394700676202774, 0.026176564395427704, -0.030542870983481407, -0.07802857458591461, 0.030975764617323875, -0.03700203076004982, 0.008385596796870232, -0.044088635593652725, 0.031368378549814224, 0.018230661749839783, 0.007297438569366932, 0.08184492588043213, 0.03150804713368416, -0.05648035556077957, -0.06362149864435196, 0.03375725448131561, -0.02628646045923233, -0.0362667590379715, -0.031946346163749695, -0.0007111296290531754, -0.06358709186315536, -0.024333328008651733, -0.04770407825708389, -0.04663310572504997, -0.04786740615963936, 0.011825649999082088, 0.01031561754643917, -0.013282595202326775, -0.019841963425278664, -0.010743995197117329, 0.035443808883428574, 0.07772501558065414, -0.05338028818368912, 0.017505932599306107, ...]",-10.493422,-3.085940,4,-19.872459,8.277333,29.218498,🙏 Religious Doctrine,NaN,NaN,NaN,NaN,NaN
4,"This House believes that, in multireligious states, schools should teach integrated religious education instead of separated religious education.","In ‘integrated religious education’, all students are taught material\nencompassing many major religions.\n\nIn ‘separated religious education’, students study different religions in\ndistinct classrooms (i.e. Catholic students attend Catholic class, Buddhist\nstudents attend Buddhist class, etc.).",Jakarta Australasian Intervarsity Debate Championships 2024,https://edudrift.calicotab.com/australs2024,ESL Finals,E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,believes,", in multireligious states, schools should teach integrated religious education instead of separated religious education","[-0.07520031929016113, -0.03346019983291626, 0.06300149857997894, -0.013544010929763317, 0.005637470632791519, 0.04309633746743202, -0.06426656246185303, 0.05444727838039398, -0.025169309228658676, -0.02944754809141159, -0.015468250028789043, -0.032316047698259354, -0.01501105260103941, -0.006567661184817553, -0.062408387660980225, 0.010683541186153889, 0.0011690518585965037, -0.015708565711975098, -0.034836482256650925, -0.04100259765982628, 0.023420879617333412, -0.05665368214249611, -0.0037485540378838778, -0.005746413953602314, 0.08521213382482529, -0.05758580192923546, -0.04743649438023567, -0.03723529353737831, 0.019359180703759193, 0.007024390157312155, -0.03344457969069481, 0.02769320458173752, -0.014369726181030273, -0.040499478578567505, 0.02861480973660946, 0.019999805837869644, 0.015948209911584854, 0.0006641345680691302, 0.022074086591601372, -0.05318406969308853, -0.005211321637034416, 0.026106735691428185, -0.052494216710329056, -0.01786131039261818, 0.024853788316249847, 0.05995015799999237, 0.01337475422769785, 0.029842080548405647, -0.025944240391254425, -0.01554922852665186, 0.012158305384218693, -0.010886283591389656, -0.016360778361558914, -0.002266588155180216, 0.02398047037422657, 0.03760286048054695, -0.008035949431359768, -0.055095117539167404, 0.017622990533709526, 0.01159000489860773, 0.008484185673296452, 0.011263301596045494, 0.004175093956291676, -0.06071307137608528, 0.029846874997019768, 0.008960277773439884, 0.05101820081472397, -0.009726595133543015, -0.03735775500535965, 0.00921248272061348, -0.006142635829746723, 0.007486921269446611, -0.06690531224012375, -0.03949689865112305, 0.039431631565093994, 0.021605489775538445, 0.009596262127161026, 0.017230993136763573, -0.04003938287496567, 0.025672679767012596, -0.039553720504045486, 0.03464031219482422, -0.019456906244158745, -0.04437463358044624, -0.010899335145950317, -0.025988634675741196, -0.04247540980577469, 0.004260201007127762, -0.005645073018968105, 0.020099977031350136, -0.007241388782858849, 0.006596441380679607, -0.04178798198699951, -0.01944931410253048, 0.09613628685474396, 0.03908085078001022, 0.10429921001195908, 0.046262241899967194, -0.02572765201330185, -0.06777990609407425, ...]",-2.238666,-4.310638,4,-6.437295,-7.297156,38.905334,🙏 Religious Doctrine,NaN,NaN,NaN,NaN,NaN

In [501]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
df_with_results.sort_values(by='z', ascending=True)

,Motion,Info Slide,Tournament,tab_url,round_1,stage_1,n,sum_og,sum_og_og,sum_og_oo,sum_og_cg,sum_og_co,speaks,sum_oo,sum_oo_oo,sum_oo_cg,sum_oo_co,sum_cg,sum_cg_cg,sum_cg_co,sum_co,sum_co_co,oo_wins,co_wins,og_wins,cg_wins,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding,pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,avg_speaks,tournament_avg_speaks,difficulty,z,imbalance
677,"THS advanced economies’ recent emphasis on “resilience” over “efficiency” in large-scale economic policy reforms (e.g., semiconductors in the CHIPS Act, green technology in the Inflation Reduction Act, etc.)","Efficiency-oriented economic policy centers on reducing prices and maximizing output by allocating production according to where a comparative advantage exists (e.g., lowering barriers to trade and investment, removing regulations that impede competition). Resilience-oriented economic policy sacrifices efficiency in order to build redundancies in the event of economic shocks (e.g., subsidizing domestic production, restricting trade of key technologies with adversaries, building national reserves).",US Universities Debate Championship Tournament 2023,https://usudc2023.calicotab.com/usudc2023,Round 6,P,19.0,30.0,64.0,54.0,29.0,33.0,11563.0,32.0,80.0,25.0,33.0,25.0,61.0,35.0,27.0,61.0,NaN,NaN,NaN,NaN,NaN,NaN,2023.0,supports,"advanced economies’ recent emphasis on “resilience” over “efficiency” in large-scale economic policy reforms (eg, semiconductors in the chips act, green technology in the inflation reduction act, etc)","[-0.06525814533233643, -0.018451331183314323, 0.018012763932347298, 0.03190440312027931, 0.015900207683444023, 0.06253833323717117, -0.014356560073792934, 0.02404562383890152, 0.02854618802666664, 0.0019102577352896333, 0.02707374095916748, -0.037970155477523804, 0.018387727439403534, -0.03788526728749275, -0.01568647101521492, 0.005331592634320259, 0.07077094167470932, -0.05616021156311035, -0.03123176097869873, 0.019697224721312523, 0.06655599176883698, -0.09950701147317886, -0.006054691970348358, 0.05933784320950508, -0.04214105382561684, -0.11423518508672714, -0.009793848730623722, 0.010438607074320316, -0.017549263313412666, 0.04300614446401596, -0.006041842512786388, 0.03249169886112213, -0.014999771490693092, -0.037831418216228485, 0.04243362322449684, 0.04745490849018097, 0.01770125888288021, -0.0009298879886046052, 0.025951342657208443, 0.009058292955160141, -0.02365785464644432, 0.00995052233338356, -0.0025596260093152523, 0.0267694853246212, -0.010920844972133636, 0.033151812851428986, 0.015394606627523899, 0.019380245357751846, 0.005967678967863321, 0.0033818709198385477, -0.017280790954828262, -0.018899284303188324, -0.0226003248244524, 0.046781025826931, -0.015005487948656082, 0.006731926929205656, 0.022664597257971764, 0.045025501400232315, -0.052813492715358734, 0.02912485972046852, -0.031118040904402733, 0.03158066049218178, -0.052789267152547836, 0.015945442020893097, -0.018010994419455528, 0.0010677613317966461, 0.01387607678771019, 0.03149577975273132, -0.08040006458759308, 0.016833022236824036, -0.013930070213973522, -8.71418887982145e-05, -0.006808693055063486, 0.009370830841362476, 0.0002212400286225602, 0.024492517113685608, 0.025097614154219627, 0.027462774887681007, -0.009907763451337814, 0.053683117032051086, 0.0327250100672245, 0.010229302570223808, -0.026091502979397774, -0.02759389393031597, 0.02563154324889183, 0.011945408768951893, -0.012492863461375237, 0.04218944534659386, 0.0007729243952780962, 0.006191284861415625, -0.02077585831284523, 0.047571104019880295, 0.007752722594887018, -0.008248526602983475, 0.04860730469226837, 0.08328219503164291, -0.036225300282239914, 0.09822577983140945, -0.09722601622343063, -0.05270655080676079, ...]",5.517421,-3.940031,20,46.821331,10.002549,2.123726,🧭 Political Ideologies,76.072368,75.787646,1.806825,0.571949,no evidence
732,This House Believes That the insanity defence should extend to people with serious ASPD,"Antisocial personality disorder (ASPD) is a mental health condition characterized by a long-term pattern of disregard for, or violation of, the interests of others. People with serious ASPD are commonly known as psychopaths or sociopaths.\r\nThe application of the insanity defence means that the perpetrator is not punished; rather, they are referred to psychiatric care and released as soon as it is deemed to be safe.",Tokyo NEADC 2021,https://neadc.calicotab.com/neadc,Round 5,P,27.0,39.0,87.0,52.0,48.0,47.0,16316.0,42.0,98.0,45.0,57.0,37.0,81.0,48.0,44.0,112.0,NaN,NaN,NaN,NaN,NaN,NaN,2021.0,believes,the insanity defence should extend to people with serious aspd,"[-0.009350398555397987, -0.03314511850476265, 0.05023828148841858, 0.018290776759386063, 0.022922249510884285, 0.021268047392368317, 0.04927708953619003, 0.03713361918926239, 0.002699771197512746, -0.023766450583934784, -0.040661536157131195, -0.022213317453861237, -0.03438377007842064, -0.049607641994953156, -0.03231741487979889, 0.029832206666469574, 0.003081647679209709, -0.030811205506324768, 0.019162064418196678, 0.028145737946033478, -0.0054366146214306355, -0.02515963651239872, 0.036267444491386414, -0.06399648636579514, 0.02801155298948288, -0.006087863817811012, -0.035632334649562836, -0.037570372223854065, -0.02540728449821472, 0.03266097232699394, 0.003926027566194534, -0.004017090890556574, -0.02805650234222412, 0.02812815085053444, -0.015816284343600273, 0.03757140785455704, 0.013447600416839123, -0.01158340647816658, 0.0015521962195634842, 0.031806137412786484, -0.032945867627859116, 0.005148598924279213, -0.03969315066933632, -0.03644438460469246, 0.042435478419065475, 0.044321801513433456, 0.04295874014496803, 0.1006757840514183, -0.011797752231359482, -0.05710705369710922, 0.009208224713802338, 0.05675658583641052, -0.02366694062948227, 0.04066919907927513, 0.055266182869672775, -0.008437270298600197, 0.0051811374723911285, 0.006911312695592642, -0.0034782267175614834, 0.0688287764787674, -0.017185058444738388, -0.010371576994657516, -0.027747003361582756, 0.03077997826039791, -0.00029481007368303835, -0.010193946771323681, 0.06692317873239517, 0.03035501204431057, -0.0020630182698369026, -0.0673256665468216, -0.006893031764775515, -0.0004750163061544299, 0.033043041825294495, 0.004424528684467077, 0.02113352343440056, 0.01635630987584591, -0.033597350120544434, 0.041890326887369156, 0.0267125703394413, -0.0500979945063591, -0.013863762840628624, -0.06627492606639862, -0.02250000461935997, -0.0043424940668046474, -0.009246353060007095, -0.0044919406063854694, -0.046408891677856445, -0.04810478165745735, 0.027321113273501396, -0.011926683597266674, 0.0173123087733984, -0.01354342233389616, 0.031774457544088364, -0.05572176352143288, 0.04741270840167999, 0.09871471673250198, -0.025543561205267906, 0.036292318254709244, 0.00900025013834238, -0.010751810856163502, ...]",-4.154664,4.788583,6,-17.139530,53.473007,-3.335940,🧑‍⚖️ Criminal Justice,75.537037,75.540123,2.507716,0.579977,no evidence
356,This house believes that it is in the interests of religious leaders to forbid the use of artificial intelligence for any religious purposes,NaN,Dartmouth United States Universities' Debating Championships 2025,https://usudc2025.calicotab.com/_,Round 3,P,20.0,28.0,58.0,40.0,39.0,31.0,12267.0,34.0,84.0,38.0,42.0,29.0,67.0,30.0,29.0,71.0,NaN,NaN,NaN,NaN,NaN,NaN,2025.0,believes,it is in the interests of religious leaders to forbid the use of artificial intelligence for any religious purposes,"[-0.048213016241788864, -0.02072463184595108, 0.013401385396718979, -0.018142884597182274, 0.02540665678679943, 0.027099987491965294, -0.034855641424655914, 0.006495335604995489, -0.0051682791672647, -0.035035718232393265, 0.014326044358313084, 0.014368589036166668, -0.0021957061253488064, 0.014802264049649239, -0.020182117819786072, 0.05128820240497589, 0.020049188286066055, -0.021220682188868523, 0.07124413549900055, -0.04070407897233963, 0.03730160370469093, -0.0624307245016098, -0.0024091992527246475, -0.024247584864497185, 0.08500687032938004, -0.06186695024371147, -0.10035811364650726, -0.09289155155420303, -0.029032807797193527, 0.021037030965089798, -0.04062457010149956, 0.012229185551404953, 0.01058262400329113, 0.008829654194414616, -0.01366986520588398, 0.03861727565526962, 0.017747830599546432, 0.0063750166445970535, -0.002882195869460702, 0.00021420176199171692, -0.019880907610058784, -8.075097866822034e-05, -0.011937067843973637, 0.006919228937476873, 0.01666741631925106, 0.07353905588388443, -0.009107549674808979, 0.089619942009449, -0.030679281800985336, -0.004248941317200661, 0.0025872294791042805, 0.013079480268061161, -0.001599453273229301, 0.02619880996644497, -0.03836102411150932, 0.03651697561144829, -0.016712376847863197, 0.019649311900138855, 0.012359891086816788, 0.022846350446343422, -0.056883178651332855, 0.00446320092305541, -0.007622639648616314, -0.06066790968179703, 0.03623615950345993, 0.05809742584824562, 0.043911028653383255, 0.030015602707862854, 0.018247805535793304, -0.05736706405878067, 0.024695828557014465, -0.057373806834220886, 0.007062533404678106, 0.03681459277868271, 0.04814845323562622, -0.0487072728574276, 0.016042295843362808, 0.060949839651584625, -0.030498728156089783, -0.015603319741785526, -0.008517779409885406, 0.026283111423254013, -0.017273975536227226, -0.02148311398923397, 0.02026343159377575, 0.054365962743759155, 0.009204631671309471, -0.039135899394750595, -0.024872954934835434, 0.028145279735326767, 0.001016952097415924, 0.04239856079220772, 0.010259220376610756, -0.034561458975076675, 0.0036736507900059223, 0.019016465172171593, -0.0017457302892580628, 0.06860204041004181, 0.019821757450699806, 0.02489141747355461, ...]",-3.558477,1.118246,4,-20.872629,-3.367551,31.714998,🙏 Religious Doctrine,76.668750,76.566250,2.244644,0.665449,no evidence
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
522,"THO the depiction of tragedies through comedy e.g. Life is Beautiful, Jojo Rabbit, The Great Dictator, Good Morning Vietnam",NaN,Glasgow European Universities Debating Championships 2024,https://eudc2024.calicotab.com/_,Round 1,P,46.0,61.0,119.0,124.0,32.0,91.0,27931.0,100.0,260.0,73.0,143.0,36.0,68.0,43.0,79.0,197.0,NaN,NaN,NaN,NaN,NaN,NaN,2024.0,opposes,"depiction of tragedies through comedy eg life is beautiful, jojo rabbit, great dictator, good morning vietnam","[0.021553194150328636, -0.022402750328183174, 0.020355014130473137, -0.025219375267624855, -0.010880604386329651, 0.04746861755847931, 0.019405867904424667, 0.011635317467153072, 0.015389421954751015, -0.013748221099376678, -0.07889667898416519, 0.007319183554500341, 0.026573175564408302, 0.022961048409342766, -0.01928921416401863, 0.02294824831187725, 0.05827195569872856, 0.005326118785887957, -0.027612540870904922, 0.042274121195077896, 0.029789520427584648, -0.019641317427158356, -0.023105794563889503, -0.07200007885694504, -0.01989220641553402, -0.037419434636831284, 0.002994998125359416, -0.006237041670829058, -0.10938098281621933, 0.005298236384987831, 0.0039441389963030815, -0.00636926619336009, 0.01995040476322174, 0.09044463187456131, -0.02309001423418522, 0.012471979483962059, 0.04988110810518265, -0.062288131564855576, -0.01607464998960495, 0.05196972191333771, 0.04215637966990471, -0.012183797545731068, -0.05627988651394844, -0.030328484252095222, -0.0008195264963433146, 0.019775638356804848, 0.04282332584261894, 0.04571203887462616, 0.025381678715348244, -0.06483545899391174, 0.012701203115284443, -0.01956980861723423, 0.04090260714292526, 0.08211129158735275, 0.01880805194377899, 9.987081284634769e-05, -0.011141310445964336, -0.04620606452226639, -0.05376577749848366, -0.01035219430923462, -0.047088053077459335, -0.04996620863676071, -0.026452962309122086, 0.03648390993475914, -0.03908607363700867, 0.032979317009449005, -0.0120841758325696, 0.07094832509756088, -0.023990539833903313, -0.0679488331079483, 0.020271725952625275, 0.0654563158750534, 0.007272772025316954, -0.015498384833335876, 0.047807954251766205, 0.0730283111333847, -0.025982998311519623, 0.11065490543842316, 0.029950041323900223, -0.039511509239673615, -0.018262071534991264, 0.03549962490797043, -0.014619549736380577, 0.0158286951482296, 0.05190318450331688, -0.016552571207284927, -0.03162100538611412, 0.009054874069988728, -0.05888479948043823, -0.10165777802467346, -0.040703628212213516, 0.03853277489542961, -0.018282655626535416, 0.009725152514874935, 0.016683442518115044, 0.02172265388071537, -0.012841513380408287, 0.035143401473760605, -0.0022545226383954287, 0.047147441655397415, ...]",-5.468651,-6.988043,2,-35.220490,24.860922,17.128740,🎭 Societal Narratives,75.899457,76.231582,3.301074,51.238285,extremely strong evidence
729,"This house supports dating apps that are exclusive to members of particular ethnic communities \r\n(e.g. AsianDating.com, WhereWhitePeopleMeet, etc.)",NaN,Tokyo NEADC 2021,https://neadc.calicotab.com/neadc,Round 2,P,27.0,55.0,133.0,86.0,79.0,32.0,16339.0,49.0,117.0,64.0,27.0,42.0,100.0,9.0,16.0,28.0,NaN,NaN,NaN,NaN,NaN,NaN,2021.0,supports,"dating apps that are exclusive to members of particular ethnic communities \r\n(eg asiandatingcom, wherewhitepeoplemeet, etc)","[0.0005183379398658872, -0.006182767450809479, -0.010557730682194233, -0.03161849454045296, 0.06391733139753342, 0.008170022629201412, 0.00023697114374954253, 0.024884503334760666, -0.029027555137872696, -0.019718095660209656, -0.024255504831671715, 0.002519082510843873, -0.09682030975818634, 0.01575375162065029, -0.05264277011156082, 0.06348051130771637, 0.04758749529719353, 0.017798293381929398, 0.017949165776371956, -0.0015722167445346713, 0.0639120489358902, -0.014245593920350075, -0.0001057663030223921, -0.035487547516822815, -0.017528364434838295, -0.028864402323961258, -0.040105968713760376, -0.038460806012153625, -0.0851488932967186, -0.0019777838606387377, 0.09979960322380066, 0.038635458797216415, 0.04363171011209488, 0.05479314550757408, 0.0016548380954191089, -0.025250889360904694, 0.025938207283616066, -0.025943776592612267, 0.05520067736506462, 0.03576246649026871, -0.006861434318125248, 0.020369768142700195, -0.02704814076423645, -0.07518335431814194, -0.00517861545085907, 0.04663459211587906, 0.034992460161447525, 0.03964320942759514, -0.047405604273080826, -0.048788607120513916, 0.012231453321874142, 0.07777401059865952, -0.07888534665107727, -0.03772584721446037, 0.01956022158265114, -0.029280927032232285, -0.038187798112630844, 0.026360562071204185, -0.0017933481140062213, 0.010737482458353043, 0.033769283443689346, -0.042402539402246475, 0.014161523431539536, -0.06096995621919632, -0.017874659970402718, 0.027423420920968056, 0.021765301004052162, 0.07041747123003006, 0.005060612689703703, -0.050849419087171555, 0.02331746183335781, -0.01306574884802103, 0.0007089597056619823, 0.002717207185924053, 0.019880101084709167, -0.04863012954592705, 0.039456021040678024, 0.02564726583659649, -0.012355110608041286, -0.03790060058236122, -0.016310174018144608, 0.008793700486421585, -0.00856033619493246, 0.03325657546520233, 0.024471014738082886, 0.0279268529266119, -0.0019927984103560448, 0.046749770641326904, -0.04627430811524391, 0.015391295775771141, 0.03628015145659447, 0.004942655563354492, -0.06316965818405151, -0.06682494282722473, 0.0985371470451355, -0.00893143005669117, 0.03453788161277771, 0.0325385257601738, -0.10903225094079971, 0.01002875342965126, ...]",-4.624513,-2.855612,18,-33.695381,33.070538,-19.277607,🫂 Cultural Identity,75.643519,75.540123,2.242430,53.290849,extremely strong evidence
721,This House Would dissolve the position of High Representative for Bosnia and Herzegovina,"The High Representative for Bosnia and Herzegovina is a position that was created in 1995 as part of the Dayton Peace Agreement that ended the Bosnian War. The postholder is appointed by the United Nations Security Council.\r\n\r\nThe High Representative's powers, without judicial oversight, include introducing or repealing laws or constitutional amendments, removing public officials from office, and banning individuals from running in elections.\r\n\r\nFor example, in 2021 the outgoing High Representative, Austrian Valentin Inzko, amended existing criminal law to make genocide denial and the glorification of war criminals illegal.",Zagreb European Universities Debating Championships 2022,https://eudc2022.calicotab.com/eudc2022,Round 7,P,37.0,31.0,51.0,71.0,7.0,57.0,22035.0,88.0,228.0,55.0,174.0,25.0,45.0,43.0,78.0,194.0,NaN,NaN,NaN,NaN,NaN,NaN,2022.0,would,dissolve the position of high representative for bosnia and herzegovina,"[0.005846691317856312, -0.06598889827728271, 0.01844724453985691, -0.046097151935100555, -0.012125474400818348, -0.0022565287072211504, 0.02791939303278923, 0.011376705020666122, -0.022184140980243683, 0.03673945739865303, 0.007446241099387407, -0.0718257948756218, 0.02980540692806244, 0.006938084494322538, 0.018334127962589264, -0.0385291613638401, 0.08752425014972687, -0.0686706155538559, 0.030999986454844475, 0.025056714192032814, 0.016618235036730766, -0.02211065962910652, -0.028041144832968712, -0.021516071632504463, -0.007907315157353878, -0.09503665566444397, -0.04200166091322899, 0.00018890976207330823, -0.03287527710199356, 0.0226131584495306, -0.013634318485856056, -0.004407704807817936, 0.03265293315052986, -0.06959182024002075, -0.060893140733242035, 0.024818377569317818, 0.01704038307070732, 0.014428977854549885, 0.001464773085899651, 0.05601135268807411, -0.0049723368138074875, -0.005823479034006596, -0.05885160714387894, 0.008315487764775753, 0.03670740872621536, 0.013896607793867588, -0.014901792630553246, 0.05026939883828163, -0.05883319303393364, -0.020526684820652008, 0.031636420637369156, 0.08816471695899963, 0.003356402274221182, -0.059493035078048706, -0.030075086280703545, 0.05989573895931244, -0.015396246686577797, -0.027576442807912827, -0.028272442519664764, -0.008400419726967812, -0.10225575417280197, 0.004640031140297651, 0.02224387787282467, -0.00762907462194562, -0.01759917289018631, -0.0165447685867548, 0.06039378419518471, 0.05098254233598709, 0.024140072986483574, -0.06834085285663605, 0.0045378971844911575, 0.001457965699955821, -0.002049789298325777, 0.016669539734721184, 0.035777609795331955, 0.051320917904376984, 0.03678121790289879, 0.11298487335443497, -0.06252222508192062, 0.012138665653765202, 0.0019660501275211573, 0.047902628779411316, -0.007819718681275845, -0.0008655411074869335, 0.0001673917140578851, -0.06372072547674179, -0.011173846200108528, 0.0023253627587109804, -0.004208965227007866, 0.022295961156487465, 0.013106410391628742, 0.06155775114893913, 0.05129331722855568, -0.00710382591933012, 0.00555665185675025, 0.04061746224761009, 0.051280517131090164, 0.01771717518568039, -0.013924382627010345, -0.09126400947570801, ...]",5.116701,-0.391674,3,3.131981,-48.461193,-0.917382,🏛️ International Relations,74.442568,75.345948,4.294850,136.883901,extremely strong evidence

In [502]:
critical_index = list(map(lambda x: x[2], CRITICAL_VALUES))
critical_index

['extremely strong evidence',
 'strong evidence',
 'moderate evidence',
 'weak evidence',
 'very weak evidence',
 'extremely weak evidence',
 'no evidence']

In [503]:
by_imbalance = df_with_emb2['imbalance'].value_counts().reindex(reversed(critical_index))
by_imbalance

imbalance
no evidence                  32
extremely weak evidence      42
very weak evidence           28
weak evidence                14
moderate evidence             6
strong evidence              19
extremely strong evidence    37
Name: count, dtype: int64

In [504]:
px.bar(by_imbalance, width=1000, height=600).show()

### Imbalance x Difficulty

In [505]:
px.scatter(df_with_results, x='z', y='difficulty')

### Imbalance x Theme

In [506]:
px.scatter(df_with_results, x='z', y='category')

In [507]:
imbalance_by_theme = df_with_results.groupby('category')['z'].median()
imbalance_by_theme = imbalance_by_theme.sort_values(ascending=True)

# Define custom y labels at certain y= horizontal locations
import plotly.graph_objects as go

fig = px.bar(
    imbalance_by_theme, 
    x=imbalance_by_theme.index, 
    y=imbalance_by_theme.values, 
    width=1000, 
    height=600,
    title="Median Imbalance by Theme",
    labels={'x': 'Theme', 'y': 'Median Imbalance'},
    # y_label="Median Imbalance"
)

# Add custom y labels at specific y values

for y_val, significance, evidence_strenth in CRITICAL_VALUES:
    fig.add_hline(
        y=y_val, 
        line_dash="dot", 
        line_color="gray",
        line_width=1,
        annotation_text=evidence_strenth,
        annotation_position="right",
        annotation_font_size=12
    )

fig.show()
# px.bar(imbalance_by_theme, x=imbalance_by_theme.index, y=imbalance_by_theme.values, width=1000, height=600).show()

### Imbalance x Type

In [520]:
imbalance_by_theme = df_with_results.groupby('Motion Type')['z'].median()
imbalance_by_theme = imbalance_by_theme.sort_values(ascending=True)

# Define custom y labels at certain y= horizontal locations
import plotly.graph_objects as go

fig = px.bar(
    imbalance_by_theme, 
    x=imbalance_by_theme.index, 
    y=imbalance_by_theme.values, 
    width=1000, 
    height=600,
    title="Median Imbalance by Type",
    labels={'x': 'Type', 'y': 'Median Imbalance'},
    # y_label="Median Imbalance"
)

# Add custom y labels at specific y values

for y_val, significance, evidence_strenth in CRITICAL_VALUES:
    fig.add_hline(
        y=y_val, 
        line_dash="dot", 
        line_color="gray",
        line_width=1,
        annotation_text=evidence_strenth,
        annotation_position="right",
        annotation_font_size=12
    )

fig.show()
# px.bar(imbalance_by_theme, x=imbalance_by_theme.index, y=imbalance_by_theme.values, width=1000, height=600).show()

### Imbalance x Year

In [521]:
imbalance_by_theme = df_with_results.groupby('Year')['z'].median()
imbalance_by_theme = imbalance_by_theme.sort_values(ascending=True)

# Define custom y labels at certain y= horizontal locations
import plotly.graph_objects as go

fig = px.bar(
    imbalance_by_theme, 
    x=imbalance_by_theme.index, 
    y=imbalance_by_theme.values, 
    width=1000, 
    height=600,
    title="Median Imbalance by Theme",
    labels={'x': 'Theme', 'y': 'Median Imbalance'},
    # y_label="Median Imbalance"
)

# Add custom y labels at specific y values

for y_val, significance, evidence_strenth in CRITICAL_VALUES:
    fig.add_hline(
        y=y_val, 
        line_dash="dot", 
        line_color="gray",
        line_width=1,
        annotation_text=evidence_strenth,
        annotation_position="right",
        annotation_font_size=12
    )

fig.show()
# px.bar(imbalance_by_theme, x=imbalance_by_theme.index, y=imbalance_by_theme.values, width=1000, height=600).show()

## Export for website

In [508]:
df_with_emb2.to_json('data/motions.json', orient='records') #FIXME: could be a nicer export (remove redudancy, group things together)

## Side balance

probably deserves a separate notebook

In [248]:
df_with_emb2.sample(1)

,Unnamed: 0,Motion,Info Slide,Tournament,sum_og,sum_oo,sum_cg,sum_co,sum_og_og,sum_oo_oo,sum_cg_cg,sum_co_co,sum_og_oo,sum_og_cg,sum_og_co,sum_oo_cg,sum_oo_co,sum_cg_co,og_wins,oo_wins,cg_wins,co_wins,n,speaks,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding,pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,avg_speaks,tournament_avg_speaks,difficulty,z,imbalance
511,511,"In post-colonial states, THP education where strong emphasis is placed on multi-culturalism over similarities between different groups",NaN,neadc2022:2022,51.0,40.0,44.0,45.0,125.0,88.0,102.0,105.0,51.0,75.0,55.0,39.0,62.0,48.0,0.0,0.0,0.0,0.0,30,18071.0,Round 4,P,NaN,NaN,2022.0,prefers,education where strong emphasis is placed on multi-culturalism over similarities between different groups,"[-0.04337465390563011, -0.02536536194384098, 0.02332160249352455, -0.0057557919062674046, 0.04405408352613449, 0.04481509327888489, 0.003533175913617015, 0.005139156710356474, -0.0006086082430556417, 0.027106139808893204, -0.016064733266830444, -0.0684538185596466, -0.06376209855079651, 0.008760707452893257, -0.039858005940914154, 0.02109174244105816, 0.027730552479624748, -0.02565099485218525, -0.03379356488585472, 0.0010756861884146929, 0.11246870458126068, -0.0743807777762413, -0.050740476697683334, -0.03318255394697189, 0.035340066999197006, -0.09142283350229263, -0.01242617517709732, -0.03250930830836296, -0.0243351049721241, -0.09859424084424973, 0.06645626574754715, 0.05360835790634155, 0.014934390783309937, -0.0354311540722847, 0.014681054279208183, -0.010985643602907658, -0.0030174371786415577, -0.008654973469674587, 0.04495846480131149, 0.04580735042691231, -0.0024388739839196205, -0.0305270217359066, -0.02443745918571949, -0.10925149917602539, -0.020340578630566597, 0.0170959010720253, 0.017159178853034973, -0.024074576795101166, -0.042901284992694855, -0.015545357950031757, 0.026015883311629295, 0.02215803973376751, -0.026521995663642883, 0.012800921685993671, 0.023527132347226143, 0.04738566279411316, -0.01958950236439705, -0.04639827087521553, -0.011621536687016487, -0.002570436568930745, 0.051326051354408264, -0.036951467394828796, 0.034808557480573654, -0.019638720899820328, 0.03019420988857746, 0.010590363293886185, 0.03292176499962807, -0.010092497803270817, -0.0641082227230072, -0.07031247764825821, 0.04029904305934906, 0.03793153539299965, 0.003716894891113043, -0.022654250264167786, 0.03773219883441925, 0.0003525181964505464, -0.0009265103144571185, 0.02018056996166706, -0.025317169725894928, -0.03444783762097359, -0.028515048325061798, 0.054337576031684875, -0.026309045031666756, -0.057145729660987854, -0.00642998656257987, 0.006582006346434355, -0.014394447207450867, 0.005054962355643511, -0.022171625867486, -0.03714342042803764, 0.034470122307538986, 0.01993439719080925, -0.07564899325370789, -0.02723422832787037, 0.08413632214069366, 0.04219828173518181, 0.07711180299520493, 0.055253639817237854, -0.014312964864075184, -0.03254425898194313, ...]",-7.106438,-6.816153,0,12.362757,48.733463,-1.162026,🏫 Higher Education,75.295833,75.174018,2.80304,1.457958,no evidence

In [365]:
og_points = df_with_emb2['sum_og'].sum()
oo_points = df_with_emb2['sum_oo'].sum()
cg_points = df_with_emb2['sum_cg'].sum()
co_points = df_with_emb2['sum_co'].sum()

og_points, oo_points, cg_points, co_points

(np.float64(11125.0),
 np.float64(13288.0),
 np.float64(10499.0),
 np.float64(11228.0))

In [366]:
data = [
    [og_points, oo_points],
    [cg_points, co_points]
]

In [388]:
px.imshow(data, text_auto=True)

In [104]:
og_wins = df_with_emb2['og_wins'].sum()
oo_wins = df_with_emb2['oo_wins'].sum()
cg_wins = df_with_emb2['cg_wins'].sum()
co_wins = df_with_emb2['co_wins'].sum()


all_wins = og_wins + oo_wins + cg_wins + co_wins

og_percent_wins = og_wins / all_wins
oo_percent_wins = oo_wins / all_wins
cg_percent_wins = cg_wins / all_wins
co_percent_wins = co_wins / all_wins

data = [
    [og_percent_wins, oo_percent_wins],
    [cg_percent_wins, co_percent_wins]
]

px.imshow(data, text_auto=True)

## comments/suggestions
- diversity in race, gender etc.
- probability cloud (?)

## DEPRECATED: WSDC Team wins (balance)

In [29]:
prop_wins = df['Prop wins'].sum()
opp_wins = df['Opp wins'].sum()

print(prop_wins, opp_wins)

px.pie(
    values=[prop_wins, opp_wins],
    names=['Prop wins', 'Opp wins'],
    title='Total Prop vs Opp Wins',
).show()

KeyError: 'Prop wins'

In [11]:
prop_wins = df_this_year['Prop wins'].sum()
opp_wins = df_this_year['Opp wins'].sum()

print(prop_wins, opp_wins)

px.pie(
    values=[prop_wins, opp_wins],
    names=['Prop wins', 'Opp wins'],
    title='Total Prop vs Opp Wins',
).show()

196.0 85.0

In [ ]:
# take a look at thow this varies by rounds (e.g. outrounds)