In [2]:
import pandas as pd
import plotly.express as px
from datetime import datetime
import os

In [3]:
pd.set_option("display.max_colwidth", 100)  # after this you can print any column length
pd.set_option("display.max_rows", 7)  # after this you can print any column length

## Load data

In [4]:
data_dir = 'raw'
motions_data_path = os.path.join(data_dir, 'motions_bp.csv')

if not os.path.exists(motions_data_path): 
    raise FileNotFoundError('Local data file not found. Please run the data collection notebook first.')

df = pd.read_csv(motions_data_path, index_col=0)
df.head(10)

,Motion,Info Slide,Tournament,og_points,oo_points,cg_points,co_points,og_wins,oo_wins,cg_wins,co_wins,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding
0,This House Supports strict state secularism* in Western Liberal Democracies.\r\n*this includes p...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Round 1,P,NaN,NaN,2024.0,supports,strict state secularism* in western liberal democracies\r\n*this includes prohibiting religious ...,"[-0.006643143482506275, -0.054989926517009735, 0.024147387593984604, -0.015618590638041496, 0.02..."
1,This House Prefers A World where Truth and Reconciliation Commissions were established to deal w...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Round 2,P,NaN,NaN,2024.0,prefers,a world where truth and reconciliation commissions were established to deal with the aftermath o...,"[-0.014495608396828175, -0.022106049582362175, 0.024879267439246178, -0.030019503086805344, 0.03..."
2,This House Would ban sports betting.,Sports betting is a form of gambling where people bet money on the outcome of\nsports events (eg...,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Round 3,P,NaN,NaN,2024.0,would,ban sports betting,"[0.025729607790708542, 0.017467768862843513, 0.04677936062216759, 0.002135881455615163, 0.045425..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7,This House opposes attempts by the feminist movement to redefine traditionally feminine* roles a...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Round 8,P,NaN,NaN,2024.0,opposes,attempts by the feminist movement to redefine traditionally feminine* roles and behaviours as em...,"[-0.0455312579870224, 0.015439186245203018, 0.0012294548796489835, -0.00377446785569191, 0.04565..."
8,This House would put an upper age limit of 60 years old for individuals running for political of...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Double-Octofinals,E,NaN,NaN,2024.0,would,put an upper age limit of 60 years old for individuals running for political office,"[-0.009694591164588928, -0.04434267431497574, 0.028031330555677414, 0.006176283583045006, 0.0121..."
9,This House regrets the narrative that money cannot buy happiness.,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Octofinals,E,NaN,NaN,2024.0,regrets,narrative that money cannot buy happiness,"[-0.030767444521188736, -0.025944072753190994, -0.004536631051450968, -0.017151610925793648, 0.0..."

### Parse the embedding field as float[]

In [5]:
import json
df['Embedding'] = df['Embedding'].map(json.loads)

## Motion counts

In [6]:
by_year = df.groupby('Year')
year_counts = by_year['Motion'].count()

In [7]:
px.line(year_counts)

## Motion types

### All-time motion types

In [8]:
year_counts = df.value_counts('Motion Type')
print(year_counts)

px.bar(
    year_counts, 
    y='count', 
    title='Motion Types',
    labels={'Motion Type': 'Motion Type'},
).show()

Motion Type
believes    578
would       170
prefers      78
           ...
predicts      2
as            1
welcomes      1
Name: count, Length: 10, dtype: int64

### This year's motion types

In [9]:
current_year = datetime.now().year

df_this_year = df[df['Year'] == current_year]
df_this_year.tail()

,Motion,Info Slide,Tournament,og_points,oo_points,cg_points,co_points,og_wins,oo_wins,cg_wins,co_wins,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),Embedding
1006,This house regrets the Indian Premier League.,The Indian Premier League (IPL) is a domestic cricket league in India. Since\nits inception in 2...,hwsrr2025:_,2.0,9.0,3.0,10.0,0.0,0.0,0.0,0.0,Round 2-A,P,Round 2-B,P,2025.0,regrets,indian premier league,"[0.007603739388287067, 0.012494048103690147, -0.01023069303482771, 0.0025290455669164658, 0.0194..."
1007,This house believes that breaking up large meat companies is in the interests of animal welfare.,NaN,hwsrr2025:_,6.0,7.0,5.0,6.0,0.0,0.0,0.0,0.0,Round 3-A,P,Round 3-B,P,2025.0,believes,breaking up large meat companies is in the interests of animal welfare,"[-0.03787577897310257, -0.024296151474118233, 0.03693372756242752, -0.06150189787149429, 0.01866..."
1008,This house prefers a world where genius only develops after adulthood (so that there are no chil...,NaN,hwsrr2025:_,8.0,7.0,5.0,4.0,0.0,0.0,0.0,0.0,Round 4-A,P,Round 4-B,P,2025.0,prefers,a world where genius only develops after adulthood (so that there are no child prodigies),"[-0.043584320694208145, 0.02300327457487583, 0.025124406442046165, 0.03347980976104736, -0.01141..."
1009,This house believes that East African national governments should prioritize investments in agri...,NaN,hwsrr2025:_,12.0,3.0,3.0,6.0,0.0,0.0,0.0,0.0,Round 5-A,P,Round 5-B,P,2025.0,believes,"east african national governments should prioritize investments in agriculture (eg, irrigation,...","[-0.006614001467823982, 0.005583884194493294, 0.03191974759101868, -0.015895619988441467, 0.0428..."
1010,"Assuming a peaceful and democratic transition, this house supports the United States of America ...",NaN,hwsrr2025:_,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Grand Final,E,NaN,NaN,2025.0,supports,"united states of america being separated into several, more politically-homogeneous, sovereign ...","[-0.06570275127887726, 0.001371739897876978, 0.020081818103790283, 0.013572579249739647, 0.04833..."

In [10]:
year_counts = df_this_year.value_counts('Motion Type')

px.bar(
    year_counts, 
    y='count', 
    title=f'Motion Types for {current_year}',
    labels={'Motion Type': 'Motion Type'},
).show()

## Semantic analysis

In [11]:
%pip install -q scikit-learn

Note: you may need to restart the kernel to use updated packages.

In [12]:
# spread embeddings across multiple columns

df_embeddings = pd.DataFrame(df['Embedding'].to_list())
df_embeddings.head()

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
0,-0.006643,-0.054990,0.024147,-0.015619,0.023231,0.009700,-0.025271,0.065433,-0.009952,-0.013879,...,0.051592,-0.006494,0.010797,0.034301,-0.002645,0.004727,0.001804,-0.028897,0.009105,-0.032109
1,-0.014496,-0.022106,0.024879,-0.030020,0.030532,-0.041181,0.011720,-0.004287,-0.056133,0.000079,...,0.099803,-0.023606,0.028624,0.021055,0.012671,0.022256,-0.021336,-0.027690,0.008352,-0.000573
2,0.025730,0.017468,0.046779,0.002136,0.045425,0.034249,-0.017990,0.021838,-0.025936,-0.039223,...,0.016942,0.034391,-0.043860,0.040858,-0.004918,0.046314,0.019110,0.032059,-0.015235,0.000771
3,-0.027982,0.019545,0.035038,-0.024627,0.029799,0.032075,0.008817,0.055913,-0.015072,0.019600,...,0.035239,0.080440,-0.001089,0.051216,-0.022976,-0.029108,0.018908,0.036357,-0.033717,-0.027688
4,0.026241,0.003334,0.020402,-0.015378,0.028763,0.006449,-0.002907,0.056074,-0.002208,-0.003650,...,0.036782,0.059721,0.051490,0.014030,0.034918,0.030074,0.002083,-0.007548,-0.050032,-0.058112

### Standardize features

In [13]:
def check_distr(df: pd.DataFrame):
    mse_mean = ((df.mean() - 0) ** 2).mean()
    mse_std = ((df.std() - 1) ** 2).mean()

    print(f"Mean: {df.values.mean()}, mse: {mse_mean}")
    print(f"St.d.: {df.values.std()}, mse: {mse_std}")

check_distr(df_embeddings)

Mean: -0.001968966658392004, mse: 0.0005093506463420668
St.d.: 0.03603058876781649, mse: 0.9447128067618428

In [14]:
from sklearn.preprocessing import StandardScaler

scaled = StandardScaler().fit_transform(df_embeddings)
df_embeddings = pd.DataFrame(scaled)

check_distr(df_embeddings)

Mean: -2.2694964565367527e-18, mse: 2.002956954659257e-33
St.d.: 0.9999999999999998, mse: 2.4495276360787605e-07

### KMeans

In [15]:
from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

silhouettes = []

k_range = (2, min(len(df_embeddings), 100))

def find_best_n_clusters(start: int = k_range[0], end: int = k_range[1]):
    best_n = dict(
        n=0.0,
        score=-1.0
    )

    for n_clusters in range(start, end):
        kmeans = KMeans(n_clusters=n_clusters, random_state=42)
        kmeans.fit(df_embeddings)

        df_kmeans = pd.DataFrame(kmeans.labels_, columns=['centroid'])

        silhouette_avg = float(silhouette_score(df_embeddings, df_kmeans.values.ravel()))
        silhouettes.append(silhouette_avg)

        if silhouette_avg > best_n['score']:
            best_n['score'] = silhouette_avg
            best_n['n'] = n_clusters
    
    return best_n

best_n_clusters = find_best_n_clusters()

In [16]:
print(f"Best n clusters = {best_n_clusters['n']} with a silhouette score of {best_n_clusters['score']}")
fig = px.line(x=range(*k_range), y=silhouettes)

avg = sum(silhouettes) / len(silhouettes)
fig.add_hline(y=avg, line_dash='dash')

Best n clusters = 93 with a silhouette score of 0.03350400468195204

NOTE! This generally shows a pretty weak argument for single-label clustering (the silhouette score is as low as 0.03 when 1.00 is the ideal).

In [18]:
n_clusters = None

# select the first value above avg
for i,k in enumerate(silhouettes): 
    if k >= avg:
        n_clusters = i + 2 # + 2 because k >= 2
        break

n_clusters

19

In [19]:
kmeans = KMeans(n_clusters=n_clusters, random_state=42)
kmeans.fit(df_embeddings)

labels = kmeans.labels_
centroids = kmeans.cluster_centers_

df_kmeans = pd.DataFrame(labels, columns=['centroid'])
df_kmeans.head()

   centroid
0         5
1        17
2        13
3         6
4        16

In [20]:
# import matplotlib.pyplot as plt
# import matplotlib.cm as cm
# import numpy as np
# from sklearn.metrics import silhouette_samples

# sample_silhouette_values = silhouette_samples(df_embeddings, df_kmeans.values.ravel())

# ax1 = plt.subplot()

# y_lower = 10
# for i in range(n_clusters):
#     # Aggregate the silhouette scores for samples belonging to
#     # cluster i, and sort them
#     ith_cluster_silhouette_values = sample_silhouette_values[df_kmeans.values.ravel() == i]

#     ith_cluster_silhouette_values.sort()

#     size_cluster_i = ith_cluster_silhouette_values.shape[0]
#     y_upper = y_lower + size_cluster_i

#     color = cm.nipy_spectral(float(i) / n_clusters)
#     ax1.fill_betweenx(
#         np.arange(y_lower, y_upper),
#         0,
#         ith_cluster_silhouette_values,
#         facecolor=color,
#         edgecolor=color,
#         alpha=0.7,
#     )

#     # Label the silhouette plots with their cluster numbers at the middle
#     ax1.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))

#     # Compute the new y_lower for next plot
#     y_lower = y_upper + 10  # 10 for the 0 samples

# ax1.set_title("The silhouette plot for the various clusters.")
# ax1.set_xlabel("The silhouette coefficient values")
# ax1.set_ylabel("Cluster label")

# # The vertical line for average silhouette score of all the values
# ax1.axvline(x=silhouette_avg, color="red", linestyle="--")

# ax1.set_yticks([])  # Clear the yaxis labels / ticks
# # ax1.set_xticks([-0.1, 0, 0.2, 0.4, 0.6, 0.8, 1])

### PCA

In [21]:
from sklearn.decomposition import PCA

pca = PCA(n_components=2)
pca_embeddings = pca.fit_transform(df_embeddings)
df_pca = pd.DataFrame(pca_embeddings, columns=['pca_1', 'pca_2'])

df_pca.head(), pca_embeddings.shape, pca.explained_variance_ratio_

(       pca_1     pca_2
 0   3.411991  3.987782
 1   2.302094  4.540261
 2  -2.253127 -8.153847
 3  10.221481  0.378712
 4  -2.845585 -1.492732,
 (1011, 2),
 array([0.03762878, 0.02828712]))

In [22]:
# centroids through PCA
pca_centroids = pca.transform(centroids)
pca_centroids.shape

(19, 2)

In [23]:
df_with_emb = pd.concat([df.drop(columns=['Embedding']), df_pca, df_kmeans], axis=1)
df_with_emb.head()

,Motion,Info Slide,Tournament,og_points,oo_points,cg_points,co_points,og_wins,oo_wins,cg_wins,...,round_1,stage_1,round_2,stage_2,Year,Motion Type,Motion (cleaned),pca_1,pca_2,centroid
0,This House Supports strict state secularism* in Western Liberal Democracies.\r\n*this includes p...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Round 1,P,NaN,NaN,2024.0,supports,strict state secularism* in western liberal democracies\r\n*this includes prohibiting religious ...,3.411991,3.987782,5
1,This House Prefers A World where Truth and Reconciliation Commissions were established to deal w...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Round 2,P,NaN,NaN,2024.0,prefers,a world where truth and reconciliation commissions were established to deal with the aftermath o...,2.302094,4.540261,17
2,This House Would ban sports betting.,Sports betting is a form of gambling where people bet money on the outcome of\nsports events (eg...,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Round 3,P,NaN,NaN,2024.0,would,ban sports betting,-2.253127,-8.153847,13
3,This House Believes That New Age wellness culture has done more harm than good.,"New Age wellness culture is the rising focus on promoting self-care and self-\nimprovement, incl...",wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Round 4,P,NaN,NaN,2024.0,believes,new age wellness culture has done more harm than good,10.221481,0.378712,6
4,This House believes that major tourist destinations should significantly limit the number of tou...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Round 5,P,NaN,NaN,2024.0,believes,major tourist destinations should significantly limit the number of tourists can visit,-2.845585,-1.492732,16

In [24]:
import plotly.graph_objects as go

fig = go.Figure()

marker = go.scatter.Marker(
    color=df_with_emb['centroid'],
    colorscale='rainbow',
    size=10,
    opacity=0.7
)

centroid_marker = go.scatter.Marker(
    symbol='x',
    size=20,
    opacity=0.5,
    color='gray'
)

fig.add_trace(go.Scatter(x=df_with_emb['pca_1'], y=df_with_emb['pca_2'], mode='markers', hovertext=df_with_emb['Motion'], marker=marker))
# fig.add_trace(go.Scatter(x=pca_centroids[:, 0], y=pca_centroids[:, 1], mode='markers', marker=centroid_marker))

fig.show()

In [25]:
df_with_emb.sort_values('centroid')[['Motion (cleaned)', 'centroid']]

,Motion (cleaned),centroid
446,newly-established democracies should have laws restricting academic freedom,0
80,we oppose universities suspending students who engage in disruptive protests,0
633,reject saudi arabian investments in education,0
...,...,...
35,the state should offer a wage to primary domestic caretakers,18
158,states with low fertility rates should implement the hanson proposal,18
367,we should incentivise the construction of build-to-rent housing,18

### t-SNE

In [26]:
from sklearn.manifold import TSNE

tsne = TSNE(n_components=3, random_state=42)
X_tsne = tsne.fit_transform(df_embeddings)

df_tsne = pd.DataFrame(X_tsne, columns=['tsne_1', 'tsne_2', 'tsne_3'])
tsne.kl_divergence_

1.4598755836486816

In [27]:
df_with_emb2 = pd.concat([df_with_emb, df_tsne], axis=1)

In [28]:
px.scatter_3d(df_with_emb2, x='tsne_1', y='tsne_2', z='tsne_3', hover_data='Motion', color='centroid',color_continuous_scale=px.colors.sequential.Jet)

## Auto-label categories with LLMs

In [29]:
import vertexai
from google import genai

from dotenv import load_dotenv
load_dotenv()

client = genai.Client(vertexai=True, project=os.getenv("VERTEXAI_PROJECT_ID"), location="us-central1")

/Users/alekseiterin/Documents/personal/debates/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning:

urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020

In [40]:
by_category = df_with_emb2.groupby("centroid")

In [41]:
for centroid, group in by_category:
    motions_list = group['Motion'].to_list()
    all_motions = '\n'.join(motions_list)

    user_prompt = f"""
    You are given a list of motions that are related to a single topic or theme. Your task is to label these motions with a single category that best describes all of them on average, yet be very specific.

    Return your answer as just the category name (1-4 words), no other text.

    Motions:
    {all_motions}
    """
    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=user_prompt
    )

    df_with_emb2.loc[df_with_emb2['centroid'] == centroid, 'category'] = response.text

    print(centroid, response.text)
    print(motions_list[:3])

0 Reforming Tertiary Education

['This House believes that we should abolish academic tenure', 'This House believes that we should have distinct teaching professionals teach at universities rather than professors', 'This House believes that we support bonded government scholarships in developing countries.']
1 Motions of Regret and Action

["This House supports France's exit from West Africa.", 'This House believes that we would undergo the procedure', 'This House believes that, as Japan, we would host US nuclear missiles']
2 Contested Feminist Strategies/Priorities

['This House opposes attempts by the feminist movement to redefine traditionally feminine* roles and behaviours as empowering. \r\n\r\n*e.g. wearing makeup and heels, wanting to be a housewife, and so on.', 'This House believes that the feminist movement should encourage women to avoid feminine linguistic behaviours (e.g. uptalk, low modality language)', 'This House believes that, as the feminist movement, we would encourage women to reject acts of chivalry (e.g. men buying drinks, holding doors open, "ladies first")']
3 Electoral Politics and Reform

['This House would put an upper age limit of 60 years old for individuals running for political office.', 'This House believes that democracies should hold elections immediately post-COVID.', 'This House believes that we should redraw electoral boundaries to eliminate safe seats/districts as far as possible.']
4 Policy and Ethics Debates

['This House believes that we support the use of human challenge trials', 'This House believes that health care providers should be allowed to offer terminally ill patients the option of a cash grant if they forgo treatment', 'This House believes that we support character integrity obligations clauses']
5 Religion and Society
['This House Supports strict state secularism* in Western Liberal Democracies.\r\n*this includes prohibiting religious symbols in public spaces, not providing funding to religious schools and charities, not having an official state religion, etc', 'This House believes that states should actively discourage self-segregation of immigrant/ethnic/religious communities', 'This House believes that the government should force all religious charities to strictly avoid religious messaging in their charity activity']
6 Critiques of Social Movements

['This House Believes That New Age wellness culture has done more harm\xa0than\xa0good.', "This House believes that the perception of being a 'model minority' has brought more harms than benefits to the Asian diaspora in Western nations", 'This House believes that individuals who display neurodivergent traits should be given a diagnosis regardless of how severely those traits impact their lives']
7 Societal Values and Norms
['This House regrets the narrative that money cannot buy happiness.', 'This House believes that we support strong norms encouraging children to highly prioritise the pursuit of excellence in competitive hobbies (e.g. debating, netball, e-sports)', 'This House believes that we would support a dominant narrative in society that there exists a soulmate for everyone']
8 International Relations and Policy

['This House believes that we support the formation of an EU army', "This House believes that Russia's grain exports should be exempt from sanctions", 'This House believes that the UN should deploy troops alongside its current WHO presence in the Democratic Republic of Congo to contain Ebola outbreaks']
9 China's Geopolitical Strategy
['This House, as Serbia, would develop closer ties with China at the expense of ties with the European Union.', 'This House believes that, as China, we would impose economic sanctions on Myanmar.', 'This House believes that it is in the interests of India to maintain economic and military ties with Russia.']
10 Professional Sports Governance
['This House regrets the glorification of champions.', 'This House believes that we prefer sports leagues with fewer teams that have a greater concentration of talented players to leagues with more teams but a greater dilution of talented players', 'This House believes that sporting clubs should be majority-owned by the local communities they represent']
11 Law and Criminal Justice Reform

['This House would allow violent offenders to opt into Pavlovian conditioning as a substitution for prison time.', 'This House believes that we should allow prisoners to volunteer for socially utile but undesirable activities in exchange for a lighter sentence (e.g. experimental drug trials, military service, hard labour)', 'This House believes that we prefer a world in which those accused of crimes remain completely anonymous to the public unless they receive a guilty verdict']
12 Environmental Policy and Advocacy

['This House believes that all green energy policies should be source neutral', 'This House believes that environmentalist movements should cease opposition to the Thacker Pass Lithium mine', 'This House believes that Australian environmentalists should advocate for stricter fuel efficiency standards in vehicles rather than electric vehicle subsidies']
13 Government Regulation of Business
['This House Would ban sports betting.', 'This House believes that, as the progressive movement, we would oppose censorship by social media companies (e.g. Spotify and Facebook)', 'This House believes that regulators should implement the Platform Utility model of anti-trust action']
14 Post-Colonial Politics and Governance

['This House believes that it is in the interests of media outlets in nascent democracies to give the state a right of reply', 'This House believes that in post-colonial states we prefer an emphasis on regional and interstate identities (e.g. Pan-Arabism, Pan-Africanism) rather than building national identities.', 'This House believes that we regret the ongoing prominence of cricket in postcolonial countries.']
15 Global Financial Regulation and Policy

['This House believes that resource-backed loans to developing nations do more harm than good', 'This House believes that central banks should raise their inflation target rate.', 'This House believes that we regret the Obama Administration’s decision not to criminally prosecute major banks and bankers in the aftermath of the global financial crisis']
16 Global Governance & Policy

['This House believes that major tourist destinations should significantly limit the number of tourists that can visit.', 'This House believes that developing nations should introduce policies to heavily discourage the development of monarch cities', 'This House believes that we should abolish Greenfield agreements']
17 Hypothetical World Preferences

['This House Prefers A World where Truth and Reconciliation Commissions were established to deal with the aftermath of the Yugoslav Wars rather than the ICTY.', 'This House believes that we prefer a world with Artificial Persona technology', 'This House believes that we prefer a world in which Veritaserum was in the global water supply']
18 Government Economic Intervention

['This House would introduce a governmental basic income for all artists, rather than offering governmental fellowships and grants to certain artists upon application.', 'This House believes that the state should offer a wage to primary domestic caretakers', 'This House believes that the Australian government should enact a job guarantee']

In [53]:
category_counts = df_with_emb2.value_counts('category')
px.bar(category_counts)

In [67]:
most_common_category = category_counts.idxmax()
df_with_emb2[df_with_emb2['category'] == most_common_category]['Motion'].head()

9                                       This House regrets the narrative that money cannot buy happiness.
19    This House believes that we support strong norms encouraging children to highly prioritise the p...
27    This House believes that we would support a dominant narrative in society that there exists a so...
36    This House believes that we regret the existence of war memorial days (e.g. ANZAC Day, Remembran...
46    This House believes that, as a first year university student, we would take active steps to ente...
Name: Motion, dtype: object

## Context/prerequisites analysis

In [69]:
def rank_motion_difficulty(motion: str, info_slide: str): 
    user_prompt = f"""
    You are given a motion (and optionally its info slide) from a debate tournament. Your task is to rank how much background knowledge is required properly understand and debate this motion.
    If it is something an average intelligent voter would already know and understand, assign a score of 1.

    Return your answer as a single an integer between 1 and 5, no other text.

    Examples:

    This house prefers a world where genius only develops after adulthood (so that there are no child prodigies). [1]
    This house prefers that progressive journalists focus their efforts on working within and reforming mainstream news platforms, as opposed to establishing their own platforms. [2]
    This House prefers a diverse number of highly competitive banks to a small number of banks. [3]
    THBT Panama should replace the US dollar with its own independent currency. [4]

    (Info slide):
    {info_slide}
    Motion:
    {motion}
    """

    response = client.models.generate_content(
        model="gemini-2.0-flash",
        contents=user_prompt
    )

    return int(response.text)

In [ ]:
df_with_emb2.loc[:10, 'Background knowledge'] = df_with_emb2[:10].apply(lambda x: rank_motion_difficulty(x['Motion'], x['Info Slide']), axis=1)
df_with_emb2.head()

,Motion,Info Slide,Tournament,og_points,oo_points,cg_points,co_points,og_wins,oo_wins,cg_wins,...,Motion Type,Motion (cleaned),pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,Difficulty
0,This House Supports strict state secularism* in Western Liberal Democracies.\r\n*this includes p...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,supports,strict state secularism* in western liberal democracies\r\n*this includes prohibiting religious ...,3.411991,3.987782,5,-13.523347,23.044777,17.509626,Religion and Society,3.0
1,This House Prefers A World where Truth and Reconciliation Commissions were established to deal w...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,prefers,a world where truth and reconciliation commissions were established to deal with the aftermath o...,2.302094,4.540261,17,-36.665039,32.789654,19.391941,Hypothetical World Preferences\n,4.0
2,This House Would ban sports betting.,Sports betting is a form of gambling where people bet money on the outcome of\nsports events (eg...,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,would,ban sports betting,-2.253127,-8.153847,13,-4.056374,-33.356461,-16.674866,Government Regulation of Business,2.0
3,This House Believes That New Age wellness culture has done more harm than good.,"New Age wellness culture is the rising focus on promoting self-care and self-\nimprovement, incl...",wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,believes,new age wellness culture has done more harm than good,10.221481,0.378712,6,-35.233570,-3.910635,-13.245320,Critiques of Social Movements\n,2.0
4,This House believes that major tourist destinations should significantly limit the number of tou...,NaN,wsdc2024:wsdc2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,believes,major tourist destinations should significantly limit the number of tourists can visit,-2.845585,-1.492732,16,17.447420,-3.919208,27.846468,Global Governance & Policy\n,2.0

In [71]:
difficulty_freq = df_with_emb2['Difficulty'].value_counts().sort_index()
px.bar(difficulty_freq, y='count', title='Difficulty Frequency')

In [ ]:
# pd.set_option('display.max_rows', 10)
# df_with_emb2[df_with_emb2['Difficulty'].notna()].sort_values(by='Difficulty', ascending=True)

## Balance

In [70]:
df_with_emb2.sample()

,Motion,Info Slide,Tournament,og_points,oo_points,cg_points,co_points,og_wins,oo_wins,cg_wins,...,Motion Type,Motion (cleaned),pca_1,pca_2,centroid,tsne_1,tsne_2,tsne_3,category,Difficulty
946,THBT left wing criticism of liberal NGOs for failing to be intersectional brings more harm than ...,"Recently, there has been a rise in left-wing criticism of liberal NGOs for failing to be interse...",eudc2024:_,97.0,70.0,60.0,49.0,0.0,0.0,0.0,...,believes,left wing criticism of liberal ngos for failing to be intersectional brings more harm than good,4.297802,1.451082,6,-13.386222,9.373111,-30.126562,Critiques of Modern Activism\n,NaN

In [97]:
og_points = df_with_emb2['og_points'].sum()
oo_points = df_with_emb2['oo_points'].sum()
cg_points = df_with_emb2['cg_points'].sum()
co_points = df_with_emb2['co_points'].sum()

In [99]:
data = [
    [og_points, oo_points],
    [cg_points, co_points]
]

In [101]:
px.imshow(data, text_auto=True)

In [104]:
og_wins = df_with_emb2['og_wins'].sum()
oo_wins = df_with_emb2['oo_wins'].sum()
cg_wins = df_with_emb2['cg_wins'].sum()
co_wins = df_with_emb2['co_wins'].sum()


all_wins = og_wins + oo_wins + cg_wins + co_wins

og_percent_wins = og_wins / all_wins
oo_percent_wins = oo_wins / all_wins
cg_percent_wins = cg_wins / all_wins
co_percent_wins = co_wins / all_wins

data = [
    [og_percent_wins, oo_percent_wins],
    [cg_percent_wins, co_percent_wins]
]

px.imshow(data, text_auto=True)

## comments/suggestions
- diversity in race, gender etc.
- probability cloud (?)

## Team wins (balance)

In [29]:
prop_wins = df['Prop wins'].sum()
opp_wins = df['Opp wins'].sum()

print(prop_wins, opp_wins)

px.pie(
    values=[prop_wins, opp_wins],
    names=['Prop wins', 'Opp wins'],
    title='Total Prop vs Opp Wins',
).show()

KeyError: 'Prop wins'

In [11]:
prop_wins = df_this_year['Prop wins'].sum()
opp_wins = df_this_year['Opp wins'].sum()

print(prop_wins, opp_wins)

px.pie(
    values=[prop_wins, opp_wins],
    names=['Prop wins', 'Opp wins'],
    title='Total Prop vs Opp Wins',
).show()

196.0 85.0

In [ ]:
# take a look at thow this varies by rounds (e.g. outrounds)

## Export for website

In [92]:
df_with_emb2.to_json('data/motions.json', orient='records')